### ISSUE TITLE
Syntax error: '��4�*B4' unexpected

### ISSUE THREAD

**Issue by devgianlu** [aria2/aria2#1002]
I'm running the aria2c executable on Android. When I try to execute it I get this error: `/path/to/aria2c[1]: syntax error: '��4�*B4' unexpected`. The device is running Android 6.0 and the arch is x86.

**Comment by devgianlu** [comment]
I'm using this one: https://github.com/aria2/aria2/releases/download/release-1.32.0/aria2-1.32.0-android-build1.zip. Not sure what it's built for.

**Comment by tatsuhiro-t** [comment]
It is for ARM, not for x86.

**Comment by devgianlu** [comment]
Got it. I'll compile my own for x86.
