### ISSUE TITLE
Aria2c does not percent decode URLs appropriately.

### ISSUE THREAD

**Issue by Metamba** [aria2/aria2#1007]
I use aria2c for http downloads but it usually messes up the downloaded file name.

Is there any way to resolve this?

**Comment by kkartaltepe** [comment]
%2F is a '/' which cant be represented on most file systems as part of a name. As such it is left in encoded form, and even if it could I dont think it should be decoded. This seems correct to me.

If you wanted it inside a folder consider storing it in a container format like zip.

Also please do not link potentially copyright infringing content here.

**Comment by Metamba** [comment]
Thanks.

**Comment by Schezuk** [comment]
> %2F is a '/' which cant be represented on most file systems as part of a name. As such it is left in encoded form, and even if it could I dont think it should be decoded. This seems correct to me.
> 
> If you wanted it inside a folder consider storing it in a container format like zip.
> 
> Also please do not link potentially copyright infringing content here.

Percent-encoding doubles or triples the length of file name, thus causing failure to create files.
