### ISSUE TITLE
File download error! （Open the check file md5 to find the problem）

### ISSUE THREAD

**Issue by q158073378252010** [aria2/aria2#1017]
File download error!
For example: address "A" download a file "F" (the server provides a file "F" check md5), and so after the download is complete, the file will be different from the value provided by the server! But use the other download tool to use the same address "A" to download the same value after the server!
It seems that the video file is not much impact, but the compressed package on the dangerous!
Test found in linux and windows are there! However macOS no test!
If I need such an address I can provision temporarily (because this address contains cookies)

**Comment by mostafa88** [comment]
I have this problem too. It seems that Aria2c face this issue when downloading large files. In my case, there is a binary file that is about 1.4 GB. I download it twice and compare them to the original file. It seems that only 31 bytes are different, but the location of the diffs are not same it both files. 
I attach comparison results.
In the following results the "SOUND.DCP.IDM" is the original file and the other one is the downloaded file.

[diff1.txt](https://github.com/aria2/aria2/files/1352375/diff1.txt)
[diff2.txt](https://github.com/aria2/aria2/files/1352376/diff2.txt)

**Comment by tatsuhiro-t** [comment]
#1012 might be related to this issue.

**Comment by antbryan** [comment]
@q158073378252010 can you give a test link? is it HTTP or HTTPS?

can you check if aria2 1.33.0 (which includes #1012 fix mentioned by @tatsuhiro-t ) fixes your issue?

https://github.com/aria2/aria2/releases/tag/release-1.33.0

**Comment by q158073378252010** [comment]
@antbryan 
Part of the connection test passed! But there is connection test failed! !
My file link from Baidu cloud.

`aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "Qt/Qt_For_Android/QtOnAndorid/好程序员2015最新Android应用视频教程/Loader的自定义(1).mov" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: BDUSS=9XcUlnaFZxUXFJSUV1WkNvSzBBSW5rY3FmU0FzYlFad2s1S3d1MXdKbmdieXBhSUFBQUFBJCQAAAAAAAAAAAEAAABPuXgXyq7I~aG2tv6htwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODiAlrg4gJaam; pcsett=1510226439-f5916ada3785397ae466d713ce1304c7" "https://d.pcs.baidu.com/file/1662cacd8d73c0fb1c5fd5823186e9c1?fid=3105030567-250528-338730737644176&time=1510140110&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-krj%2B5yzpDmoH8fcklSiLrFZxsmE%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7231680902494061695&dp-callid=0&r=668477203" --checksum=md5=1662cacd8d73c0fb1c5fd5823186e9c1`
