### ISSUE TITLE
CAN NOT download this file

### ISSUE THREAD

**Issue by adaaaaaa** [aria2/aria2#1029]
ftp://ygdy8:ygdy8@y201.dygod.org:1224/[阳光电影www.ygdy8.com].帕丁顿熊.BD.720p.中英双字幕.rmvb

aria2 version: 1.33.0

**Comment by adam1x** [comment]
Can you download it directly with the browser?

What's the error message? If it's `Failed to resolve the hostname y201.dygod.org, cause: nodename nor servname provided, or not known` (like on my end), then either you need to switch to another DNS server or that particular link is down.

**Comment by adaaaaaa** [comment]
it's OK to download with other tool...

error output below:
[root@PandoraBox_7D29:/usr]#aria2c ftp://ygdy8:ygdy8@y201.dygod.org:1224/[ww
w.ygdy8.com]..BD.720p..rmvb

10/18 16:29:49 [NOTICE] Downloading 1 item(s)

10/18 16:29:49 [ERROR] CUID#7 - Download aborted. URI=ftp://ygdy8:ygdy8@y201.dygod.org:1224/[%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1www.ygdy8.com].%E5%B8%95%E4%B8%81%E9%A1%BF%E7%86%8A.BD.720p.%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97%E5%B9%95.rmvb
Exception: [AbstractCommand.cc:351] errorCode=19 URI=ftp://ygdy8:ygdy8@y201.dygod.org:1224/[%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1www.ygdy8.com].%E5%B8%95%E4%B8%81%E9%A1%BF%E7%86%8A.BD.720p.%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97%E5%B9%95.rmvb
  -> [AbstractCommand.cc:792] errorCode=19 CUID#7 - Name resolution for y201.dygod.org failed:DNS server returned answer with no data

10/18 16:29:49 [NOTICE] Download GID#e49a359122a192b6 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e49a35|ERR |       0B/s|ftp://ygdy8:ygdy8@y201.dygod.org:1224/[%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1www.ygdy8.com].%E5%B8%95%E4%B8%81%E9%A1%BF%E7%86%8A.BD.720p.%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97%E5%B9%95.rmvb

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by adaaaaaa** [comment]
[aria2.log](https://github.com/aria2/aria2/files/1394881/aria2.log)

**Comment by tatsuhiro-t** [comment]
try --async-dns=false

**Comment by adaaaaaa** [comment]
log is here...@tatsuhiro-t 

[root@PandoraBox_7D29:/root]#aria2c ftp://ygdy8:ygdy8@y201.dygod.org:1224/[w
ww.ygdy8.com]..BD.720p..rmvb --async-dns=false

10/19 08:57:48 [NOTICE] Downloading 1 item(s)

10/19 08:57:48 [ERROR] CUID#7 - Download aborted. URI=ftp://ygdy8:ygdy8@y201.dygod.org:1224/[%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1www.ygdy8.com].%E5%B8%95%E4%B8%81%E9%A1%BF%E7%86%8A.BD.720p.%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97%E5%B9%95.rmvb
Exception: [AbstractCommand.cc:351] errorCode=19 URI=ftp://ygdy8:ygdy8@y201.dygod.org:1224/[%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1www.ygdy8.com].%E5%B8%95%E4%B8%81%E9%A1%BF%E7%86%8A.BD.720p.%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97%E5%B9%95.rmvb
  -> [NameResolver.cc:60] errorCode=19 Failed to resolve the hostname y201.dygod.org, cause: Name or service not known

10/19 08:57:48 [NOTICE] Download GID#6ce7fdd1957c5831 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
6ce7fd|ERR |        n/a|ftp://ygdy8:ygdy8@y201.dygod.org:1224/[%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1www.ygdy8.com].%E5%B8%95%E4%B8%81%E9%A1%BF%E7%86%8A.BD.720p.%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97%E5%B9%95.rmvb

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by adaaaaaa** [comment]
with AriaNg i got this log file:[aria2.log](https://github.com/aria2/aria2/files/1396784/aria2.log)
@tatsuhiro-t

**Comment by adam1x** [comment]
From the looks of your error message, aria2 can’t resolve the domain name of your download link. Run a `dig` or `nslookup` on y201.dygod.org and see if your DNS server can resolve this domain name.

Which tool can you successfully download it with? And, are you sure it is downloading through the link directly and not P2P?

**Comment by adaaaaaa** [comment]
http://r6---sn-a5meknel.googlevideo.com/videoplayback?ipbits=0&lmt=1505638935671216&sparams=dur,ei,expire,id,initcwndbps,ip,ipbits,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,source&key=cms1&expire=1508668193&itag=22&ei=wR7sWcLfFNHSVuLvksAE&dur=7330.957&ip=192.117.146.110&pl=21&id=o-ANhyCe5DEJ9x05nNyQCvfGh8qYtSHGCNHlDGZSIKVRJq&ratebypass=yes&source=youtube&signature=1F38FFF503E1EA7DE759DD3ABEC06C0E9E794F09.0F8DF54D7F6A1C75882D63878E7EE9F4548EB1A9&mime=video%2Fmp4&title=%E7%AC%AC%E4%BA%8C%E8%AF%BE%EF%BC%9A%E8%BF%87%E6%8B%9F%E5%90%88%E3%80%81%E5%A4%9A%E5%B1%82%E6%84%9F%E7%9F%A5%E6%9C%BA%E3%80%81GPU%E5%92%8C%E5%8D%B7%E7%A7%AF%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C&redirect_counter=1&cm2rm=sn-aigess7s&req_id=6d85dc3133b2a3ee&cms_redirect=yes&mip=97.64.44.72&mm=34&mn=sn-a5meknel&ms=ltu&mt=1508647823&mv=m

can you download this video file in aria2 1.33.0 ?  @adam1x

**Comment by adaaaaaa** [comment]
![image](https://user-images.githubusercontent.com/23206387/31858378-be6532b8-b728-11e7-9f7d-31cf00fc916c.png)
 
the first file it download almost from (mirror accelerate)? a little bit from P2P...

**Comment by adam1x** [comment]
You see, you are downloading from a "mirror" and P2P, while the original source contributes nothing at all. This means the source is down, hence why aria2 or the browser, for that matter, can't download it.

**Comment by adam1x** [comment]
For YouTube downloads, try [youtube-dl](https://github.com/rg3/youtube-dl) with this argument: `--external-downloader aria2c`.

**Comment by adaaaaaa** [comment]
it means aria2 can only download from source? @adam1x

**Comment by adam1x** [comment]
Well what do you think? Without massively breaching its users' privacy (proactively scanning every user's hard drive for any "valuable" file), how do you expect a downloader to be able to do P2P with a non-BT/ed2k/.. link?
