### ISSUE TITLE
Bug: aria2 takes too much cpu when downloading bittorrent

### ISSUE THREAD

**Issue by qweaszxcdf** [aria2/aria2#1031]
![1](https://user-images.githubusercontent.com/10515874/31719615-9a809fa2-b446-11e7-860e-f12430564970.jpg)
I'm using aria2c 1.33 win64
here is the magnet 
magnet:?xt=urn:btih:f13541e37e9e2a58c8e090fc8a1f30836a4541df&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=http://tr.cili001.com:8070/announce&tr=http://tracker.trackerfix.com:80/announce&tr=udp://open.demonii.com:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://p4p.arenabg.com:1337&tr=wss://tracker.openwebtorrent.com&tr=wss://tracker.btorrent.xyz&tr=wss://tracker.fastcast.nz

**Comment by adaaaaaa** [comment]
maybe it's mining bitcoin......![default](https://user-images.githubusercontent.com/23206387/31720316-cea09cea-b448-11e7-90e2-853d4c649467.gif)

**Comment by kangmya** [comment]
The same is true of me, CPU occupancy rate is high, in exchange for version 1.32 normal

**Comment by kangmya** [comment]
1.33  WIN64
