### ISSUE TITLE
can't write into portable hard disk

### ISSUE THREAD

**Issue by sunrisewestern** [aria2/aria2#1032]
CUID#27 - Exception caught while allocating file space.
Exception: [AbstractDiskWriter.cc:542] errNum=45 errorCode=17 fcntl(F_PREALLOCATE) of 655534161 failed. cause: Operation not supported

When I change to ~/Downloads it worked well.

**Comment by tatsuhiro-t** [comment]
--file-allocation=falloc might not work depending on the file system.  Try other file allocation method.

**Comment by sunrisewestern** [comment]
Thanks, I changed it back to --file-allocation=none and it works, but I'm using NTFS.
