### ISSUE TITLE
Help with remote connection

### ISSUE THREAD

**Issue by iCsav** [aria2/aria2#1036]
I want to view my Aria2 downloads and add a new one from anywhere. I also plan to use the Aria2App for Android. The WebUI works correctly for localhost but I can't get it to work with any other ip. Do I need to forward ports? If so, which ones and how? Sorry for not knowing much, I'm new to this. Any help is much appreciated.

**Comment by adam1x** [comment]
Security issues aside, if you just want to access the web UI outside, you will need to set up port forwarding on your router (assuming the web UI is running on another machine), and you probably need a DDNS service for easy access to your home IP address (unless you get a static IP from your ISP, which is unlikely).

**Comment by iCsav** [comment]
@adam1x  Thanks, I figured that out recently. Forgot to close the issue. Sorry. And yes, I'm now using a DDNS service. Also, what security issues would I be facing by doing this?

**Comment by adam1x** [comment]
Well, there's always security risks involved when you are opening up your LAN to the entire internet. If you're not careful with configurations, or your devices have vulnerabilities, it's entirely possible for others to breach into your LAN. Not to mention there are bots scanning open networks looking for vulnerabilities 24/7.
