### ISSUE TITLE
aria2-1.33 takes too much cpu

### ISSUE THREAD

**Issue by underlaw** [aria2/aria2#1041]
v 1.33 win64

When aria downloads, CPU takes up too much, about 18% to 19%.

**Comment by Youxikong** [comment]
v 1.33 win64

Takes up about 30%.

**Comment by Deadooshka** [comment]
v1.33 win32 win7 ~50% on old 2-core cpu.

**Comment by tatsuhiro-t** [comment]
I would appreciate it if anyone performs 'git bisect' to find a commit which causes high CPU usage.
