### ISSUE TITLE
Just a crazy idea

### ISSUE THREAD

**Issue by wu67** [aria2/aria2#1047]
If we will get an option like `torrent-dir`?

Sometimes i try to download some sources(releases by magnet), and i want the '.torrent' too.
But the torrent file will save with the sources, finally they made a mess in my Download folder .
 
eg:
```
...
dir=/Donwload
torrent-dir=/mytorrents
...
```

even: 
```
...
dir=/download
bt-dir=/btFilePath
torrent-dir=/mytorrents
...
```

**Comment by underlaw** [comment]
good idea,You might also add a function to select files when you download

**Comment by underlaw** [comment]
最好能实现前台删除文件，也能删除硬盘上的文件

**Comment by underlaw** [comment]
Best to achieve the front desk to delete files, but also to delete files on the hard disk

**Comment by kkartaltepe** [comment]
@underlaw you can already selectively download files with `-S/--show-files` to show files in the torrent and then selectively download them with the `--select-file` option

You can probably automate this torrent file moving yourself using the event hooks described here
https://aria2.github.io/manual/en/html/aria2c.html#event-hook

I do think it would be useful to store torrent/metadata/control files in a separate location to prevent cluttering download locations.

**Comment by wu67** [comment]
@kkartaltepe 
I try:
```
# aria2.conf
on-download-complete=mv /Users/wk/Downloads/*.torrent /Users/wk/.torrent/
```
but get a message that:
```
# cli
[NOTICE] Saved metadata as /Users/wk/Downloads/6dc1c37e69576426a63570dd3642c7d4e6f4c082.torrent.
Could not execute user command: mv /Users/wk/Downloads/*.torrent /Users/wk/.torrent/: No such file or directory
```
----------

Then I try:
```
# aria2.conf
on-download-complete=/Users/wk/.aria2/torrent.sh
// or 
on-download-complete=sh /Users/wk/.aria2/torrent.sh
```
```
# torrent.sh
mv /Users/wk/Downloads/*.torrent /Users/wk/.torrent/
```
and i get the same message above.

**Comment by kkartaltepe** [comment]
the only valid `on-download-complete` you listed was 
`on-download-complete=/Users/wk/.aria2/torrent.sh`

This option takes a single executable as its argument. In your first example you tried to pass it the text of a shell script, which is incorrect. Your third example is similarly incorrect.

And if you are running this under windows you will need to ensure things are executable by windows natively (I think).

**Comment by wu67** [comment]
But actually, i try the second way, and it doesn't work(In my Mac mini).

Thanks for your comments. I've given up ...

**Comment by underlaw** [comment]
@kkartaltepe thx
