### ISSUE TITLE
Too large HTTP header with JSON-RPC over HTTP

### ISSUE THREAD

**Issue by devgianlu** [aria2/aria2#1050]
When trying to add a torrent file through RPC with HTTP, I get a receive failure on the client and a "Too large HTTP header" exception on aria2. The request URL is pretty big and it's around 26kb because the torrent file is base64 encoded into the "params" parameter. I know I could use Websockets, but I also need to do it over HTTP. A solution may be enabling POST requests.

**Comment by tatsuhiro-t** [comment]
aria2 has already supported POST-style RPC request for both XML-RPC and JSON-RPC.  It looks like you are using JSONP?

**Comment by devgianlu** [comment]
I'm not using JSONP. Could you explain how should I send POST  requests? It's not mentioned in the docs.

**Comment by tatsuhiro-t** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface

**Comment by devgianlu** [comment]
I tried sending some requests with POST but the server always responded with 500 (parse error). I am trying to send data putting the URL parameters in the body of the request, but putting them in the URL doesn't work either. Do I have to send JSON?

**Comment by devgianlu** [comment]
I solved this issue by sending POST requests, which contains the JSON request in their body.
