### ISSUE TITLE
RPC-Server not responding after calling aria2.unpauseAll

### ISSUE THREAD

**Issue by HoseinGhanbari** [aria2/aria2#1067]
Hello !
I'm running aria2c on openWRT using the following command on system startup.

```
aria2c --enable-rpc --rpc-listen-all --allow-overwrite=true --auto-file-renaming=false --continue=true --dir=/mnt/usb/downloads --max-connection-per-server=4 --max-concurrent-downloads=1 --file-allocation=none --piece-length=50M --input-file=/mnt/usb/download_list --pause=true --rpc-secret=Just4Aria2c
```

I have two CRON jobs to start & stop the download progress.

```
00 02 * * * curl http://192.168.1.34:6800/jsonrpc -H "Content-Type: application/json" -H "Accept: application/json" --data '{"jsonrpc": "2.0","id":1, "method": "aria2.unpauseAll", "params":["token:Just4Aria2c"]}'

00 06 * * * curl http://192.168.1.34:6800/jsonrpc -H "Content-Type: application/json" -H "Accept: application/json" --data '{"jsonrpc": "2.0","id":1, "method": "aria2.pauseAll", "params":["token:Just4Aria2c"]}'
```

The issue is that, after starting download progress using aria2.unpauseAll, you can't send any new command to the rpc server using curl.

Actually, when you type proper curl commands to call aria2c cammands, and then hitting the return key, you don't get any results, it's just waiting and nothing happens in the console.

Thank you sincerely for your help!

**Comment by tatsuhiro-t** [comment]
It works for me.  Could you check that aria2c server receives RPC request?

**Comment by HoseinGhanbari** [comment]
Thank you very much for your quick response!
How can I check that?

As i mentioned before, when the downloads started, I can't pause them using curl command; actually no response comes back from the rpc server.

**Comment by tatsuhiro-t** [comment]
For example, you can use -l option to show aria2 log.

**Comment by HoseinGhanbari** [comment]
The issue is that, after sending the pauseAll command through curl, the aria2c is going to do the 'Cache flush' and during completing this action, nothing happens in the console; therefore I thought something went wrong !

I strongly recommend that add a simple log string immediately after calling pauseAll. It would be very helpful to show the user, aria2c is just doing the 'Cache flush'.

It's worth noting that, when I checked the log file, Cache flush has generated 984 lines before it's getting over !

Thank you so much for your help !
Thank you so much for this GREAT project !
