### ISSUE TITLE
Feature Request: Run external script on successful download.

### ISSUE THREAD

**Issue by clem16** [aria2/aria2#1076]
I've looked through the doc's but I couldn't find a switch that allowed running of external scripts on download event. (fail, succeed, err, etc).
Looks like there might be something similar in the bit torrent section. (--on-bt-download-complete=<COMMAND>)
Found nothing for regular http/s connections.

My usage case would be to trigger a pushover script on successful download.

If there's any other solutions that i'm completely overlooking please let me know.

Thanks for some great stuff guys, I use it daily.

**Comment by tatsuhiro-t** [comment]
There are several options for regular downloads:
https://aria2.github.io/manual/en/html/aria2c.html#event-hook

**Comment by clem16** [comment]
Thank you! Forgot to close this.
