### ISSUE TITLE
File modified timestamp gets extra hour when original's modified date is in DST range (Windows only?)

### ISSUE THREAD

**Issue by oh-ren** [aria2/aria2#1077]
When downloading with the timestamp option (`-R, --remote-time true`) the modified date of the downloaded file is exactly *one hour* ahead when the server file has a modified date that's within my tz's DST range.

At least, that's my finding comparing downloading files out- and inside the DST range.
Files outside the DST range seem to get correctly timestamped.

So e.g. a file with a `Last-Modified` datetime of `Mon, 07 Aug 2017 10:23:00 GMT` which Windows displays correctly as 12:23:00 otherwise (tz = GMT+1), becomes 13:23:00 when downloaded with Aria2.

Wget seems to suffer from the same flaw. Curl doesn't.

This is all on Windows (7) btw. Wget on a CentOS VM **doesn't** seem to suffer from this flaw.
Haven't tried to compile Aria2 to test this as well inside the VM.

**Comment by tatsuhiro-t** [comment]
Thank you for bringing this topic.  It looks like Windows _wutime adjusts time with DST.
Curl source code has the following comment:

```c
/* Windows utime() may attempt to adjust our unix gmt 'filetime' by a daylight
   saving time offset and since it's GMT that is bad behavior. When we have
   access to a 64-bit type we can bypass utime and set the times directly. */
```

It looks like using SetFileTime is a right approach for Windows.
