### ISSUE TITLE
aria2 -S see file

### ISSUE THREAD

**Issue by shichaohao** [aria2/aria2#1089]
Hi, when I  type "aria2c -S  'magnet:?.........................'" in the terminal, show "This file is neither Torrent nor Metalink file. Skipping."

So can I see the all files of the magnet and select part of them to download ?

Thanks.

**Comment by tatsuhiro-t** [comment]
-S works for local file only.
For magnet URIs, first download torrent metadata using --bt-save-metadata and --bt-metadata-only, and then use -S option against the downloaded torrent file.

**Comment by shichaohao** [comment]
Thank you

**Comment by jkldgoefgkljefogeg** [comment]
If would be nice to add this as a feature for -S to support magnet link
