### ISSUE TITLE
aria2 JSON-RPC does not work when I specified a config file on Mac 

### ISSUE THREAD

**Issue by webbin** [aria2/aria2#1094]
Hey guys! How to specify a config file to aria2? I use the command like this : 

> aria2c --conf-path=aria2.conf
aria2c --enable-rpc=true
12/20 16:34:05 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd  is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.
12/20 16:34:05 [NOTICE] IPv4 RPC: listening on TCP port 6800
12/20 16:34:05 [NOTICE] IPv6 RPC: listening on TCP port 6800
12/20 16:34:12 [NOTICE] 3 second(s) has passed. Stopping application.

the JSON-RPC works!
However, I found that the config file path is non-existing by invoking the "aria2.getGlobalOption([secret]) "method.
Because there is no a directory called "aria2",not to mentiong the "aria2.conf" file.

> "check-integrity":"false",
        "conditional-get":"false",
        "conf-path":"/Users/webbin/.config/aria2/aria2.conf",
        "connect-timeout":"60",
        "console-log-level":"notice",

If I create the config file in aira2/aria2.conf , the RPC cannot be started.
>webbins-Sierra:.config webbin$ cd aria2/
webbins-Sierra:aria2 webbin$ ls
aria2.conf
webbins-Sierra:aria2 webbin$ pwd
/Users/webbin/.config/aria2
webbins-Sierra:aria2 webbin$ aria2c --enable-rpc=true
webbins-Sierra:aria2 webbin$ 

It seems that running the command does nothing.

**Comment by tatsuhiro-t** [comment]
It woks for me.  Perhaps, configuration file is badly formatted?

**Comment by webbin** [comment]
@tatsuhiro-t Yes,I try again with another configuration file and it works.Thanks!
