### ISSUE TITLE
WinTLS Error

### ISSUE THREAD

**Issue by Quaraxkad** [aria2/aria2#1098]
I frequently receive the following error message: 
`[ERROR] WinTLS: Failed to encrypt a message! Error: The specified data could not be encrypted. (80090329)`
The download seems to be unaffected and completes successfully, as far as I can tell.

A _similar_ error is also mentioned here: https://github.com/aria2/aria2/issues/351
That thread suggests the cause is WinXP, however I am not using XP.

What does this error mean?

**Comment by tatsuhiro-t** [comment]
If download is not affected, it might happen on the very end of the connection where TLS session is teared down.
