### ISSUE TITLE
request 1 byte in Range request.

### ISSUE THREAD

**Issue by casouri** [aria2/aria2#1103]
**Problem**

I'm developing a file transfer tool which serves a file and support range request.
When testing with aria2c, server keeps receiving range requests for 1 byte when 99% of the file has been transferred. And that byte is not the last byte.

What may cause this issue?

My server is at here: https://github.com/PLUTO-ALicE-Assn/pass/blob/master/pass.c

**header received:**

```
GET / HTTP/1.1
User-Agent: aria2/1.33.1
Accept: */*
Host: localhost:8082
Range: bytes=1973202502-1973202502
Want-Digest: SHA-512;q=1, SHA-256;q=1, SHA;q=0.1
```

**Comment by tatsuhiro-t** [comment]
What is the size of the resource?  Are you saying that aria2 does not request the last byte?

**Comment by casouri** [comment]
No, they are not the last byte, and aria2c sends requests for different bytes, but all the requests have a length of one byte.
Let me later reproduce it and give you more information.

**Comment by casouri** [comment]
I'm sorry, it's the problem of the server. I'll close it now :P
