### ISSUE TITLE
A spelling mistake in "man aria2c"

### ISSUE THREAD

**Issue by jinshuichengliu** [aria2/aria2#1110]
--on-download-complete=<COMMAND>
              Set  the  command to be executed after download completed.  **_See See_** Event Hook for
              more details about COMMAND.  See also --on-download-stop option.  Possible Values:
              /path/to/command

double "See"

**Comment by tatsuhiro-t** [comment]
Fix committed via d791d0b6c3c086a8523f727d9d7aab550688a599
Thank you!
