### ISSUE TITLE
can not resolve hostname of ipv6 only private tracker

### ISSUE THREAD

**Issue by alanzhangzm** [aria2/aria2#1114]
aria2 works fine with ipv4 tracker, but when working with ipv6 private tracker, it can not resolve hostname of ipv6 only private tracker, and repeat the step of resolving hostname of the tracker.
Tested with aria2 1.33.1 on Debian 9 and aria2 1.33 on macOS 10.13.

**Comment by tatsuhiro-t** [comment]
It looks like aria2 doesn't resolve hostname to ipv6 address if no ipv6 address is configured (loopback address is excluded).  --async-dns=false will make aria2 reolve ipv6 address as a last resort.

**Comment by alanzhangzm** [comment]
@tatsuhiro-t my aria2 works perfectly with --async-dns=false. Thank you very much.
