### ISSUE TITLE
how to recheck the files and continue download

### ISSUE THREAD

**Issue by heimoshuiyu** [aria2/aria2#1116]
When I downloaded the bittorrent, Centos suddenly rebooted....
After that, I saw that the size of the file "*.aria2" was 0, and I re-added the seed link on web-ui, and it said failed to open the "*.aria2" file
and then I deleted the "*.aria2" and added the seed Link once again, it said the file already exists, 
I dare not add --allow-overwrite because this will start from 0 to download
What should I do???

Can aria2 recheck the file and continue download??

**Comment by heimoshuiyu** [comment]
I had found that add -V to restart can solve this problem.

**Comment by tatsuhiro-t** [comment]
-V is the right option to check file content.
