### ISSUE TITLE
Problem in downloading a 72 GB dataset(errorCode=8 Invalid range header)

### ISSUE THREAD

**Issue by vermaarjun7** [aria2/aria2#1129]
Hello!

I'm using aria2 version 1.19.0. I tried downloading the dataset several times but it fails. Below is the error.  

02/03 00:40:39 [ERROR] CUID#6 - Download aborted. URI=http://data.csail.mit.edu/soundnet/actions3/split1/Moments_in_Time_256x256_30fps.zip
Exception: [AbstractCommand.cc:350] errorCode=8 URI=http://data.csail.mit.edu/soundnet/actions3/split1/Moments_in_Time_256x256_30fps.zip
  -> [HttpResponse.cc:90] errorCode=8 Invalid range header. Request: 54683116136-77343182211/77343182212, Response: 0-77343182211/77343182212

02/03 00:40:39 [NOTICE] Download GID#0704c4425bba6281 not complete: /media/arjun/92975fe8-2050-422a-b3d3-6b2c814e9658/Moments_in_Time_256x256_30fps.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0704c4|ERR |   3.3MiB/s|/media/arjun/92975fe8-2050-422a-b3d3-6b2c814e9658/Moments_in_Time_256x256_30fps.zip

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by SumatraPeter** [comment]
Attaching the detailed log might help the dev figure out the problem.

Also, is only aria2 failing  or other tools too?

**Comment by vermaarjun7** [comment]
The log file is too big. I can post some part of it here if that helps. 

Yes, I tried downloading using uGet and its failing as well.

**Comment by SumatraPeter** [comment]
> I can post some part of it here if that helps.

It might help the dev of aria2 to diagnose the issue. However if other tools are failing too then how do you know the problem is at your end?

**Comment by vermaarjun7** [comment]
@SumatraPeter I asked the person who hosted the dataset on the website. Anyways it's downloaded.

**Comment by sdfww** [comment]
Encountered the same problem.

But a modified version of aria2 was found in a software called PanDownload, which does not have this problem. However, the author of the software did not disclose the source code of the modified aria2, which violated the GPL license.

**Comment by LovelyBloom** [comment]
> Encountered the same problem.
> 
> But a modified version of aria2 was found in a software called PanDownload, which does not have this problem. However, the author of the software did not disclose the source code of the modified aria2, which violated the GPL license.

you happen to have a local copy of this app? the author has made everything log-in mode in Chinese. I can't make sense of it

**Comment by beck-8** [comment]
You must be visiting the cloudflare website, just turn off the cache.

**Comment by zhangbo** [comment]
try "aria2c --file-allocation=none", work for me, seems like the target url only supports one time download, not continuously download
