### ISSUE TITLE
bitfield always 80 downloading torrent

### ISSUE THREAD

**Issue by TEDSON007** [aria2/aria2#1142]
When I download a file bitfield increases, as does CompletedLength when polling with aria2.tellStatus
When I download a torrent bitfield is stay at '80' and both CompletedLength and TotalLength stay at '7235'

I am trying to get progress.

**Comment by devgianlu** [comment]
When you start a torrent download with a magnet aria2 downloads the metadata first and then creates a new download with the real torrent. Maybe you're looking at the wrong download. Try seeing all of them with `aria2.tellActive`

**Comment by TEDSON007** [comment]
That was the problem.
