### ISSUE TITLE
fallocate when allocating disk space if the filesystem supports it

### ISSUE THREAD

**Issue by Tmplt** [aria2/aria2#1147]
Allocating disk space takes some time in aria2. With fallocate(1), I can allocate big files almost instantly:

```sh
$ time fallocate -l 30G big                    
fallocate -l 30G big  0.00s user 0.13s system 86% cpu 0.148 total
```

Could aria2 allocate disk space in this manner instead, if the filesystem supports it? I believe all required documentation is available in fallocate(2).

**Comment by myfreeer** [comment]
Do you mean `--file-allocation=falloc`?

**Comment by Tmplt** [comment]
I totally missed that flag; that's exactly what I'm looking for. Thank you.
