### ISSUE TITLE
save completed torrents for resume seeding

### ISSUE THREAD

**Issue by http403** [aria2/aria2#1150]
I hope the `--save-session` options can save completed torrents so I can resume seeding after restarting the session.

**Comment by blackCauldron7** [comment]
Does this work?

**Comment by mtmcf** [comment]
@blackCauldron7 yes

**Comment by blackCauldron7** [comment]
Doesn't work for me across sessions once the file is fully downloaded its removed from the session

**Comment by mtmcf** [comment]
it might not be enough, perhaps consider switching force-save to true as well ...? 
https://aria2.github.io/manual/en/html/aria2c.html?highlight=download%20complete#cmdoption-force-save

**Comment by blackCauldron7** [comment]
That does work but kinda pollutes the download directory with stale aria2 files.

**Comment by mtmcf** [comment]
Well, sorry, I'm already out of suggestions concerning aria2 ;) But for torrenting specifically, you might be better off moving to rtorrent ...^^" 

Which is precisely what I did the other day the other day... I got to know about aria2 while looking for a lightweight BT client, and even though it was nice for one shots (i.e. download file and shutdown process afterwards), once I finally figured out how to seed stuff, I started having some performance issues on my 256 MB RAM VPS, namely, every now and then the process was dying out of a sudden - and luckily I've yet to experience a similar problem with rtorrent :)

**Comment by http403** [comment]
Close as stale
