### ISSUE TITLE
Accept `content-disposition` HTTP header

### ISSUE THREAD

**Issue by http403** [aria2/aria2#1154]
I would like a option that could obtain filename via `content-disposition` header. Like `curl`'s -J option. Very useful when downloading with URL like `http://example.com/?fid=2939`.

**Comment by NightMachinary** [comment]
The manpage is confusing; Is this behavior implemented or not?

**Comment by NightMachinary** [comment]
It seems this is supported but the implementation can't handle the wild:

https://github.com/aria2/aria2/issues/1118

**Comment by http403** [comment]
Since #1118 covered the topic in this issue. To avoid duplication, I will close this one.
