### ISSUE TITLE
Aria2 cannot download anything!

### ISSUE THREAD

**Issue by leslievan** [aria2/aria2#1159]
Hello!

aria2 version: 1.19.0
system version: Ubuntu 16.04

I want to change the proxy setting with '--all-proxy="http://xxxx:1080"' and '--http-proxy="http://xxxx:1080"'.
I do it. But then I find I can't download anything. While I input a URL and want to download it. It will return an error information.
```
Exception caught
Exception: [download_helper.cc:417] errorCode=1 Unrecognized URI or unsupported protocol: www.baidu.com
```
Can you give me some help?

Regards.

**Comment by jie2515** [comment]
Aria2c cann't download BT and MG. How to solve this problem ? Help me.

**Comment by devgianlu** [comment]
The URL should be `http://www.baidu.com`
