### ISSUE TITLE
upadte

### ISSUE THREAD

**Issue by ocean521** [aria2/aria2#1169]
how can i update my aira2 to a new release？coverly install？

**Comment by AiyionPrime** [comment]
Hello @ocean521, I have a hard time understanding what you're aiming for.
What is a 'coverly' installation?
When you're still interested in a solution, please hand over some technical details,
like which OS you are using, which version of aria2c you're currently running, and so on.

Asking a broad question, and not even spelling the project right may not encourage others to help you, as you appear to lack enough interest to even ask properly.

For starters, Linux distributions usually have aria2c in their package repos, so as you update them, you'll get a new version.

**Comment by ocean521** [comment]
My question has been solved,and my english is poor.Sorry.
