### ISSUE TITLE
Ubuntu mingw64 make fail

### ISSUE THREAD

**Issue by AheadSnail** [aria2/aria2#1173]
use github master code  in Ubuntu using mingw64 make fail：

In file included from WinConsoleFile.cc:36:0:
WinConsoleFile.h:48:24: error: expected ‘)’ before ‘stdHandle’
   WinConsoleFile(DWORD stdHandle);
                        ^
WinConsoleFile.h:57:3: error: ‘DWORD’ does not name a type
   DWORD stdHandle_;
   ^
WinConsoleFile.h:61:3: error: ‘WORD’ does not name a type
   WORD fg_, deffg_;
   ^
WinConsoleFile.h:62:3: error: ‘WORD’ does not name a type
   WORD bg_, defbg_;
   ^
WinConsoleFile.h:65:10: error: ‘HANDLE’ does not name a type
   inline HANDLE handle() const { return ::GetStdHandle(stdHandle_); }

**Comment by icyblade** [comment]
I have the same problem. Did you find the solution now?

**Comment by Tu5039** [comment]
Have u resolved? I'm facing this problem now!
