### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kunaltyagi** [aria2/aria2#1207]
I'm getting ```sys/random.h``` not found errors while compiling.

Dockerfile to reproduce is [here](https://gitlab.com/kunaltyagi/dockerfiles/blob/master/aria2.docker). I have successfully used the dockerfile before, so this might be a recent change.

**Comment by Star-Track** [comment]
I also meet the same problem too.

**Comment by brooklyn097** [comment]
I've the same problem.

**Comment by psycholyzern** [comment]
Any solution?

**Comment by kunaltyagi** [comment]
I updated the base image from Ubuntu 16.04 to Ubuntu 18.04 and the ecosystem seems to have changed such that the error has vanished. There's another error (this time from `automake`) but I'm trying to work around it. 

* Good news: The docker image (`kunaltyagi/aria2c`) should work for executable `aria2c` as before
* Unchanged: There is no static build. The image has the same extra baggage (from `cpp-dev`)
