### ISSUE TITLE
failed to find the aria2.conf

### ISSUE THREAD

**Issue by zerobikappa** [aria2/aria2#1216]
(distribution: CentOS7)
I installed aria2 by using command:
sudo yum install aria2

After completed installation, I found no config directory in $HOME, $HOME/.config or /etc.
How could I get a default aria2.conf?

**Comment by tatsuhiro-t** [comment]
You have to create it manually.  https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-conf-path
