### ISSUE TITLE
Error while execute autoreconf -fiv

### ISSUE THREAD

**Issue by Neutron3529** [aria2/aria2#1221]
i use msys2 to compile, but failed at the first step..
$ autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
/usr/bin/autopoint:line 485: /usr/share/gettext/archive.dir.tar.xz: No such file or directory
tar: 它似乎不像是一个 tar 归档文件
tar: gettext-0.18：归档中找不到
tar: 由于前次错误，将以上次的错误状态退出
autopoint: *** infrastructure files for version 0.18 not found; this is autopoint from GNU gettext-tools 0.19.8.1
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1

**Comment by okibar** [comment]
Very late, but:  $ pacman -S gettext-devel
