### ISSUE TITLE
[Feature Request]  Temporary Download Directory

### ISSUE THREAD

**Issue by zero77** [aria2/aria2#1238]
Can you please add the option for a temporary download directory where all downloads are kept wile they are downloading.

Because, it’s easier to manage the downloads that way also, so scripts or other automated tasks can be ran on the finished downloads.
Thanks

**Comment by gitchs** [comment]
Why not try `-d` option.

https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-d
