### ISSUE TITLE
fatal error: sys/random.h

### ISSUE THREAD

**Issue by liyujx** [aria2/aria2#1249]
CC       getrandom_linux.lo
getrandom_linux.c:40:24: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
                        ^
compilation terminated.

**Comment by wolfhong** [comment]
+1

**Comment by rainyl** [comment]
is there any solution??

**Comment by Bob0505** [comment]
+1

**Comment by CodeFarmer1995** [comment]
@wolfhong @rainyl @Bob0505 
We can locate the file [getrandom_linux.c] (https://github.com/aria2/aria2/blob/master/src/getrandom_linux.c) and find this:
`#ifdef HAVE_GETRANDOM
    /* libc already has support */
    read = getrandom(p, buflen, 0);
#else  // HAVE_GETRANDOM
    /* libc has no support, make the syscall ourselves */
    read = syscall(SYS_getrandom, p, buflen, 0);
    /* Some libc impl. might mess -ERESTART up */
    if (read == -EINTR || read == -ERESTART) {
      /* ERESTART, like EINTR, should restart the call, later, so handle both
       * the same way.
       */
      errno = EINTR;
      read = -1;
    }
    /* Some other non-interrupted error happened, put error code into errno and
     * switch read to -1 (return value).
     */
    if (read < -1) {
      errno = -read;
      read = -1;
    }
#endif // HAVE_GETRANDOM
`
The latest libc actually has support for `getrandom`([random.h](https://github.com/lattera/glibc/blob/master/stdlib/sys/random.h)).But my OS(CentOS Linux release 7.5.1804 (Core)  3.10.0-862.11.6.el7.x86_64) dosen't include this header file nither.
But I think it is OK to just comment it, as the comment "libc has no support, make the syscall ourselves" says, we can call the `syscall`.It works for me.

**Comment by ZQQ1024** [comment]
+1, same error on my several Ubuntu 16.04s

**Comment by Lightdisappear** [comment]
Just comment the error line(getrandom_linux.c:40).
It works for me.

**Comment by gzlittle** [comment]
I find random.h at /usr/include/linux/random.h, so I edit src/getrandom_linux.c
`#include <sys/random.h>`
to
`#include </usr/include/linux/random.h>`
