### ISSUE TITLE
 Exception caught while loading DHT routing table from /root/.cache/aria2/dht.dat Exception: [DHTRoutingTableDeserializer.cc:83] errorCode=1 Failed to load DHT routing table from /root/.cache/aria2/dht.dat

### ISSUE THREAD

**Issue by jidesheng6** [aria2/aria2#1253]
Exception caught while loading DHT routing table from /root/.cache/aria2/dht.dat
Exception: [DHTRoutingTableDeserializer.cc:83] errorCode=1 Failed to load DHT routing table from /root/.cache/aria2/dht.dat

**Comment by victorbnl** [comment]
It didn't solve it for me, I use Windows 10

**Comment by milahu** [comment]
> When you see this, trying one more time will solve it.

this is just a workaround
when running aria in an empty sandbox, i get this "error" every time

creating an empty `$HOME/.cache/aria2/dht.dat` file does not work

workaround: create a \*valid\* empty `dht.dat` file in bash:

```sh
if ! [ -e $HOME/.cache/aria2/dht.dat ]; then
  # hide false error: Exception caught while loading DHT routing table
  # https://github.com/aria2/aria2/issues/1253
  # based on aria2/src/DHTRoutingTableDeserializer.cc
  hex=""
  hex+="a1 a2" # 0+2: magic
  hex+="02" # 2+1: format
  hex+="00 00 00" # 3+3
  hex+="00 03" # 6+2: version
  hex+=$(printf "%016x\n" $(date --utc +%s)) # 8+8: time
  hex+="00 00 00 00 00 00 00 00" # 16+8: localnode
  hex+=$(dd if=/dev/random bs=1 count=40 status=none | sha1sum - | cut -c1-40) # 24+20: localnode ID
  hex+="00 00 00 00" # 44+4: reserved
  hex+="00 00 00 00" # 48+4: num_nodes uint32_t
  hex+="00 00 00 00" # 52+4: reserved
  # 56 bytes
  mkdir -p $HOME/.cache/aria2
  echo $hex | xxd -r -p >$HOME/.cache/aria2/dht.dat
fi
```

**Comment by anzz1** [comment]
> When you see this, trying one more time will solve it.

Can confirm, this works! :+1:
I first tried restarting many times, then created empty `dht.dat` file, restarted few times again, deleted the file, some more restarts. Didn't work. Then I read the message, tried one more time, and it worked instantly!

**Steps**
1. Try restarting a few times.
2. Read [this message](https://github.com/aria2/aria2/issues/1253#issuecomment-442282097)
3. Try one more time.
4. It works!

**Comment by Zibri** [comment]
just do this:
`aria2c --dht-entry-point=router.bittorrent.com:6881 --dht-entry-point=dht.transmissionbt.com:6881 --dht-entry-point=router.utorrent.com:6881  [... and the rest of the commend ]
`dht.dat will be created..

**Comment by Cleverscript** [comment]
> > When you see this, trying one more time will solve it.
> 
> this is just a workaround when running aria in an empty sandbox, i get this "error" every time
> 
> creating an empty `$HOME/.cache/aria2/dht.dat` file does not work
> 
> workaround: create a *valid* empty `dht.dat` file in bash:
> 
> ```shell
> if ! [ -e $HOME/.cache/aria2/dht.dat ]; then
>   # hide false error: Exception caught while loading DHT routing table
>   # https://github.com/aria2/aria2/issues/1253
>   # based on aria2/src/DHTRoutingTableDeserializer.cc
>   hex=""
>   hex+="a1 a2" # 0+2: magic
>   hex+="02" # 2+1: format
>   hex+="00 00 00" # 3+3
>   hex+="00 03" # 6+2: version
>   hex+=$(printf "%016x\n" $(date --utc +%s)) # 8+8: time
>   hex+="00 00 00 00 00 00 00 00" # 16+8: localnode
>   hex+=$(dd if=/dev/random bs=1 count=40 status=none | sha1sum - | cut -c1-40) # 24+20: localnode ID
>   hex+="00 00 00 00" # 44+4: reserved
>   hex+="00 00 00 00" # 48+4: num_nodes uint32_t
>   hex+="00 00 00 00" # 52+4: reserved
>   # 56 bytes
>   mkdir -p $HOME/.cache/aria2
>   echo $hex | xxd -r -p >$HOME/.cache/aria2/dht.dat
> fi
> ```

I did this but it didn't solve the problem, the problem repeats every time no matter how many times I try...
