### ISSUE TITLE
磁力链接下载没有速度，添加了BT服务器仍未解决

### ISSUE THREAD

**Issue by cilicilili** [aria2/aria2#1293]

**Comment by underlaw** [comment]
那基本上是种子的原因以及你自己网络的原因了

**Comment by recolic** [comment]
You're more likely to be ignored if you're using chinese while everyone else is in english. It will be horrible if a project is mixed with english, chinese, french, spanish, russian, germany, and many other languages.

**Comment by haodong** [comment]
@recolic True, you're right. Probably because of the popularity of its usage in China, @cilicilili may treat the author as a Chinese. :)

**Comment by lzbgt** [comment]
@recolic it reports no progress when downloading magnet resource, even added BT servers.

**Comment by underlaw** [comment]
如果你设置都正确，去BT大站下载一个热门种子，下载完。你会发现你的DHT.dat这个文件会变大，以后你下载就有速度了
速度与种子热度有关，时间太久无人做种以及你的网络都有影响，影响最大的是你的网络。
