### ISSUE TITLE
How can i get info of finished tasks after I restarted aria2

### ISSUE THREAD

**Issue by hugetiny** [aria2/aria2#1330]
I can get finished tasks when i use aria2.tellStopped.
If I restart aria2 aria2.tellStopped can only return tasks not finished.
How can i get info of finished tasks after I restarted aria2

**Comment by pawamoy** [comment]
I guess you need to set this option to "true":
```
--force-save[=true|false]
              Save download with --save-session option even if the download is completed or removed.
              This option also saves control file in that situations. This may be useful to save BitTorrent
              seeding which is  recognized  as  completed state.  Default: false
```
And when restarting, pass the saved session file as the `--input-file`.

**Comment by hugetiny** [comment]
Thank you for your help

On Jan 14, 2019, at 11:09 PM, Timothée Mazzucotelli <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess you need to set this option to "true":

--force-save[=true|false]
              Save download with --save-session option even if the download is completed or removed.
              This option also saves control file in that situations. This may be useful to save BitTorrent
              seeding which is  recognized  as  completed state.  Default: false


And when restarting, pass the saved session file as the --input-file.
