### ISSUE TITLE
I made a cross-platform aria2 gui client,hope you like it

### ISSUE THREAD

**Issue by hugetiny** [aria2/aria2#1340]
https://github.com/hugetiny/negibox

**Comment by no1xsyzy** [comment]
# Caution: Not satisfying GPLv2 while providing aria2 bundled in the installer. Not satisfying MIT while including [AriaNg](https://github.com/mayswind/AriaNg) in it as electron app.

**Comment by no1xsyzy** [comment]
@hugetiny after illegal movements comes personal attack? It sounds like downgrading.

**Comment by hugetiny** [comment]
无语，中国式开源叫偷，再见

**Comment by hugetiny** [comment]
首先对于原作者，你的项目是基于MIT licenses，不要用MIT然后又觉得别人用你代码不爽，那你干脆闭源比较合适。
其次，奇怪的是中国这个盗版大国里，来我项目狂吠什么你必须怎么怎么做，什么偷的疯狗太多了。

你一定要，装作一副正义凌然光明磊落的样子，那我问你，作为一个中国人，你用的IDE和各种软件有几个是正版？我只想做一款免费的给大家用的，能替代现在越来越不好用的迅雷的下载工具，现在疯狗太多了，我项目跟项目无关的，纯发牢骚的issue我会全部删除。

这里的issue我知道不能删除，这是我的最后回复，如果有喜欢搞事情的人，欢迎来搞，毕竟我以后要面对更多的各种各样的搞事情的人。

**Comment by mayswind** [comment]
@hugetiny 隔了俩月怎么又翻出来了。
第一，再重申一遍，MIT协议不是拿来随便用，而是允许你商用，但是请署名附加LICENSE。不要只将权利不讲义务。
其次，别有事没事出来抹黑国家。
第三，去你妈的。

**Comment by hugetiny** [comment]
mayswind，作为ariang作者，你的确做出了aria2最好的的gui，你说的第一点还算是人话，我回答你，署名当然附加了LICENSE，这个早就有了。
另外中国人说说自己国家的明摆着的缺点就不可以？就是抹黑自己国家？共产党不允许说任何党的不好，你就乖乖站好自干五了？你装孙子装惯了，可能不懂什么叫言论自由，或者喜欢上纲上线提升到抹黑国家来上升自己。
废话不要多，欢迎来搞事情。

**Comment by no1xsyzy** [comment]
@hugetiny 你可能真的不懂什么叫言论自由。
> ## 言论自由 VS 冒犯 / 挑衅言论
> 说完 “煽动暴力 / 煽动仇恨” 言论，顺便说说 “冒犯性 / 挑衅性言论”。
> 还是以美国为例，看看美国的立法如何对待 “冒犯和挑衅言论”。在 1942 年的 “查普林斯基诉新罕布什尔州案”（洋文是 Chaplinsky v. New Hampshire），最高法院裁决：含 “挑衅字眼”（fighting word）的言论是违法的，【不受】言论自由保护。为了防止被滥用，对啥是 “挑衅字眼” 有严格的定义。必须【同时符合】如下三条，才算。
> 1. 通过激怒别人而 “煽动【即刻的】破坏和平行为” 的言论；
> 2. 这些言论 “由普通人通过【常识判断】很可能会引发【暴力】反应”；
> 3. 这些言论还必须是 “【直接针对】听者”。

上来就人身攻击，真当 Github ToS 写出来给你看看就完的？

**Comment by no1xsyzy** [comment]
要我说多少次我提的是建议，我要搞事有一万种方法，但这对人民群众不利，他们将用不上潜在的优秀软件。

我语气冲，我承认，我也没什么好办法。
而如果仅仅因为我的语气冲你要就生气就要涨红了脸，额上的青筋条条绽出，争辩道，“开源不能算偷…… 开源！…… 中国式开源，能算偷么？”，接连便是难懂的话，什么 “盗版大国”，什么 “自干五” 之类，引得众人都哄笑起来：issue 内外充满了快活的空气。
那你不适合当程序员。
