### ISSUE TITLE
How to register onDownloadFinish event via RPC

### ISSUE THREAD

**Issue by ceres-c** [aria2/aria2#1342]
Hello,
I'm trying to control aria2 via xmlrpc (but could move to json-rpc if needed) in python, basing on this implementation https://github.com/zhenlohuang/pyaria2/blob/master/pyaria2.py
I need onDownloadComplete and onDownloadError notifications but I'm not sure if I need to configure some option to get those delivered. According to log notifications aren't fired, but maybe I missed something
Sorry for bothering with noob questions

**Comment by tatsuhiro-t** [comment]
In order to receive notification, JSON-RPC over WebSocket must be used: https://aria2.github.io/manual/en/html/aria2c.html#json-rpc-over-websocket

**Comment by ceres-c** [comment]
Managed to get it to work via https://github.com/armills/jsonrpc-websocket Maybe you could change examples to use this library

If I finish this script I'll publish it on my account and could serve as an example implementation.
Thanks
