### ISSUE TITLE
Control file/session for Torrent downloads gets deleted v1.33.0

### ISSUE THREAD

**Issue by ahmar20** [aria2/aria2#1353]
I am using aria2 in OpenWrt with v1.33.0  and whenever a torrent file gets completed and starts seeding, it gets removed from the `aria2.session.main` file in config directory but it stays in the downloads list as an active task. Now if I stop the aria2 at this time, the control file gets deleted on next start of aria2 resulting in the torrent cannot be seeded anymore because it does not exist and you'll have to use the torrent file (if you have one, or if you can identify it from the aria2 saved torrent files). 

If I pause the seeding torrent and stop aria2 then it doesn't get removed from the session file and also from the downloads list and control file does not get deleted.

Is this expected behavior or a bug?  This seems to be a major bug, because in the case of a torrent download the session file should always contain the torrent data and only remove it if the user requests to do so. Otherwise no one will be able to continue seeding their torrents if the router/network device turns off for any reason or even if the user stops the aria2 program for some reason. Can this be fixed?

**Comment by websaz2000** [comment]
I have the same Problem
