### ISSUE TITLE
Can I use BITFIELD to find out downloaded bytes of a file in a torrent download task?

### ISSUE THREAD

**Issue by lee88688** [aria2/aria2#1416]
As I want to stream a file which may not be completed in a torrent task, is there any way to use BITFIELD to find out downloaded bytes in a file? Using `tellStatus` method can get BITFIELD and FILES from aria2 rpc. But a torrent task may contain multiple files, and how can I know which pieces belong to the file. Since the piece length is constant, there would be a situation which one piece contains two files' bytes. And how can I know it?

**Comment by tatsuhiro-t** [comment]
BitTorrent bitfield is like all files concatenated in a big file.
So I think you need to calculate the offset of each file and locate the first and last pieces.

**Comment by lee88688** [comment]
The file order is same as `getFiles` result?
