### ISSUE TITLE
Not working on RPi4

### ISSUE THREAD

**Issue by amilino** [aria2/aria2#1434]
Hi, I tired to use aria2 on my brand new RPi4 running under Buster but it doesn't work. Not sure what is the problem.

This is what I used for installation:
> sudo apt-get install aria2
> sudo mkdir /home/pi/.aria2
> sudo chmod +x /etc/init.d/aria2
> sudo update-rc.d aria2 defaults

File `/etc/init.d/aria2`:
> #! /bin/sh 
> 
> RETVAL=0 
> case "$1" in 
> start) 
> echo -n "Starting aria2c daemon " 
> umask 0000 
> aria2c --daemon=true --enable-rpc --rpc-listen-all -D --conf-path=/home/pi/.aria2/aria2.conf 
> RETVAL=$? 
> echo 
> ;; 
> stop) 
> echo -n "Shutting down aria2c daemon " 
> /usr/bin/killall aria2c 
> RETVAL=$? 
> echo 
> ;; 
> restart) 
> stop 
> sleep 3 
> start 
> ;; 
> *) 
> echo $"Usage: $0 {start|stop|restart}" 
> RETVAL=1 
> esac 
> exit $RETVAL

File `/home/pi/.aria2/aria2.conf`:
> ##
> dir=/home/pi/Downloads
> file-allocation=falloc
> continue=true
> ###
> input-file=/home/pi/Downloads/aria2_input.txt
> save-session=/home/pi/Downloads/aria2_input.txt
> save-session-interval=30
> ###
> #log=/home/pi/Downloads/aria2.log
> #console-log-level=warn
> #log-level=notice
> ###
> max-connection-per-server=4
> max-concurrent-downloads=1
> max-overall-download-limit=600K
> disable-ipv6=true
> ###
> split=10
> stream-piece-selector=geom
> enable-http-pipelining=true
> ###
> enable-rpc=true
> rpc-allow-origin-all=true
> rpc-listen-all=true
> rpc-listen-port=20542
> rpc-secret=***my secret***
> ###
> #disk-cache=25M
> timeout=600
> max-tries=5
> retry-wait=60
> ###
> check-integrity=true
> follow-torrent=mem
> follow-metalink=mem
> enable-dht6=false
> seed-time=0
> #bt-seed-unverified=true
> bt-save-metadata=true
> bt-remove-unselected-file=true
> #pause-metadata=true

I get it working for some seconds:
> ● aria2.service - LSB: aria2c RPC init script.
>    Loaded: loaded (/etc/init.d/aria2; generated)
>    Active: active (running) since Fri 2019-07-12 20:47:39 CEST; 1s ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 8878 ExecStart=/etc/init.d/aria2 start (code=exited, status=0/SUCCESS)
>     Tasks: 1 (limit: 4915)
>    Memory: 11.7M
>    CGroup: /system.slice/aria2.service
>            └─8880 aria2c --daemon=true --enable-rpc --rpc-listen-all -D --conf-path=/home/pi/.aria2/aria2.conf
> 
> Jul 12 20:47:39 2raspberrypi systemd[1]: Starting LSB: aria2c RPC init script....
> Jul 12 20:47:39 2raspberrypi aria2[8878]: Starting aria2c daemon
> Jul 12 20:47:39 2raspberrypi systemd[1]: Started LSB: aria2c RPC init script..

but then this:
> ● aria2.service - LSB: aria2c RPC init script.
>    Loaded: loaded (/etc/init.d/aria2; generated)
>    Active: inactive (dead) since Fri 2019-07-12 20:47:49 CEST; 22s ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 8878 ExecStart=/etc/init.d/aria2 start (code=exited, status=0/SUCCESS)
>   Process: 8951 ExecStop=/etc/init.d/aria2 stop (code=exited, status=0/SUCCESS)
>     Tasks: 0 (limit: 4915)
>    Memory: 8.5M
>    CGroup: /system.slice/aria2.service
> 
> Jul 12 20:47:39 2raspberrypi systemd[1]: Starting LSB: aria2c RPC init script....
> Jul 12 20:47:39 2raspberrypi aria2[8878]: Starting aria2c daemon
> Jul 12 20:47:39 2raspberrypi systemd[1]: Started LSB: aria2c RPC init script..
> Jul 12 20:47:49 2raspberrypi systemd[1]: Stopping LSB: aria2c RPC init script....
> Jul 12 20:47:49 2raspberrypi aria2[8951]: Shutting down aria2c daemon
> Jul 12 20:47:49 2raspberrypi systemd[1]: aria2.service: Succeeded.
> Jul 12 20:47:49 2raspberrypi systemd[1]: Stopped LSB: aria2c RPC init script..

**Comment by amilino** [comment]
Exactly the same setup on RPi 3 is working fine. I checked all file permissions.

And this is the log file taken from RPi 4:

> 2019-07-12 20:42:15.083336 [INFO] [Context.cc:179] <<--- --- --- ---
> 2019-07-12 20:42:15.083628 [INFO] [Context.cc:180]   --- --- --- ---
> 2019-07-12 20:42:15.083646 [INFO] [Context.cc:181]   --- --- --- --->>
> 2019-07-12 20:42:15.083687 [INFO] [Context.cc:182] aria2 1.34.0
> 2019-07-12 20:42:15.083882 [INFO] [Context.cc:183] gcc 8.2.0
>   built by  arm-unknown-linux-gnueabihf
>   on        Feb 28 2019 15:36:13
> 2019-07-12 20:42:15.083917 [INFO] [Context.cc:184] Linux 4.19.57-v7l+ #1244 SMP Thu Jul 4 18:48:07 BST 2019 armv7l
> 2019-07-12 20:42:15.083939 [INFO] [Context.cc:185] zlib/1.2.11 libxml2/2.9.4 sqlite3/3.27.2 GnuTLS/3.6.6 nettle GMP/6.1.2 c-ares/1.14.0 libssh2/1.8.0
> 2019-07-12 20:42:15.083990 [INFO] [Context.cc:186] Logging started.
> 2019-07-12 20:42:15.084031 [DEBUG] [Context.cc:216] Not setting rlimit NO_FILE: 1024 >= 1024
> 2019-07-12 20:42:15.084053 [INFO] [SocketCore.cc:1653] Checking configured addresses
> 2019-07-12 20:42:15.084284 [INFO] [SocketCore.cc:1704] Not considered: 127.0.0.1
> 2019-07-12 20:42:15.084314 [INFO] [SocketCore.cc:1701] Found configured address: 192.168.188.202
> 2019-07-12 20:42:15.084330 [INFO] [SocketCore.cc:1704] Not considered: ::1
> 2019-07-12 20:42:15.084434 [INFO] [SocketCore.cc:1704] Not considered: fe80::e699:3910:3aaa:524b%wlan0
> 2019-07-12 20:42:15.084458 [INFO] [SocketCore.cc:1709] IPv4 configured=1, IPv6 configured=0
> 2019-07-12 20:42:15.085438 [INFO] [HttpListenCommand.cc:106] CUID#8 - Using port 20542 for accepting new connections
> 2019-07-12 20:42:15.085521 [NOTICE] [HttpListenCommand.cc:108] IPv4 RPC: listening on TCP port 20542
> 2019-07-12 20:42:15.116916 [DEBUG] [Platform.cc:86] GnuTLS: <3> ASSERT: ../../../lib/x509/common.c[_gnutls_x509_get_raw_field2]:1570
> 2019-07-12 20:42:15.116997 [DEBUG] [Platform.cc:86] GnuTLS: <3> ASSERT: ../../../lib/x509/x509.c[gnutls_x509_crt_get_subject_unique_id]:3897
> 2019-07-12 20:42:15.117024 [DEBUG] [Platform.cc:86] GnuTLS: <3> ASSERT: ../../../lib/x509/x509.c[gnutls_x509_crt_get_issuer_unique_id]:3947
> 2019-07-12 20:42:15.119706 [INFO] [LibgnutlsTLSContext.cc:158] 128 certificate(s) were imported.
> 2019-07-12 20:42:26.704876 [NOTICE] [DownloadEngine.cc:265] Emergency shutdown sequence commencing...
> 2019-07-12 20:42:26.711118 [NOTICE] [MultiUrlRequestInfo.cc:342] Serialized session to '/home/pi/Downloads/aria2_input.txt' successfully.

**Comment by Plausible0Bug** [comment]
GnuTLS on Raspberry Pi 4 is causing trouble, try compile with OpenSSL instead?

Or download their latest build chain and cross compile again.

**Comment by amilino** [comment]
It is working with latest build.
