### ISSUE TITLE
Details on Server Performance Profile management

### ISSUE THREAD

**Issue by starless72** [aria2/aria2#1439]
Dear Tatsuhiro,
would it be possible to have some more information on how the Server Performance Profile is managed? Some things are not clear to me from the documentation.

* The server stat file is only loaded (if available) at startup, and saved at shutdown. It is *never* used during operation, when all server stats are only kept in memory. Is this correct?

* When is the server choice performed? Only at the start of a new download (i.e. when a download is passed from the queue to the active downloads), or also during the download process?

* After "**server-stat-timeout**" the profile of a server is discarded if there was no more contact with this server. But what happens if we are sending requests to a server which is not responding? Is this counted as "contacted", so that the timeout is moved ahead in time, or not?

* If a server which had great performance for hours suddenly provides very low download speed, is it immediately marked as "bad" and abandoned, or is there some sort of inertia before completely switching over to other servers? Can it happen that downloads from the failing server are still attempted for durations of 25-30 minutes?

* How does the **--uri-selector=adaptive** option affect the situations described above? I do not completely understand its description... If e.g. we only have two servers available, and one is suddenly failing, would this mean that the failing server is continously choosen anyway, slowing down downloads overall?

Thank you very much in advance!
Marco

**Comment by tatsuhiro-t** [comment]
> The server stat file is only loaded (if available) at startup, and saved at shutdown. It is never used during operation, when all server stats are only kept in memory. Is this correct?

Correct.

> When is the server choice performed? Only at the start of a new download (i.e. when a download is passed from the queue to the active downloads), or also during the download process?

It is performed when selecting URI.  It includes retrying request due to connection loss.

> After "server-stat-timeout" the profile of a server is discarded if there was no more contact with this server. But what happens if we are sending requests to a server which is not responding? Is this counted as "contacted", so that the timeout is moved ahead in time, or not?

Timestamp is updated when download is stopped regardless of success/failure, so I think timeout is extended.

> If a server which had great performance for hours suddenly provides very low download speed, is it immediately marked as "bad" and abandoned, or is there some sort of inertia before completely switching over to other servers? Can it happen that downloads from the failing server are still attempted for durations of 25-30 minutes?

It looks like it suddenly goes to error state.

> How does the --uri-selector=adaptive option affect the situations described above? I do not completely understand its description... If e.g. we only have two servers available, and one is suddenly failing, would this mean that the failing server is continously choosen anyway, slowing down downloads overall?

Adaptive server tries to test not best URI at most 8 times at the moment with geometric backoff using server stat last-update value.  I think it may be selected several times, but is going to be faded out.
