### ISSUE TITLE
aria2 destroyed parts of videos with multiple simultaneous connections

### ISSUE THREAD

**Issue by princeofguilty** [aria2/aria2#1441]
my command was
aria2c -x 16 -s 16 url
and also i tried to use flareget and uget with 16 multiple simultaneous connections to download videos from same link in which i know the video works good on online streaming and when downloaded with idm on wine
all of them gave same result, the video is about 2 hours, nearly every 20 min there's a part of the video which is corrupted and have to skip like 30 seconds or a minute so the video continues playing again. iam sure the video from this url is working and uncorrupted

**Comment by Plausible0Bug** [comment]
link, please?

**Comment by princeofguilty** [comment]
that was month and a half ago so i don't remember which link was that but iam sure that the link of the video was okay and  when aria2 caused the problem i mentioned i streamed the video and it was okay

**Comment by Jimmy-Z** [comment]
I've download videos using multiple connections (and with even hundreds of connections) numerous times, none of them failed. Maybe - I said maybe - you should make sure the download is complete.
