### ISSUE TITLE
Auto file renaming for --input-file

### ISSUE THREAD

**Issue by Nisto** [aria2/aria2#145]
The option --auto-file-renaming doesn't seem to work with files downloaded via --input-file, can you fix this? I'm on Windows XP if that changes anything.

Here is a log sample:

```
[DL:10KiB UL:0B][#f8cb39 0B/0B][#884696 0B/14MiB(0%)]
11/03 21:43:16 [ERROR] CUID#6 - Download aborted. URI=xxxxx
Exception: [AbstractCommand.cc:363] errorCode=11 URI=xxxxx
  -> [HttpResponseCommand.cc:264] errorCode=11 File C:/videoplayback is being downloaded by other command.

11/03 21:43:16 [NOTICE] Download GID#f8cb39db6d74cd45 not complete: C:/videoplayback
[#884696 13MiB/14MiB(98%) CN:2 DL:1.7MiB]
11/03 21:43:23 [NOTICE] Download complete: C:/videoplayback

Download Results:
gid   |stat|avg speed  |  %|path/URI
======+====+===========+===+===================================================
f8cb39|ERR |       0B/s|  -|C:/videoplayback
884696|OK  |   1.6MiB/s|100|C:/videoplayback

Status Legend:
(OK):download completed.(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```

Thanks.

**Comment by scythargon** [comment]
@tatsuhiro-t 
```
http://r6---sn-5go7ln7l.googlevideo.com/videoplayback?.....
    out=file1
http://r6---sn-5go7ln7l.googlevideo.com/videoplayback?.....
    out=file2
```
how exactly to do that?
out=file2 should be on the next like? cant get it to work

**Comment by tomasz1986** [comment]
> how exactly to do that?
> out=file2 should be on the next line? cant get it to work

I hope no-one will mind my reply to this comment, but this closed issue is the first result on Google when searching for renaming files downloaded with `--input-file`. This info is also not present in the documentation, as far as I can see.

Basically, to make this work there needs to be either a space or a tab before `out=file`, which itself should be placed in the line right after the URL, e.g.

```
http://example.com
 out=file1
```

If there is no space or tab, then the line is treated as an URL.
