### ISSUE TITLE
can we download via VPN?

### ISSUE THREAD

**Issue by akinkoker** [aria2/aria2#1457]
hi.
I want to download via VPN.
How can I do that? Can you show me the way?

**Comment by Jimmy-Z** [comment]
That should be pretty straight forward: start the VPN, run aria2, profit?

**Comment by akinkoker** [comment]
hi, I used proxy.

`aria2c.exe 
	--all-proxy="https://xxxx.com:6060" 
	--all-proxy-passwd="_PASS_" 
	--all-proxy-user="_USER_" `
