### ISSUE TITLE
Lazy load for source

### ISSUE THREAD

**Issue by 1271** [aria2/aria2#1462]
Is it possible to make lazy url loading from a file? (option -i)
Now aria2 requires a lot of resources if there are a lot of links in the file.
Thank!

**Comment by Jimmy-Z** [comment]
I think you can break the input files to smaller ones and write a script to call on them sequentially. It's not ideal but I'm afraid you're asking a feature too specific to interest anybody to work on it.

**Comment by Jimmy-Z** [comment]
My bad, it's actually implemented already:
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-deferred-input

**Comment by 1271** [comment]
Oh. Thanks! ^_^
Love this app!
