### ISSUE TITLE
Please consider making a new release

### ISSUE THREAD

**Issue by 49616e** [aria2/aria2#1464]
With more websites starting to adopt TLSv1.3, I see the `[WARN] aria2c had to connect to the other side using an unknown TLS protocol. The integrity and confidentiality of the connection might be compromised.` error quite a lot, because aria2 v1.34.0 doesn't know what TLSv1.3 is. Since commit 52da4e40ea22d1db13c1eadeac5baed4e8fd5dd8 fixes the issue, and it's been more than a year since the last release, please consider making a new release soon.

**Comment by truebit** [comment]
I got the same error here when using let's encryt SSL certificates.

More details on this issue could be found from here: "https://unix.stackexchange.com/a/523465"

**Comment by 49616e** [comment]
> I got the same error here when using let's encryt SSL certificates.
> 
> More details on this issue could be found from here: "https://unix.stackexchange.com/a/523465"

I was proposing a solution, not reporting a problem. It has already been resolved by 52da4e40ea22d1db13c1eadeac5baed4e8fd5dd8 , but if a new release is not made, most package maintainers won't package it. I think making a new release to address this issue is better than telling everyone to compile master from source.

**Comment by 49616e** [comment]
> Arch user here,

You can just use https://aur.archlinux.org/packages/aria2-git/ instead I think?

**Comment by tatsuhiro-t** [comment]
#1468

**Comment by 49616e** [comment]
Thank you, closing for now.
