### ISSUE TITLE
RPC: any built-in protection against brute-force attacks?

### ISSUE THREAD

**Issue by carlosfilhoadm** [aria2/aria2#1465]
Hi,

Does the RPC interface (I use it with '--rpc-secret=(...)' option) have any built-in protection mechanism against brute-force attacks?

I didn't find any detailed information about it (I also didn't find any information at all about using something like fail2ban to do the job).

Thanks.

**Comment by carlosfilhoadm** [comment]
I'd like to expose the RPC interface to the internet in order to access it remotely (I'd also use Let's Encrypt to secure it), so some protection against brute-force attacks would be nice.

**Comment by sonnyp** [comment]
Most likely you want to setup an http reverse proxy in front of aria2 and use something like https://www.nginx.com/blog/rate-limiting-nginx/

**Comment by carlosfilhoadm** [comment]
I actually already use apache as reverse proxy for aria2, but I'm just taking advantage of a pre-existing infrastructure (just installed aria2 on my webserver).

I just wonder if it'd be safe to expose the rpc interface directly to the internet (for remote access) without needing to install and configure a reverse proxy for it.

Thanks.

Oh, by the way, thanks for your work on Tangram. It's a nice app.

**Comment by sonnyp** [comment]
I checked the documentation, I found this

> The secret token validation in aria2 is designed to take at least a certain amount of time to mitigate brute-force/dictionary attacks against the RPC interface. 

https://aria2.github.io/manual/en/html/aria2c.html?highlight=force%20save#rpc-authorization-secret-token

> Oh, by the way, thanks for your work on Tangram. It's a nice app.

Thanks! Something that might be of interest to you then https://github.com/sonnyp/Tangram/pull/54#issuecomment-531802487 feedback welcome!

**Comment by carlosfilhoadm** [comment]
That's useful. Thanks.

-----

A standalone aria2 frontend is a very good idea, I'd use it gladly.
Would you please consider adding RPC capabilities to it (in order to manage remote aria2 instances)?
