### ISSUE TITLE
请问 aria2 的下个更新能增加对ed2k的支持吗?

### ISSUE THREAD

**Issue by currencyporter** [aria2/aria2#1472]

**Comment by no1xsyzy** [comment]
1. 用英文
2. 不要寒暄
3. 不要在一个 issue 里提两个问题

需要 ed2k 请自写，[主要维护作者之一标志对此不感兴趣并且工作量很大](https://github.com/aria2/aria2/issues/986#issuecomment-325183535)。

如果有控制文件 *.aria2 只要建立完全一致的下载任务会自动继续下载，如果没有会重新下载
如果是希望自动中断后继续则请使用 `input-file` 和 `save-session` 两个选项。

我会 unsubscribe，也不常看 aria2 的 issue，更多问题请用英文重新发 issue。

**Comment by currencyporter** [comment]
> 
> 
>     1. 用英文
> 
>     2. 不要寒暄
> 
>     3. 不要在一个 issue 里提两个问题
> 
> 
> 需要 ed2k 请自写，[主要维护作者之一标志对此不感兴趣并且工作量很大](https://github.com/aria2/aria2/issues/986#issuecomment-325183535)。
> 
> 如果有控制文件 *.aria2 只要建立完全一致的下载任务会自动继续下载，如果没有会重新下载
> 如果是希望自动中断后继续则请使用 `input-file` 和 `save-session` 两个选项。
> 
> 我会 unsubscribe，也不常看 aria2 的 issue，更多问题请用英文重新发 issue。

我不懂c程序,怎么写才能支持ed2k ?谢谢

**Comment by zealotCE** [comment]
> > ```
> > 1. 用英文
> > 
> > 2. 不要寒暄
> > 
> > 3. 不要在一个 issue 里提两个问题
> > ```
> > 
> > 
> > 需要 ed2k 请自写，[主要维护作者之一标志对此不感兴趣并且工作量很大](https://github.com/aria2/aria2/issues/986#issuecomment-325183535)。
> > 如果有控制文件 *.aria2 只要建立完全一致的下载任务会自动继续下载，如果没有会重新下载
> > 如果是希望自动中断后继续则请使用 `input-file` 和 `save-session` 两个选项。
> > 我会 unsubscribe，也不常看 aria2 的 issue，更多问题请用英文重新发 issue。
> 
> 我不懂c程序,怎么写才能支持ed2k ?谢谢

这个目前无解，建议放弃使用aria2下载ed2k。我翻了很多记录所以了解到主要作者对ed2k不感兴趣。所以建议放弃。

另外，如果没有问题就尽快关闭 issue 吧。（可以的话，提问题最好还是英文，即便是 google translate）
