### ISSUE TITLE
Openwrt can't connect RPC

### ISSUE THREAD

**Issue by thesuperfatcat** [aria2/aria2#1485]
Hello, i using openwrt in aria2. My English is not good, I try to speak simple words as possible, I'm sorry
Installed packages in my openwrt router : 
aria2 ver/1.33.0-1
luci-app-aria2 ver/1.0.1-2
ariang ver/2018-02-21-f71a67cb-1

etc config : 

> config aria2 'main'
	option config_dir '/var/etc/aria2'
	option bt_enable_lpd 'true'
	option enable_dht 'true'
	option follow_torrent 'true'
	option file_allocation 'none'
	option save_session_interval '30'
	list header ''
	option enable_log 'false'
	option rpc_listen_port '9092'
	option dir '/mnt/usb3/downloads'
	option disk_cache '20M'
	option rpc_user 'mypass'
	option rpc_passwd 'mypass'
	list extra_settings 'enable-rpc=true'
	list extra_settings 'rpc-listen-all=true'
	list extra_settings 'rpc-listen-port=9092'
	option enabled '1' 

Login screen as 192.168.1.1:9092 port in localhost. Blank screen comes when I'm logged in.
Web interface works on port 80. And am change all port settings over openwrt. I'm setting up rpc. But doesn't ask for password in web interface, What is the source of this problem? Thank you for your helps

**Comment by Jimmy-Z** [comment]
I'm not familiar with neither luci-app-aria2 nor ariang, but rpc user/password was deprecated ages ago, try using rpc-secret and specify that in the rpc uri.

reference:
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-secret
https://aria2.github.io/manual/en/html/aria2c.html#rpc-auth

**Comment by thesuperfatcat** [comment]
> 
> 
> I'm not familiar with neither luci-app-aria2 nor ariang, but rpc user/password was deprecated ages ago, try using rpc-secret and specify that in the rpc uri.
> 
> reference:
> https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-secret
> https://aria2.github.io/manual/en/html/aria2c.html#rpc-auth

**Comment by thesuperfatcat** [comment]
> 
> 
> I'm not familiar with neither luci-app-aria2 nor ariang, but rpc user/password was deprecated ages ago, try using rpc-secret and specify that in the rpc uri.
> 
> reference:
> https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-secret
> https://aria2.github.io/manual/en/html/aria2c.html#rpc-auth

thank you so much. I will try
