### ISSUE TITLE
RPC interface fails to bind

### ISSUE THREAD

**Issue by CircleFaith** [aria2/aria2#1512]
2019-11-21 17:22:04.191508 [ERROR] [HttpListenCommand.cc:112] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: An attempt was made to access a socket in a way forbidden by its access permissions.

2019-11-21 17:22:04.191508 [DEBUG] [SelectEventPoll.cc:311] Socket -1 is not found in SocketEntries.
2019-11-21 17:22:04.191508 [ERROR] [HttpListenCommand.cc:112] IPv6 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: An attempt was made to access a socket in a way forbidden by its access permissions.

2019-11-21 17:22:04.191508 [DEBUG] [SelectEventPoll.cc:311] Socket -1 is not found in SocketEntries.
2019-11-21 17:22:04.191508 [ERROR] [MultiUrlRequestInfo.cc:297] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.

**Comment by CircleFaith** [comment]
It seems like the aria2 default 6800 port used by the other process,but i checked the process,no process used the 6800 port

**Comment by CircleFaith** [comment]
Hope to get a reply

**Comment by shaojiasai-Chinese** [comment]
hi,I encounter the same  pronlem ,how did you solve it?

**Comment by CircleFaith** [comment]
> hi,I encounter the same pronlem ,how did you solve it?

update the configuration file,change the default 6800 port

**Comment by ileodo** [comment]
This happens to me as well, changing port doesn't help.

```
2020-03-23 10:59:05.828524 [ERROR] [HttpListenCommand.cc:112] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: Address already in use
2020-03-23 10:59:05.829310 [ERROR] [MultiUrlRequestInfo.cc:297] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.
```

and aria2c is the only process listening to port 6800.

However, aria2 works fine even with this error. any idea?

**Comment by SymmetricISupreme** [comment]
i got the same problem
<img width="776" alt="image" src="https://user-images.githubusercontent.com/44258489/80355931-4e242c00-88ab-11ea-9293-54e86bb0127a.png">
but aria2 works pretty well......

**Comment by SharonSHH** [comment]
sudo kill -9 $(pidof aria2c)

**Comment by itchin** [comment]
do not use ipv6.

aria2c --conf-path=/usr/local/aria2/aria2.conf --disable-ipv6

**Comment by HTLXMC** [comment]
So,how to solve this problem?

**Comment by wyptaotao** [comment]
This problem occurs to me today..... It worked fine yesterday.

**Comment by cloudwindy** [comment]
> This problem occurs to me today..... It worked fine yesterday.

Just disable ipv6 and it'll be okay

**Comment by FiberStudio** [comment]
In my case, this problem is due to windows update.
>The reason is most likely due to a Windows Update that restricted access to certain ports on Windows machines. The details are [here](https://superuser.com/questions/1486417/unable-to-start-kestrel-getting-an-attempt-was-made-to-access-a-socket-in-a-way).
 I jst fixed by changing ports.

**Comment by RedSnt** [comment]
Turns out that WinNAT was the problem on my computer. Doing a simple ```net stop winnat``` and then ```net start winnat``` cleared the almost 2000 ports that WinNAT had reserved for some reason. Probably because I'm playing around with WSL or Docker a lot.  
Command to see what ports are reserved is ```netsh interface ipv4 show excludedportrange protocol=tcp```

**Comment by chinese-kongfu** [comment]
you can stop hyper-v port,it's powerful.
powershell: net stop winnat
