### ISSUE TITLE
--show-files gives Unrecognized URI or unsupported protocol in .torrent files

### ISSUE THREAD

**Issue by mattneal7** [aria2/aria2#1520]
Trying to get a list of files from `.torrent` files yields error: 
```bash
[ERROR] Unrecognized URI or unsupported protocol:
```
---

**Steps to reproduce**:
```bash
wget http://releases.ubuntu.com/18.04/ubuntu-18.04.3-desktop-amd64.iso.torrent
aria2c -i ubuntu-18.04.3-desktop-amd64.iso.torrent --show-files
```

**Output:**
```
(trimmed output)
.
.
12/09 09:29:26 [ERROR] Unrecognized URI or unsupported protocol: �0�����Ĩ�J9�~��Nr

⒋�ŨL�=R����Zü��������Unrecognized URI or unsupported protocol: ���i+ۙ�o�GKb(=q�����lfu�n�

12/09 09:29:26 [ERROR] Unrecognized URI or unsupported protocol: BUl��x����q!�ڞ�Y�Y�� ��.������[���E_�ׂ�/,�n��&&�:�H_�m���f�|���

hu:_@lU?���eeERROR] Unrecognized URI or unsupported protocol: I�Pd!���h-�jR*c,&�;���K�����jR*c,&�;���K��������:�
No files to download.
```

**Comment by mattneal7** [comment]
@tatsuhiro-t anyways to fix this? I love using `aria2`, but this is the only blocker that I am facing.
I want to use this to select certain files from the torrent.

Ref: https://github.com/aria2/aria2/issues/843#issuecomment-275913139

**Comment by VaslD** [comment]
`-i` (`--input-file`) loads saved or exported session given as parameter. A session file is just plaintext of URLs. If you supply a `.torrent` file as `--input` parameter, Aria2 treats it as plaintext.

You should give `.torrent` to Aria2 as *command-line input*, like how you supply input to `wget`. Try:

```
aria2c.exe ubuntu-18.04.3-desktop-amd64.iso.torrent --show-files
```

The example is for Windows.

**Comment by mattneal7** [comment]
@VaslD thanks. That solves it :confetti_ball:
