### ISSUE TITLE
aria2 only downloads with sudo

### ISSUE THREAD

**Issue by Max0412** [aria2/aria2#1533]
i´ve installed aria2 via apt-get install aria2 on a raspberry pi.
after that i´ve placed a aria2.conf in .aria2 in my homefolder.
`dir=/mnt/ExSSD1
file-allocation=falloc
continue
log-level=error
max-connection-per-server=4
summary-interval=120
daemon=true
enable-rpc=true
rpc-listen-port=6800
rpc-listen-all=true
max-concurrent-downloads=2
disable-ipv6=true
disk-cache=25M
timeout=600
retry-wait=30
max-tries=50`

downloading with aria2c <file> does nothing, no error message, nothing.
adding sudo infront of it starts the download process.

**Comment by VaslD** [comment]
Try using something other than `falloc` (or not use allocation at all), is the issue still present?

On Windows `falloc` only works when Aria2 is run using highest privilege so maybe it’s the same on some Linux as well.

Also verify that you (your account, without `sudo`) do have write permission on whatever disk you mounted for Aria2. The easiest way to check is `cd` into the download folder and `touch` some random name in your favorite terminal.

**Comment by Max0412** [comment]
Hey, thanks for the answer and tips.
i´ve completely emptied the config file besides the dir=.. and also do have checked the folder permission, but the folder ExSSD1 already has 777(for testing purpose) so everyone should be able to write there. 
Sadly clearing out the config and deleting the file allocation didn`t help.

**Comment by no1xsyzy** [comment]
Have you tried `file-allocation=none`?

I suppose @VasID meant: other than file system permission, there is also mount permission. The best way to check is use `touch` to create file.

What's more, was there `*_proxy` settings that would prevent download? `sudo` doesn't keep that. Try just reset every environment and try again.

**Comment by Max0412** [comment]
Hey, thank you for answering. 

i´ve tried to `touch` and it works fine, even writing in that file etc, but didn´t mention it here, sorry.

`file-allocation=none` didn´t work out either. 

there is no proxy configed in any way, it´s a fresh new raspbian image besides samba and minidlna, and router is also on standard config.

a new `env` does nothing too, no error, nothing.

**Comment by no1xsyzy** [comment]
I'm sorry but I have no idea other than debug it directly, which I am not good at.
What's more, I failed to reproduce with QEMU with `2019-09-26-raspbian-buster` and `kernel-qemu-4.19.50-buster`.

**Comment by Max0412** [comment]
ok i´ve reinstalled it again, deleted the config and "redid" everything and now i know that it should be a problem with the mnt/ExHDD .. thanks alot for all the help!
