### ISSUE TITLE
OSX + Homebrew compilation caveat

### ISSUE THREAD

**Issue by benwaffle** [aria2/aria2#156]
autoreconf had a problem where it couldn't find autopoint even though gettext was installed. I think that hombrew, a package manager on OSX, doesn't symlink autopoint into /usr/local/bin by default. Can someone confirm this? To solve, i had to run `brew link --force gettext`

(using OSX 10.9)

**Comment by chapinb** [comment]
Thanks @nmaier solution # 2 helped perfectly
