### ISSUE TITLE
下载100%后任务依然停留在“正在下载”中

### ISSUE THREAD

**Issue by curryhendry** [aria2/aria2#1561]
你好，如题。
下载100%后任务依然停留在“正在下载”中。需要手动删除后才可以进行后面（超出最大数）的任务。

**Comment by Jimmy-Z** [comment]
torrent?

**Comment by curryhendry** [comment]
你好，是的。


谢谢

**Comment by Jimmy-Z** [comment]
朋友, 听说过做种吗?

**Comment by curryhendry** [comment]
你好，感谢回复。明白什么意思了。

建议改在已完成里吧，其他平台做种也不是在“正在下载”中


谢谢

**Comment by Jimmy-Z** [comment]
建议close issue.
建议另开feature request, 不过我猜测优先级会很低.
建议用英文.

**Comment by curryhendry** [comment]
好的，谢谢。

**Comment by Jimmy-Z** [comment]
然而你并没有close...

**Comment by code2828** [comment]
Please use English... 虽然我是中国人能看懂但毕竟github是外国网站，大家都说英文。

**Comment by VVVVictorJ** [comment]
@curryhendry 你应该关掉这个issue
