### ISSUE TITLE
download from txt file

### ISSUE THREAD

**Issue by X-C0DE** [aria2/aria2#1584]
is there any way I can organize or set the output file from a URL's file? it happens that I have a file of links and the URLs of the fragments sometimes have the same names and usually the difference is in a part of the link before the file name

**Comment by aliemjay** [comment]
You can specify the file name and many other options for each URL separately in the input file.
Please refer to https://aria2.github.io/manual/en/html/aria2c.html#input-file for documentation. The first example addresses this specific case.

**Comment by X-C0DE** [comment]
thanks
