### ISSUE TITLE
Always slows down when reaching the end.

### ISSUE THREAD

**Issue by code2828** [aria2/aria2#1593]
This problem exists on both MacOS and FreeBSD 13.0. For example, I have this output once: 

 > [128KiB/467KiB DL:12KiB]

When it has almost finished:

> [461KiB/467KiB DL:0.8KiB]

I don't know what is the problem with it, it just starts to slow down then it is about 95%, and when it is 99%, the speed will be about only 1/20 ~ 1/10 of the average speed. I am very confused.

Another example:

> [3.5GB/7.8GB DL:8.9MiB]
> [7.7GB/7.8GB DL:334KiB]
> [7.8GB/7.8GB DL:29KiB]

**Comment by edrozenberg** [comment]
If aria2 is using many separate connections, it could be that as it reaches the end most of the connections have completed their work, and a few "stragglers" are still downloading the little that remains.

For ex. say aria2 is using 20 connections. Toward the end say 19 connections have finished their work, and 1 connection still has a bit to go, and for some reason that 1 connection is downloading slowly. The work isn't done until that last slow connection is finished.

**Comment by code2828** [comment]
Thank you. That may be a reason, because I always use >=10 connections.

**Comment by code2828** [comment]
I see. I tried to download a file with 16 connections, and then it almost ends it gives the following output:
> [#91f82d 16MiB/16MiB(99%) CN:1 DL:100KiB]
When I am downloading, it is 1MiB/s(16 connections).
