### ISSUE TITLE
[Q/FR] How do I get the completed length from the control file?

### ISSUE THREAD

**Issue by NightMachinary** [aria2/aria2#1621]
I am writing a shell function to download videos using `youtube-dl` and `aria2c`, and I need to be able to know how much of the file has been downloaded to start `mpv`. Using `du` doesn't  work because of pre-allocation. I tried using an aria2 server and rpc, but that gets very complicated for my usecase, especially since I have to start `aria2c` from `youtube-dl`. So is there a way to get the downloaded length from the file itself or the control file?

**Comment by NightMachinary** [comment]
It seems this information is not stored in the control file at all ... I can extract `total length`, but it is just the total length, not total downloaded length.

```
#!/usr/bin/env python3
import os, sys
file_name = sys.argv[1]
from IPython import embed

with open(file_name, "rb") as f:
    # https://aria2.github.io/manual/en/html/technical-notes.html
    f.seek(10+hash_length+4)
    total_length = f.read(8)
    # embed()
    print(int.from_bytes(total_length, 'big'))
```

**Comment by shaifulroni** [comment]
You can try to calculate the information from the **bitfield** and **piece length**. This does not include the in-flight chunks. You can calculate in inflight download length from in-flight chunks information. 

Roughly the calculation should be - (Number of set bit in the bitfield * piece length) + for each in-flight piece ( number of set bit in piece bitfield * 16K)
