### ISSUE TITLE
The download request Range is too large resulting in 403

### ISSUE THREAD

**Issue by Erope** [aria2/aria2#1627]
First of all, please forgive me, my English is not very good. When I downloaded a file of website, I found that they have restrictions on the Range request header. If the requested Range is too large, it will directly throw a 403 error, and in order to reduce the number of connections when Aria2 is downloaded, the default piece is very large. This will directly lead to 403, is there any good way?

**Comment by aliemjay** [comment]
Can you please share the URL to investigate it further myself? I am very interested because I worked recently on range requests in this codebase.

It seems to be a server-side problem. Its support for range requests may be broken, so one can assume that it doesn't support resuming downloads. Otherwise, you can send custom http requests via `curl` with particular ranges and then merge the responses to create the whole file.

**Comment by Erope** [comment]
> Can you please share the URL to investigate it further myself? I am very interested because I worked recently on range requests in this codebase.
> 
> It seems to be a server-side problem. Its support for range requests may be broken, so one can assume that it doesn't support resuming downloads. Otherwise, you can send custom http requests via with particular ranges and then merge the responses to create the whole file.`curl`

Sharing is no problem, but the link is only valid for 8 hours, this is a dynamically generated download link. You can contact me through https://t.me/hchchhccc  !

Yes, the server assumes that you will only use a single thread to download this file, but in order to reduce expenditures, the Range method is still supported for download, but the Range cannot be bigger than 20M, otherwise it will generate a 403 error. The download mode of Aria2 will directly request the Range of the entire segment (reducing the number of requests), but this will prevent me from downloading this file.

**Comment by anadius** [comment]
Try using [`--enable-http-pipelining`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-enable-http-pipelining). Combine it with [--piece-length=<LENGTH>](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-piece-length) to control the piece size.

**Comment by Erope** [comment]
@anadius Thank you very much for your reply! I tried this and it does work. aria2 is indeed a powerful download tool!
