### ISSUE TITLE
aria2 can't start

### ISSUE THREAD

**Issue by wikilike7** [aria2/aria2#1639]
`2020-06-11 07:50:57.447656 [ERROR] [MultiUrlRequestInfo.cc:297] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.
2020-06-11 07:52:05.777779 [ERROR] [HttpListenCommand.cc:112] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: An attempt was made to access a socket in a way forbidden by its access permissions.`

when i upgraded to win10 2020 the aria2 can't work any more, any one know how to solve it ?

thank you

**Comment by purringChaos** [comment]
Run `netstat -an |find /i "listening"`in cmd and kill whatever is listening on that port. 
Maybe change the listen port?

**Comment by wikilike7** [comment]
I found how to fix it, it's occurred by Hyper-v port. After Windows 10 upgrade to 2004, Hyper-v use a large port range. 
Change Hyper-v's port to high port number and reduce the range.

Anyway the issue was fixed, thank you

**Comment by ianzhuo** [comment]
change the starting port like this, could solve the problem.
```batch
netsh int ipv4 set dynamic tcp start=32768 num=16384
netsh int ipv6 set dynamic tcp start=32768 num=16384
```
