### ISSUE TITLE
Small typo in error message

### ISSUE THREAD

**Issue by SumatraPeter** [aria2/aria2#1654]
By mistake I specified `-max-tries=1` instead of `--max-tries=1`, and got this:

```
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--max-tries'.
  -> [OptionHandlerImpl.cc:159] errorCode=1 Bad number ax-tries=1
```

Note that it says "Bad number **ax-tries**=1", not "Bad number **max-tries**=1". Also, technically the problem wasn't a "bad number" but the fact that I skipped one of the hyphens.

**Comment by YanceyChiew** [comment]
[-m, --max-tries=<N>](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-m)
>Set number of tries. 0 means unlimited. See also --retry-wait. Default: 5

So, if you used a single hyphen instead a n-dash, a single letter option would be recognized and the rest input was taken as an argument to this option.
Just like “-j**3**”, "-m**3**", "-k**20M**" or "-m**ax-tries=1**".

**Comment by SumatraPeter** [comment]
Thanks, that makes sense. I'll go ahead and close this then.
