### ISSUE TITLE
Which one shuold I download?

### ISSUE THREAD

**Issue by yzs0324** [aria2/aria2#1662]
aria2-1.35.0-aarch64-linux-android-build1.zip 2.34 MB

aria2-1.35.0-osx-darwin.dmg 2.1 MB

aria2-1.35.0-osx-darwin.tar.bz2 1.86 MB

aria2-1.35.0-win-32bit-build1.zip 2.06 MB

aria2-1.35.0-win-64bit-build1.zip 2.11 MB

aria2-1.35.0.tar.bz2 2.2 MB

aria2-1.35.0.tar.gz 3.62 MB

aria2-1.35.0.tar.xz 1.46 MB

Source code (zip)

Source code (tar.gz)

**Comment by yzs0324** [comment]
My computer is Win 10,64 digits

**Comment by saisesai** [comment]
aria2-1.35.0-win-64bit-build1.zip 2.11 MB

**Comment by yzs0324** [comment]
> aria2-1.35.0-win-64bit-build1.zip 2.11 MB

Yeah,I actually download that,and I double click the program,and nothing happens.

**Comment by saisesai** [comment]
this is a command line tool，you may should read the readme. md
