### ISSUE TITLE
[QUESTION] How to disable showing download stats every minute for BitTorrent?

### ISSUE THREAD

**Issue by plagov** [aria2/aria2#1665]
When I download a file using BitTorrent, then every minute it prints the download/upload statistic to the console:
```
 *** Download Progress Summary as of Thu Aug  6 10:38:02 2020 ***
<...>
 *** Download Progress Summary as of Thu Aug  6 10:39:03 2020 ***
```
I couldn't find in man pages a respective key to pass in to make it quite or less verbose. Is it possible?

**Comment by Hurricos** [comment]
`man aria2c`:

```
       -q, --quiet [true|false]
              Make aria2 quiet (no console output).  Default: false
```

**Comment by plagov** [comment]
@Hurricos, thanks for your reply! This `--quiet` shuts all output down. That's not what I'm looking for. I would like to keep the stats of the speed, ETA, percentage and so on. Just don't want to have every minute summary updates.

**Comment by Hurricos** [comment]
If you're under Linux, you could try something like this:

`aria2c $OPTIONS 2>&1 | stdbuf -oL grep -v 'Download Progress Summary'`

This `2>&1` merges stderr with stdout, and `stdbuf -oL` runs a program, making sure that the output of that program spits out a line when it has a line to spit out. Then the `grep -v` just excludes that part of the output.

**Comment by abactuon** [comment]
?
--summary-interval=<SEC>

**Comment by plagov** [comment]
@abactuon, looks like it is. Thanks a lot!
