### ISSUE TITLE
Binary file is too large (114 Mb) after build

### ISSUE THREAD

**Issue by django1222** [aria2/aria2#1668]
After build aria2 the generated binary file is too much large (114 Mb). I'm using Ubuntu BTW

**Comment by tofuliang** [comment]
```shell
strip aria2c
```

**Comment by django1222** [comment]
Thanks for your reply but what do you mean by strip aria2c ?

**Comment by tofuliang** [comment]
> what do you mean by strip aria2c ?

[usage of strip](https://www.computerhope.com/unix/strip.htm)

**Comment by django1222** [comment]
OMG Thank you bro now it's just 2.9 MB
