### ISSUE TITLE
how to exclude file in BitTorrent/Metalink?

### ISSUE THREAD

**Issue by gMan1990** [aria2/aria2#1686]
`--select-file` https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-select-file

**Comment by sithglan** [comment]
# Download the torrent
aria2c --bt-metadata-only=true --bt-save-metadata=true 'magnet:?xt=urn:btih:...'
# Show the files
aria2c -S <torrent>
# Download only the files you want
aria2c --file-allocation=none --select-file=1 <torrent>
