### ISSUE TITLE
Does aria2 support Linux?

### ISSUE THREAD

**Issue by axetroy** [aria2/aria2#1731]
I can’t find the Linux version on the Github Release page. Does this tool support Linux?

**Comment by chromer030** [comment]
aria2 is available almost for any UNIX OS , from Linux to BSDs and almost all architectures.
You can find package for any distro here : https://pkgs.org/search/?q=aria2
But install it via your distro's package manager , in order to handle dependencies.

**Comment by axetroy** [comment]
@chromer030 thank you very much for your help, have a good day :)
