### ISSUE TITLE
Can aria2 just download torrent file?

### ISSUE THREAD

**Issue by militaooo** [aria2/aria2#1741]
I have a magnet link and I just wanna download the torrent file, can aria2 do this?

**Comment by WilliamZY** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-follow-torrent

**Comment by militaooo** [comment]
> https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-follow-torrent

good job buddy
