### ISSUE TITLE
What is the default value for the --continue option?

### ISSUE THREAD

**Issue by louie-github** [aria2/aria2#1744]
I've been looking through the [documentation](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-c) on the options for `aria2c` and I've noticed just one thing. The documentation for the `--continue` option seems to not specify a default value for it.

![image](https://user-images.githubusercontent.com/30176969/107057354-53d17980-680e-11eb-874a-bd92f2177bc6.png)

Is it something to do with how the option works or not? It apparently takes either `true` or `false`, as it is listed as `-c, --continue [true|false]`. By default, is it set to true or false?

I apologize if this is just a misunderstanding on my part and the option really is not meant to have a default value. Thank you.

**Comment by hasitpbhatt** [comment]
It's by default value is "false". 

If you want to use it, you need to add "--continue" / "-c" explicitly. You can confirm the same [here](https://github.com/aria2/aria2/blob/15cad965eb75c8b7f11bc2fc94354d1873bf6261/src/OptionHandlerFactory.cc#L160).

**Comment by louie-github** [comment]
Thank you so much for your response.
