### ISSUE TITLE
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

### ISSUE THREAD

**Issue by JDOUBLE-U** [aria2/aria2#1785]
```
$ /hpc/local/CentOS7/aria2-1.35.0/src/aria2c -v
aria2 version 1.35.0
Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.7 libxml2/2.9.1 sqlite3/3.7.17 OpenSSL/1.0.2k
Compiler: gcc 4.8.5 20150623 (Red Hat 4.8.5-39)
  built by  x86_64-pc-linux-gnu
  on        Nov  6 2019 17:47:49
System: Linux 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/
```
Receiving this error on our cluster when downloading files from an aria.txt file (HTTPS, googleapis.com), locally on my Mac it works like charm. Could someone help me out with a solution? I have already tried to install a Conda version of aria2c including certifi and ca-certificates. Nothing seems to work :(

**Comment by tyeeman** [comment]
I'm getting this same error connecting to Easynews.

**Comment by JDOUBLE-U** [comment]
You should check the certificates, these were expired. For me that worked

**Comment by tyeeman** [comment]
I'm on windows and I found out how to display the certificates but there are over 45 in my list. Which section do I need to check and how do I renew it? If your on Linux I guess you would not know.
<img width="433" alt="2021-08-20_174645" src="https://user-images.githubusercontent.com/4469306/130305303-af32e242-4c2b-42d2-8477-300b46f2c521.png">
