### ISSUE TITLE
Allow change of download URL

### ISSUE THREAD

**Issue by alpha7504** [aria2/aria2#1788]
Hello,

I don't know if this feature is already included, but i want to be able to change download URL of a download task in midway.
There are times when the file is large and the download address expires or no longer reachable or file is deleted from server before the download could complete. At such moments, users should be able to change the download URL of the task to resume the download from where it was paused. Is such a feature already present?

Using aria2 1.35.0-2 on openwrt 19.07.7
Regards!

**Comment by alpha7504** [comment]
Issue is closed, since after spending hours on trying to replace the download link, i found that after deleting the download task, i can simply resume the download by adding a download task with new link. Could've saved me hours..! Still i wish change of download link with current download task be possible instead of deleting the task and adding again with new link.

**Comment by leic4u** [comment]
DO NOT DELETE THE TASKS!!! the progress of tasks would be lost if you delete the tasks before you created new tasks.

Only pause the tasks, and creat new tasks, the download will be continued with the progress. After the tasks are downloading correctly, you can delete the expires tasks. it's useful to me.

**Comment by alpha7504** [comment]
Thank you for your input, The important part is .aria2 file, which I think is a download session file that is created along with download file. As long as this file remains, it doesn't matter whether task is deleted or not, the download will always resume. And that is how it works for me.
