### ISSUE TITLE
Wrong version when checked

### ISSUE THREAD

**Issue by dancristino** [aria2/aria2#1803]
The version (v1.36.0) doesn't reflect on the compiled 64bit version when checked in the command line.

Haven't tried the 32 bit.

![image](https://user-images.githubusercontent.com/49893577/130324866-1c22a349-4a99-4220-8e42-a8475d13b46d.png)

**Comment by nkh0472** [comment]
![20210822111120](https://user-images.githubusercontent.com/67589323/130340648-6af10dc5-eff8-4fb3-af02-8d901c64bf7c.png)
The problem you mentioned did not appear in the official release. Are you sure that the new version of the file is launched in your picture? I see that the compilation date is October 6, 2019...
https://github.com/aria2/aria2/releases/tag/release-1.36.0

**Comment by dancristino** [comment]
My bad.

I had an older version placed inside of my "Windows" folder while having the newer one in my "ProgramData" folder.

Sorry.
