### ISSUE TITLE
Invalid behavior when $XDG_CONFIG_HOME is empty.

### ISSUE THREAD

**Issue by zhanghua000** [aria2/aria2#1817]
According to https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html, $XDG_CONFIG_HOME should be $HOME/.config if it is either not set or empty.  I am using aria2 on ArchLinux and my $XDG_CONFIG_HOME is empty. When I start aria2 from systemd with command `/usr/bin/aria2c --daemon=true`, aria2 says that I should specify at least one URL. This looks like it doesn't find my config file in ${HOME}/.config/aria2/aria2.conf

**Comment by abcfy2** [comment]
By default systemd only pass few environment variables to service. You can find the description here: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment%20Variables%20in%20Spawned%20Processes

So you should declare environment variable yourself use `Environment=` or `EnvironmentFile=`

**Comment by zhanghua000** [comment]
I see in code that aria2c has support of that using $HOME/.config as fallback when $XDG_CONFIG_HOME is empty . So maybe it is my fault, I will check my settings.
