### ISSUE TITLE
[Question] Can Aria2 download files from Mediafire?

### ISSUE THREAD

**Issue by LOuroboros** [aria2/aria2#1825]
For a bit of context, I'm trying to download a file that I uploaded to Mediafire as a way to test out Aria2.
I used `aria2c https://www.mediafire.com/file/sxcy91c52cp6vsv/test.txt/file` to download the file, however, instead of downloading the actual file, Aria created a file called `file` of about 312kb.
Even if I remove the last `/file` out of the link the result is still the same, just in case that's worth mentioning.
This leads me to ask, can Aria2 download files from Mediafire?

**Comment by redranamber** [comment]
It can but you need the url of the actual file first. You get that url when you click the download link on the page. Put that into aria2 to download the file.

**Comment by LOuroboros** [comment]
> 
> 
> It can but you need the url of the actual file first. You get that url when you click the download link on the page. Put that into aria2 to download the file.

Oh. I was hoping it would just fetch a list of URLs present in the page and pick the right one.

Do you know if there's any plans to make it behave like that?

**Comment by redranamber** [comment]
If that is what you are looking for try jdownloader or downthemall.

If you must use aria2 you can find many browser extensions that will pass download links to it when they are clicked.
