### ISSUE TITLE
I'm getting response status not successful download aborted error code 22 403 forbidden for this link 

### ISSUE THREAD

**Issue by ank003** [aria2/aria2#1831]
![IMG_20211001_133404_860__01.jpg](https://user-images.githubusercontent.com/89583050/135586458-0cd9705d-42f3-4215-9e36-28ae4e408ffb.jpg)

This error for This Below mpd link 
https://nammaflix-streams.streamready.in/NAMMAFLIX/FEATUREFILM/6135c2da4bdb2711dbc3b40a/dash/manifest.mpd?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vbmFtbWFmbGl4LXN0cmVhbXMuc3RyZWFtcmVhZHkuaW4vTkFNTUFGTElYL0ZFQVRVUkVGSUxNLzYxMzVjMmRhNGJkYjI3MTFkYmMzYjQwYS9kYXNoLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzMwODI1Mjh9fX1dfQ__&Key-Pair-Id=APKAIWHAQM7JDJRYIKDA&Signature=nHPGootChBO4rB2Z8Uzjl3TyZjo2~-AxeWn1VrVzFS5zUcX83MJewCRpuc7F1IeM5TbtXZEzDeWAobppP2NND8kMXD08uB7toEJlzQf5TKlTNo~AFxIolHsr6VXI9K7JicYNX-KwKKEnrjNh-8jEjTuCDUR3G29Ao~G~hAVxJc0SwidfmuGV6mXBv0B9byNcwriulR7aOAILT1ogxBvXbmk6MFTPY7obnO727zFq398phVjcufI~NA2DHLzS8xXCCmepSNgHzUtovdcWym9v~LIORkwNIWNvCwiD2yrZBmyvSK9CRoYzeZGO5H~qM2oZH13e4Mws4cJzbPAwMHZrWg__&spid=NAMMAFLIX-XSTREAM&request-id=40339B34AF4B4F74994F18FD5B926E93&uid=0cvABY9UGpXoKeM3i0

While downloading externally through yt-dlp
Can anyone please help me ....

**Comment by kikuyan** [comment]
Ask yt-dlp.

**Comment by ank003** [comment]
> Ask yt-dlp.

May be because of cookies..?. Bro ... How can we add cookies for this aria2...?? Like in ytdlp..??
