### ISSUE TITLE
aria2c does not download at all

### ISSUE THREAD

**Issue by winkee01** [aria2/aria2#1848]
I execute this command in the command line, it won't download at all.
```
aria2c https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2
```

<img width="1437" alt="notwork@2x" src="https://user-images.githubusercontent.com/49930785/140172735-7d6ac6c7-ecee-4c6c-b12a-d827a306888f.png">

**Comment by winkee01** [comment]
after executing the command, nothing happened, it seems it only listens on some port but never does the download.

**Comment by abcfy2** [comment]
Did you write a custom config file `~/.aria2/aria2.conf`.

You may check this file whether you use `dir=<new_location>` to download into a new directory not current working directory.

Or you can just remove this file to let aria2c use default options.

**Comment by winkee01** [comment]
> 

I do have this file `~/.aria2/aria2.conf`, and seems there is nothing wrong with it. As you can read from the prompt, the download job didn't even start.

**Comment by winkee01** [comment]
After I press `Ctrl-C`

```
aria2c https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2 -c                                                   17:15:55

11/22 17:15:57 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

11/22 17:15:57 [NOTICE] IPv4 RPC: listening on TCP port 6800

11/22 17:15:57 [NOTICE] IPv6 RPC: listening on TCP port 6800

11/22 17:16:03 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================

11/22 17:16:03 [NOTICE] Serialized session to '/Users/winkee/.aria2/aria2.session' successfully.
```

**Comment by abcfy2** [comment]
Please also show your `~/.aria2/aria2.conf`, maybe something wrong within it.

Or you may try to remove this file to see if `aria2c` works.

**Comment by winkee01** [comment]
> Please also show your `~/.aria2/aria2.conf`, maybe something wrong within it.
> 
> Or you may try to remove this file to see if `aria2c` works.

Thanks so much, I finally got it worked. This line `input={HOME}/.aria2/aria2.session` in aria2.conf make aria2 to read the download list from this file, which causes the `aria2c https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2 -c` to not work.
