### ISSUE TITLE
Libaria2ex cannot download HTTPS links on the mingw platform

### ISSUE THREAD

**Issue by xiaoke0O** [aria2/aria2#1849]
I can successfully compile and run [libaria2ex.cc](https://github.com/aria2/aria2/blob/master/examples/libaria2ex.cc) on both debian and mingw64 （windows10） platforms, but I get an error when I download the HTTPS link on mingw64 （windows10） platforms. The same code does not fail to download HTTPS links on the Debian platform.

- mingw64 aria2  v1.36.0-1
- debian     aria2  v1.34.0-4

The test result is given as：

|            | mingw64（windows10） | mingw64（windows10）      |debian | debian |
| ---------- | -------------------- | ----- | -------------------------- | ------ |
|            | http                 | https | http                       | https  |
| aria2c     | √                    | √     | √                          | √      |
| libaria2ex | √                    | ×     | √                          | √      |

![run on msys2/mingw64](https://user-images.githubusercontent.com/46664191/140638300-5570954f-8c9a-4de6-bc04-0e6b5181ee90.png)

**Comment by xiaoke0O** [comment]
How can I modify the libaria2ex code to support HTTPS links on ming64 platforms?

**Comment by xiaoke0O** [comment]
Adding a '--check-certificate=false' argument to sessionNew fixes the problem. I think it should be the problem of certificate on mingw64 platform.

![image](https://user-images.githubusercontent.com/46664191/140644742-dd17ca65-9b67-4c8f-885d-27af257e7b3b.png)

**Comment by abcfy2** [comment]
Maybe you can try build without `openssl` (do not add openssl in your build environment or add `--without-openssl`) in your configure arguments.

Because windows provides `WinTLS` and aria2 can use it by default.

**Comment by xiaoke0O** [comment]
Thank you very much！
