### ISSUE TITLE
file-allocation=none not working properly

### ISSUE THREAD

**Issue by alpha7504** [aria2/aria2#1851]
Hello

File allocation option is set to none, but aria2 still allocates space when downloading files over p2p or other protocols and it goes into non responding mode until the space fully allocates.

This seems to be only happening when I'm adding download by ariang web ui or other webui by RPC.

If I add download by CLI, like this

`aria2c --file-allocation=none [URL]`
then it works fine, no allocation issue... downloads to my DL dir set in config file.

if I download like this
`aria2c [URL]`

Then file allocation is happening and it warns about using `--file-allocation=none`, but still download file goes to my DL dir set in config file.

`11/09 19:36:43 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.`

Somehow, it's only ignoring `--file-allocation=none` in config file which is weird, because it's downloading to my set DL dir in config file but ignoring --file-allocation=none.

Config file clearly has the above line. Why it's not working through web-gui as well?

**Comment by alpha7504** [comment]
file allocation=none cant work when split is greater than one...

**Comment by alpha7504** [comment]
I am opening this again, since the issue is not solved... for http downloads, after setting split to 1, the issue is solved and no more allocation of file space, but for torrent downloads the `file-allocation=none` is still not working...

Weirdly by using CLI  `aria2c --file-allocation=none [torrentFile]`, it works fine, but from GUI it doesn't? why it's happening...?

This is my config file... just incase i messed something up.
`dir=/mnt/sda1/downloads
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
quiet=true
continue=true
input-file=/mnt/sda1/config/aria2/aria2.session.main
save-session=/mnt/sda1/config/aria2/aria2.session.main
check-certificate=false
enable-dht=true
dht-file-path=/mnt/sda1/config/aria2/dht.dat.main
bt-enable-lpd=true
bt-save-metadata=true
bt-seed-unverified=true
disable-ipv6=true
disk-cache=1M
enable-peer-exchange=true
file-allocation=none
follow-torrent=true
force-save=true
max-concurrent-downloads=2
max-connection-per-server=5
max-tries=3
retry-wait=20
save-session-interval=30
split=1
bt-load-saved-metadata=true`

**Comment by anadius** [comment]
This is HTTP example but the same applies for torrent downloads.

First a small legend. `-` means unallocated space, `+` allocated, `*` downloaded.

When you use `file-allocation=none`, `split=2` and `max-connection-per-server=2` this is what happens:
```
-------- - unallocated file
*------- - data from the first split saved
aria wants to save some data from the second split and starts allocating file
*+++----- - allocated file
*+++*---- - data from the second split saved
```
And it seems that allocation is done using the default method, so `prealloc`.

To solve your problem use `file-allocation=trunc` instead. As the manual says:
> Using `trunc` seemingly allocates disk space very quickly, but what it actually does is that it sets file length metadata in file system, and **does not allocate disk space at all**. This means that it does not help avoiding fragmentation.

**Comment by alpha7504** [comment]
thanks for your reply... 
I really appreciate the details. I tried all the allocation options and nothing is effective for torrent downloads,
I assume the reason being exfat file system. I switched over to this one for its better performance over ntfs. Anyway I'm used to it now.

**Comment by anadius** [comment]
Yup, can confirm. `file-allocation=trunc` works as intended on NTFS but it doesn't on exFAT.

**Comment by alpha7504** [comment]
Ok, thanks for clarification.
