### ISSUE TITLE
Huge binary file size difference between 1.35 and 1.36.

### ISSUE THREAD

**Issue by stangri** [aria2/aria2#1852]
I've build 1.35 from sources a while back and it's just 14Kb:

```sh
$ ls -la /usr/bin/aria2c
.rwxr-xr-x 14k root 22 Mar  2020 /usr/bin/aria2c
$ file /usr/bin/aria2c
/usr/bin/aria2c: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=ffc8ccaf97b0555d9f8ba16227981246780ba119, for GNU/Linux 3.2.0, stripped
$ /usr/bin/aria2c -v
aria2 version 1.35.0
...
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 libxml2/2.9.10 sqlite3/3.31.1 GnuTLS/3.6.11 nettle GMP/6.2.0 c-ares/1.15.0 libssh2/1.8.0
Compiler: gcc 9.3.0
  built by  x86_64-pc-linux-gnu
  on        Mar 22 2020 15:33:25
System: Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64
...
```

However when I build 1.36 now, I get:

```sh
$ ls -la aria2_git/src/aria2c
.rwxrwxr-x 3.0M stangri 18 Nov 12:56 aria2_git/src/aria2c
$ file aria2_git/src/aria2c
aria2_git/src/aria2c: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=bc3b9fb3e1123b740f10c8dcf6901fce28af6ab7, for GNU/Linux 3.2.0, stripped
$ aria2_git/src/aria2c -v
aria2 version 1.36.0
...
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 libxml2/2.9.10 sqlite3/3.31.1 GnuTLS/3.6.13 nettle GMP/6.2.0 c-ares/1.15.0 libssh2/1.8.0
Compiler: gcc 9.3.0
  built by  x86_64-pc-linux-gnu
  on        Nov 18 2021 12:47:45
System: Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64
...
```

It's a huge file size difference (14Kb vs 3Mb).  Is that the SYSV vs GNU/Linux ELF format which can explain that? I've used default `autoreconf -i; ./configure`, can I do anything different to reduce the final binary file?

**Comment by yoran4096** [comment]
-Os -s -flto -fdata-sections -ffunction-sections -Wl,--gc-sections

**Comment by stangri** [comment]
> -Os -s -flto -fdata-sections -ffunction-sections -Wl,--gc-sections

Thank you for your detailed response. Neither `autoreconf`, nor `./configure` nor `make` accept this as the legit parameters, so I have no idea how it can help.

**Comment by yoran4096** [comment]
Set compiler environment variables like this
export XFLAGS="-w -pipe -Os -s -flto -fdata-sections -ffunction-sections -Wl,--gc-sections"
export CFLAGS=$XFLAGS
export CXXFLAGS=$XFLAGS

**Comment by yoran4096** [comment]
This is my unfinished compilation script. It works normally on common platforms and android. You can run it with docker or install alpine on a virtual machin
[aria2-cross-build.zip](https://github.com/aria2/aria2/files/7571984/aria2-cross-build.zip)
e.

**Comment by stangri** [comment]
@yoran4096 Thank you for clarification and sharing the build script. Setting the flags reduced the binary size from ~ 3.0Mb to ~1.7Mb. It's still a dramatic difference from version 1.3.5 file size of just 14Kb!

I don't know enough to understand if it's the build tools or environment or what, @tatsuhiro-t can you please have a look and advise?

**Comment by yoran4096** [comment]
Generally speaking, it is not possible to 14kb... If all dynamic links can reduce a certain size

**Comment by stangri** [comment]
> Generally speaking, it is not possible to 14kb... If all dynamic links can reduce a certain size

```sh
$ ls -la $(which aria2c)
.rwxr-xr-x 14k root 22 Mar  2020 /usr/bin/aria2c
```

**Comment by stangri** [comment]
Anyone?

**Comment by STSMHQ** [comment]
> Anyone?

@stangri May u upload the 14KB version of aria2, please?! I compiled the 1.35 version by my own and I could not get any smilar size. I would like to keep your small version, if possible.

**Comment by stangri** [comment]
> > Anyone?
> 
> @stangri May u upload the 14KB version of aria2, please?! I compiled the 1.35 version by my own and I could not get any smilar size. I would like to keep your small version, if possible.

It maybe have come from the Ubuntu 20.04 package, not self-compiled.

**Comment by STSMHQ** [comment]
> > > Anyone?
> > 
> > 
> > @stangri May u upload the 14KB version of aria2, please?! I compiled the 1.35 version by my own and I could not get any smilar size. I would like to keep your small version, if possible.
> 
> It maybe have come from the Ubuntu 20.04 package, not self-compiled.

Yours or mine?! Could u share your 14KB binary file with me, please?

**Comment by stangri** [comment]
@STSMHQ https://paste.c-net.org/PoeticPopeye

**Comment by Jimmy-Z** [comment]
most likely that's the one from the distribution.
`/usr/bin/aria2c --version` should give you some idea

I have a 14k aria2c on my arch as well.
```$ ls -al $(which aria2c)
-rwxr-xr-x 1 root root 14200 May  5  2020 /usr/bin/aria2c```

```$ ldd $(which aria2c)
        linux-vdso.so.1 (0x00007ffe401d6000)
        libaria2.so.0 => /usr/lib/libaria2.so.0 (0x00007f3cb8306000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f3cb80f0000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3cb80d5000)
...```
you see that `libaria2.so.0` there?

```$ ls -al /usr/lib/libaria2.so.0.0.0
-rwxr-xr-x 1 root root 3999856 May  5  2020 /usr/lib/libaria2.so.0.0.0```
this is your answer.
