### ISSUE TITLE
Status of download launched by CLI

### ISSUE THREAD

**Issue by smm993** [aria2/aria2#1861]
How can I track the status of downloads which would have been launched through the aria2c command line by JSON-PRC ?

For example, if I launch the command "aria2c --gid=f24eb9711a8b5f44 https://speed.hetzner.de/100MB.bin" through CLI, 
How do I capture the percentage download  by JSON-RPC ?

**Comment by anadius** [comment]
You can't. Start the RPC server, add the download with [`aria2.addUri`](https://aria2.github.io/manual/en/html/aria2c.html#aria2.addUri) method and then check the status with [`aria2.tellStatus`](https://aria2.github.io/manual/en/html/aria2c.html#aria2.tellStatus).
