### ISSUE TITLE
RPC interface fails to bind

### ISSUE THREAD

**Issue by cn857** [aria2/aria2#1878]
01/26 22:12:37 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

01/26 22:12:37 [ERROR] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: An attempt was made to access a socket in a way forbidden by its access permissions.

01/26 22:12:37 [ERROR] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.

**Comment by cn857** [comment]
It seems like the aria2 default 6800 port used by the other process,but i checked the process,no process used the 6800 port

**Comment by cn857** [comment]
Hope to get a reply

**Comment by jduerstock** [comment]
Are you running this out of Docker or some sort of other setup?  This error doesn't usually get thrown by a full system in my experience.
