### ISSUE TITLE
aria2c can't download torrent but other app can download

### ISSUE THREAD

**Issue by jazz1611** [aria2/aria2#1903]
Hello,

I have use video from "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" and create to torrent file (https://xfl.jp/7ceksM or https://anonfiles.com/T3H8p1U0xb/BigBuckBunny.mp4_torrent). For testing download from torrent have Info Hash v1 and v2.

the aria2c (latest version 1.36.0) can't download/seed anything. but other app can download it as normal. can you @tatsuhiro-t  check it? there is my setting

```
bt-tracker=xxxxxxxxxxxxx
check-integrity=true
summary-interval=0
seed-time=0
bt-max-peers=0
bt-tracker-interval=120
bt-remove-unselected-file=true
enable-dht6=true
listen-port=15000-16000
dht-listen-port=15000-16000
enable-peer-exchange=true
bt-enable-lpd=true
dht-entry-point=dht.transmissionbt.com:6881
dht-entry-point6=dht.transmissionbt.com:6881
seed-ratio=0
```

aria2 log process

```
04/07 18:13:01 [[1;32mNOTICE[0m] Downloading 1 item(s)

04/07 18:13:01 [[1;32mNOTICE[0m] IPv4 DHT: listening on UDP port 15673

04/07 18:13:01 [[1;32mNOTICE[0m] IPv6 DHT: listening on UDP port 15673

04/07 18:13:01 [[1;31mERROR[0m] Checksum error detected. file=download/BigBuckBunny.mp4

04/07 18:13:01 [[1;32mNOTICE[0m] IPv4 BitTorrent: listening on TCP port 15197

04/07 18:13:01 [[1;32mNOTICE[0m] IPv6 BitTorrent: listening on TCP port 15197
[#5492b8 0B/150MiB(0%) CN:0 SD:0 DL:0B]
[#5492b8 0B/150MiB(0%) CN:2 SD:0 DL:0B]
[#5492b8 0B/150MiB(0%) CN:2 SD:0 DL:0B]
[#5492b8 0B/150MiB(0%) CN:1 SD:0 DL:0B]
[#5492b8 0B/150MiB(0%) CN:1 SD:0 DL:0B]
[#5492b8 0B/150MiB(0%) CN:0 SD:0 DL:0B]
[#5492b8 0B/150MiB(0%) CN:0 SD:0 DL:0B]
.....
similar result to timeout process with (--bt-stop-timeout=21600)
```

this torrent have only Info Hash v1 (https://anonfiles.com/v1P0ufUfx7/BigBuckBunny_only_v1.mp4_torrent) and aria2c can download as normal

**Comment by jazz1611** [comment]
hello @tatsuhiro-t

i found other problem when aria2c show content of torrent file. it not same Magnet URI when compare with (example: qBittorrent). i think this reason make aria2c can't download.

Get Magnet URI from torrent file "BigBuckBunny.mp4.torrent"

aria2c result:
`magnet:?xt=urn:btih:8F40914678B02CD8846F33D15772171C5A816978&dn=BigBuckBunny.mp4&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Fwww.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker4.itzmx.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fvibe.sleepyinternetfun.xyz%3A1738%2Fannounce&tr=udp%3A%2F%2Ftracker2.dler.org%3A80%2Fannounce`

qBittorent result:
`magnet:?xt=urn:btih:109e65aa961de56187665cfeb58153cc096e54b1&xt=urn:btmh:1220f46b4465fc8a1db36a11bf973ba1317f1df5c112e36e0e051db4c4776b3e6ad3&dn=BigBuckBunny.mp4&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=http%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2f9.rarbg.com%3a2810%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a6969%2fannounce&tr=http%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2fopentracker.i2p.rocks%3a6969%2fannounce&tr=https%3a%2f%2fopentracker.i2p.rocks%3a443%2fannounce&tr=udp%3a%2f%2fwww.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2ftracker.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2fopen.stealth.si%3a80%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2fipv4.tracker.harry.lu%3a80%2fannounce&tr=udp%3a%2f%2fopentor.org%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker4.itzmx.com%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.moeking.me%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.dler.org%3a6969%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2fvibe.sleepyinternetfun.xyz%3a1738%2fannounce&tr=udp%3a%2f%2ftracker2.dler.org%3a80%2fannounce`

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.  #1905 fixes it.

**Comment by jazz1611** [comment]
> Thank you for reporting this. #1905 fixes it.

hello,

i just make a new static build and it work fine with my report. but in some torrent it still can't download although is connect type is BT (not uTP). qBittorrent can download but aria2c is can't. it same provider ISP, same machine. which Torrent is private, it can't download too. hope you can improve more for Torrent feature and integrate the uTP connect to aria2c.

Torrent private: https://anonfiles.com/V6x9ZcU9xf/BigBuckBunny.mp4_private_torrent

thank you.

**Comment by tatsuhiro-t** [comment]
Closing because this specific bug is fixed.  No plan to add new features to aria2 for now.
