### ISSUE TITLE
Python and CPP bindings for this?

### ISSUE THREAD

**Issue by Advik-B** [aria2/aria2#1926]
This is the best network-related project i've ever seen. is there a python and a cpp binding for this in such a way that I can also track progress. etc?

**Comment by zjyl1994** [comment]
CPP binding: https://aria2.github.io/manual/en/html/libaria2.html

**Comment by pawamoy** [comment]
[aria2p](https://github.com/pawamoy/aria2p)? 😛

**Comment by Advik-B** [comment]
Closing in favor  of @pawamoy and @zjyl1994.
Thank you so much
