### ISSUE TITLE
aria2 downloads files multiple times (duplicates)

### ISSUE THREAD

**Issue by paxsali** [aria2/aria2#1959]
Hello there,

I'd like to report the following bug I seem to have discovered...

Given the following input URLs file as input:

`urls.txt`:

```text
https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/kernel-default-5.18.15-1.1.x86_64.rpm
https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/kernel-default-5.18.15-1.1.x86_64.rpm.mirrorlist
https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/kernel-default-base-5.18.15-1.1.24.25.x86_64.rpm
https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/kernel-default-base-5.18.15-1.1.24.25.x86_64.rpm.mirrorlist
https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/kernel-default-devel-5.18.15-1.1.x86_64.rpm
https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/kernel-default-devel-5.18.15-1.1.x86_64.rpm.mirrorlist
```

And the following cmdline usage will download the same files multiple times and rename them, even though it is specified in the cmdline arguments to never use auto file renaming:

```sh
aria2c -q -R --console-log-level=error \
    --allow-overwrite false --auto-file-renaming false \
    -i urls.txt \
    -d .
```

No errors are produced by this command.

The following files are present after the download has finished:

```text
kernel-default-5.18.15-1.1.x86_64.1.rpm
kernel-default-5.18.15-1.1.x86_64.rpm
kernel-default-5.18.15-1.1.x86_64.rpm.1.metalink
kernel-default-5.18.15-1.1.x86_64.rpm.metalink
kernel-default-base-5.18.15-1.1.24.25.x86_64.1.rpm
kernel-default-base-5.18.15-1.1.24.25.x86_64.rpm
kernel-default-base-5.18.15-1.1.24.25.x86_64.rpm.metalink
kernel-default-devel-5.18.15-1.1.x86_64.rpm
kernel-default-devel-5.18.15-1.1.x86_64.rpm.metalink
```

This is obviously incorrect as some files are being downloaded multiple times, the redundant files having `.[0-9]+.{ext}` suffix (the number is incremented if you repeat the operation).

I tested the same input file with `wget -i urls.txt` and the bug doesn't happen.
I also noticed that the cmdline switches used in the command seem not to be the problem, as a simple `aria2c -i urls.txt` produced the same list of (duplicate) downloaded files.

On my environment this is reproducible 100% of the time.

Aria2 version: `aria2 version 1.36.0`
OS: openSUSE Tumbleweed (everything up-to-date)

Any more questions you have about my environment, I can answer.

Thanks in advance.

**Comment by saltedcoffii** [comment]
@paxsali , could `--allow-overwrite=false` be the option you're looking for?

**Comment by paxsali** [comment]
I think I found the reason for this.

Apparently, if the list of URLs in the input file `urls.txt` contain files with the extension `.mirrorlist`, then aria2 instead of downloading the files as text, like it is the case when testing with `curl` or `wget`, it downloads the references files inside the `.mirrorlist` files.

Simple, reproducable example:

```bash
mkdir /tmp/aria2_tests
cd /tmp/aria2_tests
echo 'https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/zypper-1.14.58-1.1.x86_64.rpm' >> urls.txt
echo 'https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/zypper-1.14.58-1.1.x86_64.rpm.mirrorlist' >> urls.txt
```

Now before we continue here you must understand the contents of that `.mirrorlist` file (line number 2 in the `urls.txt` file).
It's a regular HTML file which contains several mirror URLs for the exact same file `.../tumbleweed/repo/oss/x86_64/zypper-1.14.58-1.1.x86_64.rpm`.

What I didn't know: apparently aria2 detects and treats `.mirrorlist` files differently (intelligently).

Continuing the example:

```bash
aria2c -q -R --console-log-level=error --allow-overwrite false --auto-file-renaming false -i urls.txt -d .
ls -l
```

Output:

```text
total 3376
-rw------- 1 paxsali paxsali     197 Dec 19 23:21 urls.txt
-rw------- 1 paxsali paxsali 1717692 Nov  9 13:53 zypper-1.14.58-1.1.x86_64.1.rpm    
-rw------- 1 paxsali paxsali 1717692 Nov  9 13:53 zypper-1.14.58-1.1.x86_64.rpm      
-rw------- 1 paxsali paxsali   11364 Dec 19 23:21 zypper-1.14.58-1.1.x86_64.rpm.meta4
```

I didn't know about this behavior when I opened the issue. My assumption was, aria2c will download the `.mirrorlist` file just the same way `curl` or `wget` would.

You can verify that by giving aria2c a `.mirrorlist` file directly as the URL on the arguments list (instead of -i input file):

```bash
# still inside /tmp/aria2_tests
aria2c 'https://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/x86_64/zypper-1.14.58-1.1.x86_64.rpm.mirrorlist'
ls -l
```

Output:

```text
total 1692
-rw------- 1 paxsali paxsali 1717692 Dec 19 23:33 zypper-1.14.58-1.1.x86_64.rpm      
-rw------- 1 paxsali paxsali   11364 Dec 19 23:33 zypper-1.14.58-1.1.x86_64.rpm.meta4
```

Also apparently, when a target URL is both inside the input file `urls.txt` (or arguments list), but the same target URL is also contained inside any given `.mirrorlist` URL, then `--allow-overwrite=false` **does not work as intented** and is infact with no effect.

If you don't know that, it's highly unintuitive as to why any files are actually being downloaded multiple times, and hence renamed, despite specifying `--allow-overwrite=false` explicitly as a user.

For my part, as the user who reported this issue, I can now live with this fact (**now that I know**).

Whether or not this behavior was intentional or unintentional from the side of the authors, that I don't know and I'll leave that up to you guys whether or not to treat this as a hard bug (requiring a fix), or simply user error on my side (no further action from you).

I'm closing this issue for now.
