### ISSUE TITLE
Crash when downloading on Fedora36

### ISSUE THREAD

**Issue by Mrcoolfuyu** [aria2/aria2#1968]
crash dump here

> Directory /var/spool/abrt/Python3-2022-08-19-00:22:51-66429
abrt_version 2.14.6
analyzer abrt-python3-handler
architecture x86_64
backtrace socket.py:955:getaddrinfo:socket.gaierror: [Errno -2] Name or service not known Traceback (most recent call last): File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/usr/lib64/python3.10/http/server.py", line 1290, in <module> test( File "/usr/lib64/python3.10/http/server.py", line 1239, in test ServerClass.address_family, addr = _get_best_family(bind, port) File "/usr/lib64/python3.10/http/server.py", line 1222, in _get_best_family infos = socket.getaddrinfo( File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -2] Name or service not known Local variables in innermost frame: host: '[::]' port: 9444 family: 0 type: <SocketKind.SOCK_STREAM: 1> proto: 0 flags: <AddressInfo.AI_PASSIVE: 1> addrlist: []
cmdline python -m http.server -b [::] 9444
component python3.10
count 2
crash_function getaddrinfo
duphash a62ccf2de1e7005294bafa6c6c9e61505feb9f6b
exception_type socket.gaierror
executable /usr/lib64/python3.10/http/server.py
hostname NAS
interpreter python-unversioned-command-3.10.5-1.fc35.noarch
kernel 5.17.13-200.fc35.x86_64
last_occurrence 1660839938
os_release Fedora release 35 (Thirty Five)
package python3-libs-3.10.5-1.fc35
pid  66429
pkg_arch x86_64
pkg_epoch 0
pkg_fingerprint DB46 3971 9867 C58F
pkg_name python3-libs
pkg_release 1.fc35
pkg_vendor Fedora Project
pkg_version 3.10.5
reason socket.py:955:getaddrinfo:socket.gaierror: [Errno -2] Name or service not known
runlevel N 3
time 1660839771
type Python3
uid 0
username root
------------------------------------------------------------------------------------------------------------------------

it seems to be wrong to execute python -m http.server -b [::] 9444 command

> python -m http.server -b [::] 9444
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.10/http/server.py", line 1297, in <module>
    test(
  File "/usr/lib64/python3.10/http/server.py", line 1246, in test
    ServerClass.address_family, addr = _get_best_family(bind, port)
  File "/usr/lib64/python3.10/http/server.py", line 1229, in _get_best_family
    infos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

This command will be fine
> python -m http.server -b :: 9444
Serving HTTP on :: port 9444 (http://[::]:9444/) ...

**Comment by Mrcoolfuyu** [comment]
additonal info:

> systemd-coredump

Process 21095 (aria2c) of user 65534 dumped core.

Module linux-vdso.so.1 with build-id 79b231eec6dc2a9d2a07e4e0b6ef786f72ea9f7b
Module libcrypto.so.3 with build-id 1cc34c0eccf5c38e231a0926e6acc94da2d9bc94
Metadata for module libcrypto.so.3 owned by FDO found: {
	"type" : "rpm",
	"name" : "openssl",
	"version" : "3.0.5-1.fc36",
	"architecture" : "x86_64",
	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
}

Module libopensc.so.8 with build-id 99ba126a7317a9e3a2a474a4dd030018c07dd224
Metadata for module libopensc.so.8 owned by FDO found: {
	"type" : "rpm",
	"name" : "opensc",
	"version" : "0.22.0-6.fc36",
	"architecture" : "x86_64",
	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
}

Module opensc-pkcs11.so with build-id 7b401f1b5992dd2c9386242164e9195b04894e40
Metadata for module opensc-pkcs11.so owned by FDO found: {
	"type" : "rpm",
	"name" : "opensc",
	"version" : "0.22.0-6.fc36",
	"architecture" : "x86_64",
	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
}

Module p11-kit-trust.so with build-id e8fad97f56aec95b74768777c51d757920ac956c
Metadata for module p11-kit-trust.so owned by FDO found: {
	"type" : "rpm",
	"name" : "p11-kit",
	"version" : "0.24.1-2.fc36",
	"architecture" : "x86_64",
	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
}

Module libffi.so.8 with build-id bfe3659c787e4ca7b1c367d1353ce552da06f75d
Metadata for module libffi.so.8 owned by FDO found: {
	"type" : "rpm",
	"name" : "libffi",
	"version" : "3.4.2-8.fc36",
	"architecture" : "x86_64",
	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
}

Module ld-linux-x86-64.so.2 with build-id 8fa0bd5df5fa6fff60bb4cbdd753621d00f94dfc
Module libhogweed.so.6 with build-id 345872e1fd9fc345eccc8344049d028164796f36
Metadata for module libhogweed.so.6 owned by FDO found: {
	"type" : "rpm",
	"name" : "nettle",
	"version" : "3.8-1.fc36",
	"architecture" : "x86_64",
	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
}

Module libtasn1.so.6 with build-id fa9e8b533cabeec70ddfb953176fcf6b634d8faf
Metadata for module libtasn1.so.6 owned by FDO found: {
	"type" : "rpm",
	"name" : "libtasn1",
	"version" : "4.18.0-2.fc36",
	"architecture" : "x86_64",
	"osCpe" : "cpe:/o:fedoraproject:fedora:36"
}

Module libunistring.so.2 with build-id 08c59845b4a3798c8c8f780a26cb9eb59e212988
Stack trace of thread 21095:
#0  0x00007f7212c8ec4c __pthread_kill_implementation (libc.so.6 + 0x8ec4c)
#1  0x00007f7212c3e9c6 raise (libc.so.6 + 0x3e9c6)
#2  0x00007f7212c287f4 abort (libc.so.6 + 0x287f4)
#3  0x00007f72130d7dd0 _ZSt21__glibcxx_assert_failPKciS0_S0_ (libstdc++.so.6 + 0xd7dd0)
#4  0x0000556d5003ee24 _ZN5aria211GZipEncoder6encodeB5cxx11EPKhmi (aria2c + 0xb5e24)
#5  0x0000556d5003ee99 _ZN5aria211GZipEncoder3strB5cxx11Ev (aria2c + 0xb5e99)
#6  0x0000556d500291a1 _ZN5aria23rpc6toJsonERKNS0_11RpcResponseERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb (aria2c + 0xa01a1)
#7  0x0000556d500eed5f _ZN5aria221HttpServerBodyCommand19sendJsonRpcResponseERKNS_3rpc11RpcResponseERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (aria2c + 0x165d5f)
#8  0x0000556d500f2f35 _ZN5aria221HttpServerBodyCommand7executeEv (aria2c + 0x169f35)
#9  0x0000556d50084e6f _ZN5aria212_GLOBAL__N_114executeCommandERSt5dequeISt10unique_ptrINS_7CommandESt14default_deleteIS3_EESaIS6_EENS3_6STATUSE.lto_priv.0 (aria2c + 0xfbe6f)
#10 0x0000556d4ffdc9d1 main (aria2c + 0x539d1)
#11 0x00007f7212c29550 __libc_start_call_main (libc.so.6 + 0x29550)
#12 0x00007f7212c29609 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29609)
#13 0x0000556d4ffe09c5 _start (aria2c + 0x579c5)
ELF object binary architecture: AMD x86-64
CODE_FILE
../src/coredump/coredump.c
CODE_FUNC
submit_coredump
CODE_LINE
900
COREDUMP_CGROUP
/system.slice/aria2.service
COREDUMP_CMDLINE
/usr/local/bin/aria2c --conf-path=/etc/aria2/aria2.conf -D
COREDUMP_COMM
aria2c
COREDUMP_CWD
/
COREDUMP_ENVIRON
LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/ LOGNAME=nobody USER=nobody INVOCATION_ID=4c30b5bba6004e8dba324349ce0d5625 JOURNAL_STREAM=8:117565 SYSTEMD_EXEC_PID=21094
COREDUMP_EXE
/usr/bin/aria2c
COREDUMP_FILENAME
/var/lib/systemd/coredump/core.aria2c.65534.efb226a9819249218571ee9b3ed17f33.21095.1661231596000000.zst
COREDUMP_GID
65534
COREDUMP_HOSTNAME
NAS
COREDUMP_OPEN_FDS
[没有数据]
COREDUMP_PACKAGE_JSON
{"elfType":"coredump","elfArchitecture":"AMD x86-64","libcrypto.so.3":{"type":"rpm","name":"openssl","version":"3.0.5-1.fc36","architecture":"x86_64","osCpe":"cpe:/o:fedoraproject:fedora:36","buildId":"1cc34c0eccf5c38e231a0926e6acc94da2d9bc94"},"libopensc.so.8":{"type":"rpm","name":"opensc","version":"0.22.0-6.fc36","architecture":"x86_64","osCpe":"cpe:/o:fedoraproject:fedora:36","buildId":"99ba126a7317a9e3a2a474a4dd030018c07dd224"},"opensc-pkcs11.so":{"type":"rpm","name":"opensc","version":"0.22.0-6.fc36","architecture":"x86_64","osCpe":"cpe:/o:fedoraproject:fedora:36","buildId":"7b401f1b5992dd2c9386242164e9195b04894e40"},"p11-kit-trust.so":{"type":"rpm","name":"p11-kit","version":"0.24.1-2.fc36","architecture":"x86_64","osCpe":"cpe:/o:fedoraproject:fedora:36","buildId":"e8fad97f56aec95b74768777c51d757920ac956c"},"libffi.so.8":{"type":"rpm","name":"libffi","version":"3.4.2-8.fc36","architecture":"x86_64","osCpe":"cpe:/o:fedoraproject:fedora:36","buildId":"bfe3659c787e4ca7b1c367d1353ce552da06f75d"},"libhogweed.so.6":{"type":"rpm","name":"nettle","version":"3.8-1.fc36","architecture":"x86_64","osCpe":"cpe:/o:fedoraproject:fedora:36","buildId":"345872e1fd9fc345eccc8344049d028164796f36"},"libtasn1.so.6":{"type":"rpm","name":"libtasn1","version":"4.18.0-2.fc36","architecture":"x86_64","osCpe":"cpe:/o:fedoraproject:fedora:36","buildId":"fa9e8b533cabeec70ddfb953176fcf6b634d8faf"}}
COREDUMP_PID
21095
COREDUMP_PROC_CGROUP
0::/system.slice/aria2.service
COREDUMP_PROC_LIMITS
Limit Soft Limit Hard Limit Units Max cpu time unlimited unlimited seconds Max file size unlimited unlimited bytes Max data size unlimited unlimited bytes Max stack size 8388608 unlimited bytes Max core file size unlimited unlimited bytes Max resident set unlimited unlimited bytes Max processes 30385 30385 processes Max open files 1024 524288 files Max locked memory 8388608 8388608 bytes Max address space unlimited unlimited bytes Max file locks unlimited unlimited locks Max pending signals 30385 30385 signals Max msgqueue size 819200 819200 bytes Max nice priority 0 0 Max realtime priority 0 0 Max realtime timeout unlimited unlimited us
COREDUMP_PROC_MAPS
556d4ff89000-556d4ffb0000 r--p 00000000 fd:00 101280463 /usr/bin/aria2c 556d4ffb0000-556d5015b000 r-xp 00027000 fd:00 101280463 /usr/bin/aria2c 556d5015b000-556d501e0000 r--p 001d2000 fd:00 101280463 /usr/bin/aria2c 556d501e1000-556d501ee000 r--p 00257000 fd:00 101280463 /usr/bin/aria2c 556d501ee000-556d501ef000 rw-p 00264000 fd:00 101280463 /usr/bin/aria2c 556d501ef000-556d501f2000 rw-p 00000000 00:00 0 556d50d04000-556d50d66000 rw-p 00000000 00:00 0 [heap] 556d50d66000-556d5255a000 rw-p 00000000 00:00 0 [heap] 7f7204c00000-7f7204cad000 r--p 00000000 fd:00 1873985 /usr/lib64/libcrypto.so.3.0.5 7f7204cad000-7f7204f02000 r-xp 000ad000 fd:00 1873985 /usr/lib64/libcrypto.so.3.0.5 7f7204f02000-7f7204fcb000 r--p 00302000 fd:00 1873985 /usr/lib64/libcrypto.so.3.0.5 7f7204fcb000-7f7204fcc000 ---p 003cb000 fd:00 1873985 /usr/lib64/libcrypto.so.3.0.5 7f7204fcc000-7f7205022000 r--p 003cb000 fd:00 1873985 /usr/lib64/libcrypto.so.3.0.5 7f7205022000-7f7205025000 rw-p 00421000 fd:00 1873985 /usr/lib64/libcrypto.so.3.0.5 7f7205025000-7f7205028000 rw-p 00000000 00:00 0 7f7205205000-7f7205222000 r--p 00000000 fd:00 155717 /usr/lib64/libopensc.so.8.0.0 7f7205222000-7f720536c000 r-xp 0001d000 fd:00 155717 /usr/lib64/libopensc.so.8.0.0 7f720536c000-7f72053e4000 r--p 00167000 fd:00 155717 /usr/lib64/libopensc.so.8.0.0 7f72053e4000-7f72053e5000 ---p 001df000 fd:00 155717 /usr/lib64/libopensc.so.8.0.0 7f72053e5000-7f72053f3000 r--p 001df000 fd:00 155717 /usr/lib64/libopensc.so.8.0.0 7f72053f3000-7f72053fb000 rw-p 001ed000 fd:00 155717 /usr/lib64/libopensc.so.8.0.0 7f72053fb000-7f7205400000 rw-p 00000000 00:00 0 7f7205400000-7f72129b7000 r--p 00000000 fd:00 33612621 /usr/lib/locale/locale-archive 7f7212a48000-7f7212a5a000 r--p 00000000 fd:00 393330 /usr/lib64/libunistring.so.2.2.0 7f7212a5a000-7f7212a9c000 r-xp 00012000 fd:00 393330 /usr/lib64/libunistring.so.2.2.0 7f7212a9c000-7f7212bfa000 r--p 00054000 fd:00 393330 /usr/lib64/libunistring.so.2.2.0 7f7212bfa000-7f7212bfb000 ---p 001b2000 fd:00 393330 /usr/lib64/libunistring.so.2.2.0 7f7212bfb000-7f7212bff000 r--p 001b2000 fd:00 393330 /usr/lib64/libunistring.so.2.2.0 7f7212bff000-7f7212c00000 rw-p 001b6000 fd:00 393330 /usr/lib64/libunistring.so.2.2.0 7f7212c00000-7f7212c28000 r--p 00000000 fd:00 227038 /usr/lib64/libc.so.6 7f7212c28000-7f7212d9c000 r-xp 00028000 fd:00 227038 /usr/lib64/libc.so.6 7f7212d9c000-7f7212df4000 r--p 0019c000 fd:00 227038 /usr/lib64/libc.so.6 7f7212df4000-7f7212df8000 r--p 001f3000 fd:00 227038 /usr/lib64/libc.so.6 7f7212df8000-7f7212dfa000 rw-p 001f7000 fd:00 227038 /usr/lib64/libc.so.6 7f7212dfa000-7f7212e02000 rw-p 00000000 00:00 0 7f7212e58000-7f7212e61000 r--p 00000000 fd:00 155722 /usr/lib64/opensc-pkcs11.so 7f7212e61000-7f7212e7f000 r-xp 00009000 fd:00 155722 /usr/lib64/opensc-pkcs11.so 7f7212e7f000-7f7212e8b000 r--p 00027000 fd:00 155722 /usr/lib64/opensc-pkcs11.so 7f7212e8b000-7f7212e8c000 ---p 00033000 fd:00 155722 /usr/lib64/opensc-pkcs11.so 7f7212e8c000-7f7212e8d000 r--p 00033000 fd:00 155722 /usr/lib64/opensc-pkcs11.so 7f7212e8d000-7f7212e91000 rw-p 00034000 fd:00 155722 /usr/lib64/opensc-pkcs11.so 7f7212e91000-7f7212e9c000 r--p 00000000 fd:00 67266779 /usr/lib64/pkcs11/p11-kit-trust.so 7f7212e9c000-7f7212eb4000 r-xp 0000b000 fd:00 67266779 /usr/lib64/pkcs11/p11-kit-trust.so
COREDUMP_PROC_MOUNTINFO
1063 1034 253:0 / / rw,relatime shared:518 master:1 - xfs /dev/mapper/fedora-root rw,attr2,inode64,logbufs=8,logbsize=32k,noquota 1064 1063 0:23 / /sys rw,nosuid,nodev,noexec,relatime shared:545 master:2 - sysfs sysfs rw 1065 1064 0:6 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:546 master:3 - securityfs securityfs rw 1066 1064 0:27 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime shared:547 master:4 - cgroup2 cgroup2 rw,nsdelegate,memory_recursiveprot 1067 1064 0:28 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:548 master:5 - pstore pstore rw 1068 1064 0:29 / /sys/fs/bpf rw,nosuid,nodev,noexec,relatime shared:549 master:6 - bpf bpf rw,mode=700 1069 1064 0:7 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime shared:550 master:15 - debugfs debugfs rw 1070 1069 0:12 / /sys/kernel/debug/tracing rw,nosuid,nodev,noexec,relatime shared:551 master:371 - tracefs tracefs rw 1071 1064 0:12 / /sys/kernel/tracing rw,nosuid,nodev,noexec,relatime shared:552 master:16 - tracefs tracefs rw 1072 1064 0:33 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime shared:553 master:17 - fusectl fusectl rw 1073 1064 0:34 / /sys/kernel/config rw,nosuid,nodev,noexec,relatime shared:554 master:18 - configfs configfs rw 1074 1063 0:5 / /dev rw,nosuid shared:555 master:7 - devtmpfs devtmpfs rw,size=4096k,nr_inodes=1048576,mode=755,inode64 1075 1074 0:24 / /dev/shm rw,nosuid,nodev shared:556 master:8 - tmpfs tmpfs rw,inode64 1076 1074 0:25 / /dev/pts rw,nosuid,noexec,relatime shared:557 master:9 - devpts devpts rw,gid=5,mode=620,ptmxmode=000 1077 1074 0:20 / /dev/mqueue rw,nosuid,nodev,noexec,relatime shared:558 master:13 - mqueue mqueue rw 1078 1074 0:32 / /dev/hugepages rw,relatime shared:559 master:14 - hugetlbfs hugetlbfs rw,pagesize=2M 1079 1063 0:26 / /run rw,nosuid,nodev shared:560 master:10 - tmpfs tmpfs rw,size=1564504k,nr_inodes=819200,mode=755,inode64 1081 1079 0:47 / /run/user/0 rw,nosuid,nodev,relatime shared:561 master:441 - tmpfs tmpfs rw,size=782248k,nr_inodes=195562,mode=700,inode64 1082 1063 0:22 / /proc rw,nosuid,nodev,noexec,relatime shared:564 master:11 - proc proc rw 1083 1082 0:30 / /proc/sys/fs/binfmt_misc rw,relatime shared:565 master:12 - autofs systemd-1 rw,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=18615 1084 1082 0:36 / /proc/fs/nfsd rw,relatime shared:566 master:20 - nfsd nfsd rw 1085 1063 0:37 / /tmp rw,nosuid,nodev shared:567 master:38 - tmpfs tmpfs rw,size=3911260k,nr_inodes=1048576,inode64 1086 1063 8:17 / /boot rw,relatime shared:569 master:45 - ext4 /dev/sdb1 rw 1087 1063 253:3 / /home rw,relatime shared:570 master:47 - xfs /dev/mapper/fedora-home rw,attr2,inode64,logbufs=8,logbsize=32k,noquota 1088 1063 253:2 / /data2 rw,relatime shared:571 master:49 - ext4 /dev/mapper/vgroup0-lvol0 rw,stripe=64 1089 1063 8:33 / /data1 rw,relatime shared:572 master:51 - ext4 /dev/sdc1 rw 1090 1063 8:1 / /data3 rw,relatime shared:573 master:53 - ext4 /dev/sda1 rw 1091 1063 0:44 / /var/lib/nfs/rpc_pipefs rw,relatime shared:574 master:232 - rpc_pipefs sunrpc rw 1080 1079 0:26 /systemd/inaccessible/dir /run/credentials ro,nosuid,nodev,noexec shared:562 master:10 - tmpfs tmpfs rw,size=1564504k,nr_inodes=819200,mode=755,inode64 1092 1079 0:26 /systemd/propagate/aria2.service /run/systemd/incoming ro,nosuid,nodev master:10 - tmpfs tmpfs rw,size=1564504k,nr_inodes=819200,mode=755,inode64 1093 1085 0:37 /systemd-private-efb226a9819249218571ee9b3ed17f33-aria2.service-T3ruMS/tmp /tmp rw,nosuid,nodev shared:568 master:38 - tmpfs tmpfs rw,size=3911260k,nr_inodes=1048576,inode64 1094 1063 253:0 /var/tmp/systemd-private-efb226a9819249218571ee9b3ed17f33-aria2.service-UkE3i5/tmp /var/tmp rw,relatime shared:575 master:1 - xfs /dev/mapper/fedora-root rw,attr2,inode64,logbufs=8,logbsize=32k,noquota
COREDUMP_PROC_STATUS
Name: aria2c Umask: 0022 State: S (sleeping) Tgid: 21095 Ngid: 0 Pid: 21095 PPid: 1 TracerPid: 0 Uid: 65534 65534 65534 65534 Gid: 65534 65534 65534 65534 FDSize: 256 Groups: 65534 NStgid: 21095 NSpid: 21095 NSpgid: 21095 NSsid: 21095 VmPeak: 272592 kB VmSize: 268712 kB VmLck: 0 kB VmPin: 0 kB VmHWM: 39900 kB VmRSS: 36208 kB RssAnon: 26028 kB RssFile: 10180 kB RssShmem: 0 kB VmData: 25288 kB VmStk: 132 kB VmExe: 1708 kB VmLib: 12488 kB VmPTE: 148 kB VmSwap: 0 kB HugetlbPages: 0 kB CoreDumping: 1 THP_enabled: 1 Threads: 1 SigQ: 0/30385 SigPnd: 0000000000000000 ShdPnd: 0000000000000000 SigBlk: 0000000000000000 SigIgn: 0000000000011000 SigCgt: 0000000000004003 CapInh: 0000000000000000 CapPrm: 0000000000000000 CapEff: 0000000000000000 CapBnd: 000001ffffffffff CapAmb: 0000000000000000 NoNewPrivs: 0 Seccomp: 0 Seccomp_filters: 0 Speculation_Store_Bypass: thread vulnerable SpeculationIndirectBranch: conditional enabled Cpus_allowed: f Cpus_allowed_list: 0-3 Mems_allowed: 00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001 Mems_allowed_list: 0 voluntary_ctxt_switches: 16309 nonvoluntary_ctxt_switches: 486
COREDUMP_RLIMIT
18446744073709551615
COREDUMP_ROOT
/
COREDUMP_SIGNAL
6
COREDUMP_SIGNAL_NAME
SIGABRT
COREDUMP_SLICE
system.slice
COREDUMP_TIMESTAMP
1661231596000000
COREDUMP_UID
65534
COREDUMP_UNIT
aria2.service
MESSAGE_ID
fc2e22bc6ee647b6b90729ab34a250b1
PRIORITY
2
SYSLOG_IDENTIFIER
systemd-coredump
_BOOT_ID
efb226a9819249218571ee9b3ed17f33
_CAP_EFFECTIVE
0
_CMDLINE
/usr/lib/systemd/systemd-coredump
_COMM
systemd-coredum
_EXE
/usr/lib/systemd/systemd-coredump
_GID
65534
_HOSTNAME
NAS
_MACHINE_ID
4a88f8de5efa4094a1f462c4a10bd7f3
_PID
22782
_SELINUX_CONTEXT
kernel
_SOURCE_REALTIME_TIMESTAMP
1661231596346702
_SYSTEMD_CGROUP
/system.slice/system-systemd\x2dcoredump.slice/systemd-coredump@1-22781-0.service
_SYSTEMD_INVOCATION_ID
82424a1975524f849eebea0069896d44
_SYSTEMD_SLICE
system-systemd\x2dcoredump.slice
_SYSTEMD_UNIT
systemd-coredump@1-22781-0.service
_TRANSPORT
journal
_UID
65534
__CURSOR
s=4baf3a631b9a4503abef6968b7a647ed;i=846dde;b=efb226a9819249218571ee9b3ed17f33;m=46edc6b9;t=5e6e19f309e0a;x=8cca05aef2ec507e
__MONOTONIC_TIMESTAMP
1189988025
__REALTIME_TIMESTAMP
1661231596346890

**Comment by netllama** [comment]
Any chance a new release is going to come out soon with a fix for this issue?

**Comment by gbcox** [comment]
I've been getting the same thing also for months:

Oct 20 11:38:23 charon audit[44280]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=kernel pid=44280 comm="aria2c" exe="/usr/bin/aria2c" sig=6 res=1
Oct 20 11:38:23 charon systemd-coredump[55052]: Process 44280 (aria2c) of user 1000 dumped core.
                                                Module aria2c from rpm aria2-1.36.0-5.fc39.x86_64
                                                #4  0x00005567fe730e1c _ZN5aria211GZipEncoder6encodeB5cxx11EPKhmi (aria2c + 0xc5e1c)
                                                #5  0x00005567fe730e9e _ZN5aria211GZipEncoder3strB5cxx11Ev (aria2c + 0xc5e9e)
                                                #6  0x00005567fe7178fe _ZN5aria23rpc11toJsonBatchERKSt6vectorINS0_11RpcResponseESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb (aria2c + 0xac8fe)
                                                #7  0x00005567fe7e6583 _ZN5aria221HttpServerBodyCommand7executeEv (aria2c + 0x17b583)
                                                #8  0x00005567fe775cf9 _ZN5aria212_GLOBAL__N_114executeCommandERSt5dequeISt10unique_ptrINS_7CommandESt14default_deleteIS3_EESaIS6_EENS3_6STATUSE.lto_priv.0 (aria2c + 0x10acf9)
                                                #9  0x00005567fe6c90b9 main (aria2c + 0x5e0b9)
                                                #12 0x00005567fe6cce95 _start (aria2c + 0x61e95)
Oct 20 11:38:23 charon systemd[1]: aria2c.service: Main process exited, code=dumped, status=6/ABRT
Oct 20 11:38:23 charon audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=aria2c comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Oct 20 11:38:23 charon systemd[1]: aria2c.service: Failed with result 'core-dump'.
Oct 20 11:38:23 charon systemd[1]: aria2c.service: Consumed 53.218s CPU time.
Oct 20 11:38:26 charon abrt-notification[55105]: Process 1360 (aria2c) crashed in __gnu_debug::_Safe_sequence_base::_M_get_mutex()()
