### ISSUE TITLE
C-Ares 404 Not Found

### ISSUE THREAD

**Issue by camenduru** [aria2/aria2#2038]
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1ubuntu0.1_amd64.deb  404  Not Found [IP: 185.125.190.36 80]

c-ares is a C library that performs DNS requests and name resolution asynchronously.

any workaround?

deleted
http://security.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1ubuntu0.1_amd64.deb

live
http://security.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1ubuntu0.2_amd64.deb

**Comment by camenduru** [comment]
my workaround

```
!wget http://security.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1ubuntu0.2_amd64.deb -O /content/libc-ares2_1.15.0-1ubuntu0.1_amd64.deb
!apt-get -y install /content/libc-ares2_1.15.0-1ubuntu0.1_amd64.deb
```

**Comment by JanDiederich** [comment]
> my workaround
> 
> ```
> !wget http://security.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1ubuntu0.2_amd64.deb -O /content/libc-ares2_1.15.0-1ubuntu0.1_amd64.deb
> !apt-get -y install /content/libc-ares2_1.15.0-1ubuntu0.1_amd64.deb
> ```
> 
> or just
> 
> `!apt -y update -qq`

Thanks, had the same problem. My Ubuntu package dependency wanted the 0.2 version, but the server had only the later 0.3 left.
