### ISSUE TITLE
how to download file on smb server ?

### ISSUE THREAD

**Issue by shishirong** [aria2/aria2#2066]

**Comment by qianbinbin** [comment]
You can set up an HTTP/FTP service, or check out other tools like `rsync`.

**Comment by shishirong** [comment]
> You can set up an HTTP/FTP service, or check out other tools like `rsync`.

aria2 do not support smb protocol?

**Comment by qianbinbin** [comment]
> aria2 do not support smb protocol?

In the DESCRIPTION it reads that

> The supported protocols are HTTP(S), FTP, SFTP, BitTorrent, and Metalink.

So I guess no.
