### ISSUE TITLE
How to enable  "force-sequential" option by using  rpc server request ?

### ISSUE THREAD

**Issue by tabebqena** [aria2/aria2#211]
I need to do the following command by rpc :

```
aria2c -P -Z 'https://www.host.com/audio[000-010].mp3'
```

It add 10 download. as -p = Parametrized-uri , -Z = force-sequential
So I write the following python 2.7 code:

```
import xmlrpclib  
from subprocess import call 

call(['aria2c' , '--daemon' , '--enable-rpc=true' ] ) 
time.sleep(2)
s = xmlrpclib.ServerProxy('http://localhost:6800/rpc'  , allow_none=True)
x = s.aria2.addUri( ['https://www.host.com/audio[000-010].mp3'] , { "parametrized-uri":"true" , "force-sequential":"true"}  )
```

but it add one file(instead of 10) and add the 10 uris as mirror for that file as given by this code : 

```
print s.aria2.tellStatus( x)
```

the result : 

> {'files': [{'index': '1', 'selected': 'true', 'length': '0', 'completedLength': '0', 'path': '', 'uris': [{'status': 'used', 'uri': 'https://www.host.com/audio000.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio001.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio002.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio003.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio004.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio005.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio006.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio007.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio008.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio009.mp3'}, {'status': 'waiting', 'uri': 'https://www.host.com/audio010.mp3'}]}], 'numPieces': '0', 'downloadSpeed': '0', 'pieceLength': '1048576', 'uploadSpeed': '0', 'connections': '1', 'status': 'active', 'gid': 'cb58a480b299fb58', 'completedLength': '0', 'uploadLength': '0', 'dir': '$HOME', 'totalLength': '0'}

despite that  : 

> -Z, --force-sequential[=true|false] Fetch URIs in the command-line sequentially
>                               and download each URI in a separate session, like
>                               the usual command-line download utilities.

aria2 version 1.17.0 , installed by apt-get

**Comment by bomdia** [comment]
@tatsuhiro-t there is some motivation to exclude this option from the rpc api?
like its a very important feature and i don't see any reason to make it unavailable to rpc, and if there is a motivation o whatsoever should at least be reported in the documentation,
i don't know the codebase but i think that adding this binding to the rpc api should be quite easy
