### ISSUE TITLE
error: use of undeclared identifier 'INFO_HASH_LENGTH'

### ISSUE THREAD

**Issue by DevonTM** [aria2/aria2#2128]
I encountered this error when building with the `--disable-bittorrent` flag with the commit 3330110cafebd86b231d860cddea2f36ca8e755c.
> make  all-recursive
make[1]: Entering directory '/home/acer/aria2/aria2'
Making all in po
make[2]: Entering directory '/home/acer/aria2/aria2/po'
make[2]: Leaving directory '/home/acer/aria2/aria2/po'
Making all in lib
make[2]: Entering directory '/home/acer/aria2/aria2/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/acer/aria2/aria2/lib'
Making all in deps
make[2]: Entering directory '/home/acer/aria2/aria2/deps'
make[3]: Entering directory '/home/acer/aria2/aria2/deps'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/acer/aria2/aria2/deps'
make[2]: Leaving directory '/home/acer/aria2/aria2/deps'
Making all in src
make[2]: Entering directory '/home/acer/aria2/aria2/src'
Making all in includes
make[3]: Entering directory '/home/acer/aria2/aria2/src/includes'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/acer/aria2/aria2/src/includes'
make[3]: Entering directory '/home/acer/aria2/aria2/src'
  CXX      main.o
  CXX      A2STR.lo
  CXX      AbstractAuthResolver.lo
  CXX      AbstractCommand.lo
  CXX      AbstractDiskWriter.lo
  CXX      AbstractHttpServerResponseCommand.lo
  CXX      AbstractOptionHandler.lo
  CXX      AbstractProxyRequestCommand.lo
  CXX      AbstractProxyResponseCommand.lo
  CXX      AbstractSingleDiskAdaptor.lo
  CXX      AdaptiveFileAllocationIterator.lo
  CXX      AdaptiveURISelector.lo
  CXX      AuthConfig.lo
  CXX      AuthConfigFactory.lo
  CXX      AutoSaveCommand.lo
  CXX      BackupIPv4ConnectCommand.lo
  CXX      base32.lo
  CXX      bitfield.lo
  CXX      BitfieldMan.lo
  CXX      BufferedFile.lo
  CXX      ByteArrayDiskWriter.lo
  CXX      CheckIntegrityCommand.lo
  CXX      CheckIntegrityDispatcherCommand.lo
  CXX      CheckIntegrityEntry.lo
  CXX      Checksum.lo
  CXX      ChecksumCheckIntegrityEntry.lo
  CXX      ChunkChecksum.lo
  CXX      ChunkedDecodingStreamFilter.lo
  CXX      ColorizedStream.lo
  CXX      Command.lo
  CXX      ConnectCommand.lo
  CXX      console.lo
  CXX      ConsoleStatCalc.lo
  CXX      ContentTypeRequestGroupCriteria.lo
  CXX      Context.lo
  CXX      ContextAttribute.lo
  CXX      Cookie.lo
  CXX      CookieStorage.lo
  CXX      cookie_helper.lo
  CXX      CreateRequestCommand.lo
  CXX      CUIDCounter.lo
  CXX      DefaultAuthResolver.lo
  CXX      DefaultBtProgressInfoFile.lo
  CXX      DefaultDiskWriter.lo
  CXX      DefaultDiskWriterFactory.lo
  CXX      DefaultPieceStorage.lo
DefaultBtProgressInfoFile.cc:267:24: error: use of undeclared identifier 'INFO_HASH_LENGTH'
  267 |   if (infoHashLength > INFO_HASH_LENGTH ||
      |                        ^
DefaultBtProgressInfoFile.cc:268:26: error: use of undeclared identifier 'INFO_HASH_LENGTH'
  268 |       (infoHashLength != INFO_HASH_LENGTH && infoHashCheckEnabled)) {
      |                          ^
DefaultBtProgressInfoFile.cc:272:31: error: use of undeclared identifier 'INFO_HASH_LENGTH'
  272 |     std::array<unsigned char, INFO_HASH_LENGTH> savedInfoHash;
      |                               ^
3 errors generated.
make[3]: *** [Makefile:2638: DefaultBtProgressInfoFile.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/acer/aria2/aria2/src'
make[2]: *** [Makefile:2679: all-recursive] Error 1
make[2]: Leaving directory '/home/acer/aria2/aria2/src'
make[1]: *** [Makefile:557: all-recursive] Error 1
make[1]: Leaving directory '/home/acer/aria2/aria2'
make: *** [Makefile:468: all] Error 2

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  #2129 fixes this.
