### ISSUE TITLE
Displays garbled code when downloading Chinese paths

### ISSUE THREAD

**Issue by fgr178707** [aria2/aria2#2141]
![image](https://github.com/aria2/aria2/assets/109357981/9ccc6f31-05c3-4a54-a46d-3fbbda2ec7f6)

`aria2c --enable-rpc --rpc-listen-port=6801 --header="Referer":"https://www.bilibili.com" --dir=F:\动漫\其他\lux  --split=8 `

**Comment by IAALAI** [comment]
这个问题大概率是powershell的问题，不是aria的问题

**Comment by fgr178707** [comment]
> powershell

问题是下载文件时候创建的文件夹也是乱码

**Comment by IAALAI** [comment]
> > powershell
> 
> 问题是下载文件时候创建的文件夹也是乱码

我用的时候从来没出现这个问题

这里显示的是你输上去的就是乱码的，这和aria都没有关系

**Comment by fgr178707** [comment]
> > > powershell
> > 
> > 
> > 问题是下载文件时候创建的文件夹也是乱码
> 
> 我用的时候从来没出现这个问题
> 
> 这里显示的是你输上去的就是乱码的，这和aria都没有关系

可否将你的那一份打包发我一下

**Comment by IAALAI** [comment]
可以整个都打包给你，但是我感觉意义不大。我看你在shell的文件名都是乱码的。

**Comment by IAALAI** [comment]
[aria2.zip](https://github.com/aria2/aria2/files/13415729/aria2.zip)
我的也就是`Releases`里下的

**Comment by fgr178707** [comment]
> [aria2.zip](https://github.com/aria2/aria2/files/13415729/aria2.zip) 我的也就是`Releases`里下的

兄弟你这个怎么用啊
双击aria2.ps1没反应

**Comment by fgr178707** [comment]
@IAALAI 
![image](https://github.com/aria2/aria2/assets/109357981/30fb9e50-b78b-44d7-9a3b-10565c8a67fd)
我用注册表改了一下强制使用  65001 还是不行中文还是乱码

**Comment by 104979058** [comment]
--dir="F:\动漫\其他\lux"
记住加符号.
