### ISSUE TITLE
How to use MSVC to compile aria2？

### ISSUE THREAD

**Issue by izdbrave** [aria2/aria2#2163]
I hope to use the libaria2 dynamic library in programs compiled with MSVC, but the official compilation method is to cross-compile the libaria2 dynamic library using gcc in Linux. Since the dynamic library compiled by gcc is not compatible with MSVC, I cannot use it. Is there a way to compile it using MSVC on Windows?

**Comment by Gaoyifei1011** [comment]
> I hope to use the libaria2 dynamic library in programs compiled with MSVC, but the official compilation method is to cross-compile the libaria2 dynamic library using gcc in Linux. Since the dynamic library compiled by gcc is not compatible with MSVC, I cannot use it. Is there a way to compile it using MSVC on Windows?

You could see reference Mile.Aria2
![image](https://github.com/aria2/aria2/assets/49179966/cc5a6dac-ecf2-489d-89da-e2acb27b3238)

**Comment by izdbrave** [comment]
Thansk a lot!

> > I hope to use the libaria2 dynamic library in programs compiled with MSVC, but the official compilation method is to cross-compile the libaria2 dynamic library using gcc in Linux. Since the dynamic library compiled by gcc is not compatible with MSVC, I cannot use it. Is there a way to compile it using MSVC on Windows?
> 
> You could see reference Mile.Aria2 ![image](https://private-user-images.githubusercontent.com/49179966/299855924-cc5a6dac-ecf2-489d-89da-e2acb27b3238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjcwMTEsIm5iZiI6MTcxMDgyNjcxMSwicGF0aCI6Ii80OTE3OTk2Ni8yOTk4NTU5MjQtY2M1YTZkYWMtZWNmMi00ODlkLTg5ZGEtZTJhY2IyN2IzMjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1MzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZmYyZTRhZTE4NjdlZDc3NWViMTU3NmI5ZDMwNTM0ZDJlZjVmMWZlNDE2MjAyMjRiZGJhOTFlNWE2MzVjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OyBsWy9PAollfWMjizNml-bCPt2i1w0BmNbzTzW5YEk)

Thansk a lot!

**Comment by izdbrave** [comment]
> > I hope to use the libaria2 dynamic library in programs compiled with MSVC, but the official compilation method is to cross-compile the libaria2 dynamic library using gcc in Linux. Since the dynamic library compiled by gcc is not compatible with MSVC, I cannot use it. Is there a way to compile it using MSVC on Windows?
> 
> You could see reference Mile.Aria2 ![image](https://private-user-images.githubusercontent.com/49179966/299855924-cc5a6dac-ecf2-489d-89da-e2acb27b3238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjcwMTEsIm5iZiI6MTcxMDgyNjcxMSwicGF0aCI6Ii80OTE3OTk2Ni8yOTk4NTU5MjQtY2M1YTZkYWMtZWNmMi00ODlkLTg5ZGEtZTJhY2IyN2IzMjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1MzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZmYyZTRhZTE4NjdlZDc3NWViMTU3NmI5ZDMwNTM0ZDJlZjVmMWZlNDE2MjAyMjRiZGJhOTFlNWE2MzVjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OyBsWy9PAollfWMjizNml-bCPt2i1w0BmNbzTzW5YEk)

Thanks a lot!
