### ISSUE TITLE
Aria2 config not being respected.

### ISSUE THREAD

**Issue by zQueal** [aria2/aria2#2248]
In my `aria2.conf` I have `disable-ipv6=true`. Grabbing YouTube videos (via yt-dlp) fail with this error message;

> Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.

Changing the command string to `yt-dlp -f {whatever} {video_url} --downloader aria2c --downloader-args --disable-ipv6=true` seems to work just fine.

I can only conclude that aria is not respecting the entire config file as the rest of my config options are respected without issue.

**Comment by zQueal** [comment]
It seems like another fix to this is to use `yt-dlp -4`, however, I feel like since the download action is being offloaded to aria, it should respect ipv4 only because its explicitly set in the config.

Am I wrong?

**Comment by thisisgk** [comment]
Ask yt-dlp the reason https://github.com/yt-dlp/yt-dlp/issues/7404 .

**Comment by zQueal** [comment]
Seems dubious of them.

Either way, thanks.
