### ISSUE TITLE
[NOTICE] No file matched with your preference. No files to download.

### ISSUE THREAD

**Issue by pro-sumer** [aria2/aria2#2267]
To optimize downloading Apple firmware images I have created a script that generates a [metalink](http://www.metalinker.org) file that I use with aria2 to download those images from the Apple servers. This has worked fine for months, but with the release of iOS 18.1.1 aria2 suddenly "failed" with this error:

```
[NOTICE] No file matched with your preference.
No files to download.
```

I then tried iOS 18.1 (which worked a couple of weeks ago), but that gave the same error, even though I did not change my script or aria2.

Here's an example of such a metalink file:

```
<?xml version="1.0"?>
<metalink version="3.0" xmlns="https://www.metalinker.org/">
  <files>
    <file name="iPhone16,2_18.1_22B83_Restore.ipsw">
      <verification>
        <hash type="sha1">eb8c56541e7c5db6f04a81a41ce2f58ac4f8df01</hash>
        <hash type="md5">ba2b1a9547b87f4702f542953355c173</hash>
      </verification>
      <resources>
        <url type="http">https://updates.cdn-apple.com/2024FallFCS/fullrestores/072-12616/7E6955BD-A1E8-45DA-BBE4-10819FDF1F7E/iPhone16,2_18.1_22B83_Restore.ipsw</url>
      </resources>
    </file>
  </files>
</metalink>
```

Why do I get this notice/error and does aria2 no longer download anything?

(Note that the URL is correct; if I open that in a browser, the browser starts downloading the IPSW file)

**Comment by zeromake** [comment]
aria2 metalink v3 support  xmlns is `http://www.metalinker.org/`, but now metalink v3 xmlns is `https://www.metalinker.org/` you metalink file is new metalink v3 xmlns

**Comment by zeromake** [comment]
you can xmlns change to `http://www.metalinker.org/`, or upgrade metalink v4

**Comment by zeromake** [comment]
v3 old:
```xml
<?xml version="1.0"?>
<metalink version="3.0" xmlns="http://www.metalinker.org/">
  <files>
    <file name="iPhone16,2_18.1_22B83_Restore.ipsw">
      <verification>
        <hash type="sha1">eb8c56541e7c5db6f04a81a41ce2f58ac4f8df01</hash>
        <hash type="md5">ba2b1a9547b87f4702f542953355c173</hash>
      </verification>
      <resources>
        <url type="http">https://updates.cdn-apple.com/2024FallFCS/fullrestores/072-12616/7E6955BD-A1E8-45DA-BBE4-10819FDF1F7E/iPhone16,2_18.1_22B83_Restore.ipsw</url>
      </resources>
    </file>
  </files>
</metalink>

```
v4:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="iPhone16,2_18.1_22B83_Restore.ipsw">
    <identity>iPhone16,2_18.1_22B83_Restore</identity>
    <size>8980572559</size>
    <hash type="sha1">eb8c56541e7c5db6f04a81a41ce2f58ac4f8df01</hash>
    <hash type="md5">ba2b1a9547b87f4702f542953355c173</hash>
    <url priority="1">https://updates.cdn-apple.com/2024FallFCS/fullrestores/072-12616/7E6955BD-A1E8-45DA-BBE4-10819FDF1F7E/iPhone16,2_18.1_22B83_Restore.ipsw</url>
  </file>
</metalink>
```

**Comment by pro-sumer** [comment]
Thank you for solving my "mystery"! I totally missed the secure HTTP (`https`) versus HTTP (`http`)...

Got it working again indeed!

(Migrated to v4 anyway; that was due a long time after all)
