### ISSUE TITLE
'std::length_error'

### ISSUE THREAD

**Issue by dhanjit** [aria2/aria2#265]
$ aria2c http://i.imgur.com/GKYwpLr.png
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
Aborted

aria2 version 1.18.7
linux 3.15.5-2-ARCH

**Comment by milolou** [comment]
It seems that it's ok to set a proxy,as long as we configure the aria2 with the same proxy value as the environment,and the computer should be connected to the proxy while downloading.
