### ISSUE TITLE
Disable SSL3 (by default)

### ISSUE THREAD

**Issue by nmaier** [aria2/aria2#313]
Firefox already disabled SSL3 completely, Chrome will disable it in v30.
In light of broken ciphers and most recently, the poodle attack affecting all block ciphers in SSLv3, the already long broken stream ciphers, etc. aria2 should follow suit and disable SSLv3 entirely in all TLS backends.

It should be feasible to add a pref to enable SSLv3 for those who still need it for backwards compatibility, however, the implementation should then warn that SSLv3 is in use.
- [ ] OpenSSL
- [ ] GnuTLS
- [ ] AppleTLS
- [ ] WinTLS

**Comment by KOLANICH** [comment]
It should be a fatal error, not a warning
