### ISSUE TITLE
 torrent file does not contain a root dictionary.

### ISSUE THREAD

**Issue by mohsenhe** [aria2/aria2#474]
I tried this on several machines but nothing:

aria2c -T 6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent -S
Exception caught
Exception: [bittorrent_helper.cc:416] errorCode=26 torrent file does not contain a root dictionary.

I am using 1.19.2 (the latest)

This is the file:
http://torcache.net/torrent/6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent

**Comment by tatsuhiro-t** [comment]
Because the file is gzipped. Try gunzip it first.

**Comment by mohsenhe** [comment]
Hi,

It is not gunzipped. I always gunzip the files hence the reason why I download it first. Here's the full logs:

>[~/tmp] mv 6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent 6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent.gz
>[~/tmp] gunzip 6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent.gz
>[~/tmp] ls 6*
6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent
>[~/tmp] less 6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent
d8:announce36:udp://open.demonii.com:1337/announce13:announce-listll36:udp://open.demonii.com:1337/announceel38:udp://tracker.publicbt.com:80/announceel44:udp://tracker.openbittorrent.com:80/announceel35:udp://tracker.istole.it:80/announceel43:udp://fr33domtracker.h33t.com:3310/announceee26:azureus_private_propertiesd13:obtained_from326:magnet:?xt=urn:btih:6e0f6ffb0908fd215ef2a8bcdd1dfba019cca2b8&dn=The.Kite.Runner.2007.720p.BluRay.x264.anoXmous&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ffr33domtracker.h33t.com%3A3310%2Fannounce&tr=udp%3A%2F%2Ftracker.istole.it%3A80%2Fannounce10:peer_cached13:tracker_peersld2:ip14:197.35.232.2084:porti10051e4:proti1eed2:ip11:41.79.71.114:porti1040e4:proti1eed2:ip14:115.248.123.774:porti51932e4:proti1eed2:ip11:189.74.42.54:porti41618e4:proti1eed2:ip14:45.114.121.1004:porti20757e4:proti1eed2:ip14:112.198.103.754:porti33346e4:proti1eed2:ip11:92.6.18.1884:porti56716e4:proti1eed2:ip12:89.77.129.134:porti11373e4:proti1eed2:ip14:27.106.123.1324:porti15759e4:proti1eed2:ip14:105.103.96.2324:porti15326e4:proti1eed2:ip14:76.184.250.2434:porti60190e4:proti1eed2:ip14:27.106.123.1764:porti15759e4:proti1eed2:ip13:52.26.135.2534:porti18233e4:proti1eed2:ip13:85.23.163.1864:porti24351e4:proti1eed2:ip10:39.54.1.384:porti16235e4:proti1eed2:ip15:177.133.126.2104:porti18879e4:proti1eed2:ip13:41.133.186.414:porti26329e4:proti1eed2:ip14:78.243.204.1604:porti1024e4:proti1eed2:ip13:138.88.42.2434:porti26085e4:proti1eed2:ip15:201.113.113.2454:porti38537e4:proti1eed2:ip13:5.107.126.1414:porti24874e4:proti1eed2:ip12:52.11.39.1794:porti17335e4:proti1eed2:ip13:83.150.17.2004:porti39379e4:proti1eed2:ip13:183.90.37.1234:porti18032e4:proti1eed2:ip13:183.90.37.1234:porti18050e4:proti1eed2:ip14:117.212.74.1574:porti13646e4:proti1eed2:ip13:183.90.37.1234:porti18055e4:proti1eed2:ip15:217.208.215.1974:porti54622e4:proti1eed2:ip11:41.79.71.114:porti19662e4:proti1eed2:ip14:189.81.216.1324:porti26867e4:proti1eed2:ip13:212.251.18.714:porti22898e4:proti1eed2:ip13:178.84.125.374:porti49727e4:proti1eed2:ip13:201.33.178.984:porti24874e4:proti1eed2:ip13:183.90.37.1234:porti27233e4:proti1eed2:ip12:39.42.125.444:porti43481e4:proti1eed2:ip13:182.189.46.174:porti41236e4:proti1eed2:ip13:183.90.37.1234:porti27234e4:proti1eed2:ip15:112.198.103.1154:porti6881e4:proti1eed2:ip14:95.211.190.2054:porti55251e4:proti1eed2:ip14:189.35.139.2344:porti52325e4:proti1eed2:ip14:113.193.48.2034:porti16031e4:proti1eed2:ip13:117.199.52.574:porti30257e4:proti1eed2:ip12:189.40.41.104:porti44747e4:proti1eed2:ip11:46.1.239.254:porti6881e4:proti1eed2:ip13:93.159.143.444:porti22256e4:proti1eed2:ip14:37.130.117.2204:porti38789e4:proti1eed2:ip15:182.186.121.2424:porti17696e4:proti1eed2:ip14:112.198.103.754:porti43414e4:proti1eed2:ip15:182.178.175.1414:porti23113e4:proti1eed2:ip11:41.137.12.24:porti26182e4:proti1eed2:ip12:89.23.238.994:porti14020e4:proti1eed2:ip14:115.248.123.774:porti50380e4:proti1eed2:ip11:80.43.12.924:porti3061e4:proti1eed2:ip15:178.149.229.1084:porti59921e4:proti1eed2:ip14:189.46.159.1804:porti6881e4:proti1eed2:ip15:151.228.144.1624:porti53493e4:proti1eed2:ip14:67.173.241.1064:porti47118e4:proti1eed2:ip13:177.18.251.684:porti60957e4:proti1eed2:ip12:39.57.115.394:porti35097e4:proti1eed2:ip14:175.110.84.1084:porti57175e4:proti1eed2:ip12:176.63.8.1504:porti35334e4:proti1eed2:ip15:203.218.219.1394:porti62348e4:proti1eed2:ip14:138.51.242.2174:porti42685e4:proti1eed2:ip15:179.105.121.1704:porti30348e4:proti1eed2:ip13:94.69.232.2304:porti39751e4:proti1eed2:ip13:158.181.41.914:porti21790e4:proti1eed2:ip13:138.36.32.1644:porti61024e4:proti1eed2:ip13:81.97.222.2064:porti36894e4:proti1eed2:ip14:197.97.101.1504:porti62721e4:proti1eed2:ip11:95.7.35.2534:porti3931e4:proti1eed2:ip12:52.11.39.1794:porti6881e4:proti1eed2:ip13:188.27.23.1564:porti52405e4:proti1eed2:ip14:213.57.253.2534:porti25565e4:proti1eed2:ip12:85.75.65.1824:porti55802e4:proti1eed2:ip15:182.183.237.1444:porti13086e4:proti1eed2:ip13:158.181.41.914:porti4073e4:proti1eed2:ip14:112.198.103.754:porti23278e4:proti1eed2:ip13:109.228.74.554:porti17090e4:proti1eed2:ip13:177.40.178.774:porti27829e4:proti1eed2:ip14:177.68.217.1464:porti26795e4:proti1eed2:ip13:92.99.199.1174:porti38824e4:proti1eed2:ip13:183.90.37.1234:porti26655e4:proti1eed2:ip14:173.238.179.364:porti59534e4:proti1eed2:ip13:183.90.37.1234:porti26892e4:proti1eed2:ip14:71.204.183.2104:porti22159e4:proti1eed2:ip14:175.139.202.774:porti20540e4:proti1eed2:ip13:196.207.77.154:porti28687e4:proti1eed2:ip15:177.158.172.2524:porti57832e4:proti1eed2:ip15:124.189.137.2524:porti35885e4:proti1eed2:ip15:205.250.122.2044:porti63931e4:proti1eed2:ip15:122.172.173.1824:porti50225e4:proti1eed2:ip12:121.54.40.564:porti6881e4:proti1eed2:ip13:85.250.221.784:porti1042e4:proti1eed2:ip12:39.47.16.2554:porti51687e4:proti1eed2:ip12:89.153.5.1754:porti59696e4:proti1eed2:ip12:81.12.209.584:porti58485e4:proti1eed2:ip15:182.185.249.2204:porti24605e4:proti1eed2:ip15:103.252.201.1454:porti16327e4:proti1eed2:ip14:189.68.149.1374:porti26795e4:proti1eed2:ip14:89.177.101.1704:porti63525e4:proti1eed2:ip13:190.172.9.1634:porti43611e4:proti1eed2:ip13:183.90.37.1234:porti26635e4:proti1eeee16:peer_cache_validi-2.6960757756466E+18ee7:comment61:Torrent downloaded from torrent cache at http://torcache.net/4:infod13:file-durationli0ei7663ei0ei0ei0ei0ei0ee10:file-mediali-1ei0ei-1ei-1ei-1ei-1ei-1ee5:filesld6:lengthi1965e4:pathl5:i.nfoeed6:lengthi1439461945e4:pathl51:The.Kite.Runner.2007.720p.BluRay.x264.anoXmous_.mp4eed6:lengthi71489e4:pathl54:The.Kite.Runner.2007.720p.BluRay.x264.anoXmous_dan.srteed6:lengthi85863e4:pathl54:The.Kite.Runner.2007.720p.BluRay.x264.anoXmous_eng.srteed6:lengthi66916e4:pathl54:The.Kite.Runner.2007.720p.BluRay.x264.anoXmous_fin.srteed6:lengthi74723e4:pathl54:The.Kite.Runner.2007.720p.BluRay.x264.anoXmous_nor.srteed6:lengthi69151e4:pathl54:The.Kite.Runner.2007.720p.BluRay.x264.anoXmous_swe.srteee4:name46:The.Kite.Runner.2007.720p.BluRay.x264.anoXmous12:piece lengthi2097152e6:pieces13740:<EB>Gt<EE><8C>^R}<DA><C9><98><D1>\<C9>(
<C7><97><98><83>!<99><A5><85>e<C0>qF<A9><D5>V<CF>:^N<87><86><C0>^Q<9B>yb<B0><F1><D8>~uS<EF>#<FA>`?X=|y<89><FB><EA><AF>^NQNz4<B9>t^<99><EC>K<8C><E7>RC<E4><8D>c
<AA><F0>^L<F8>}<D7><C2>n$9^^<A2><89>|^P_h<CD>"D<BE>u<D2><8A>X:]N<B6>%}<FF><99>
<E9>A<96>'^Y<FB>m<D4><81><A3>YN0<F0>/s<B6>^R=<98><AA><8A>)<^@S^G<C4>^L<91><A6>F7<90>{<E9>*<CD><A3><A8><A0>6<A3>^])^O<AB>^A}<FB><C5><C8><8D><F0>Z<A7>^H+<EB><D4>
<BA>^Y<B2>I^Q<D4><FA>kC@<F3><9E><FE><AC><A6><F7>m<F4>T6Nt^B4^N<85><DB>*G<B9>VD(s[<CB>6<DC><B1>>2<9C>Ng<BC>D<D7><8B><ED><CB><83><B5><CB><8D>6<E9><AE>\<A4><FE>
<A9><E1><E5>E<CD><DD>,e<95>e<A4><89><9C>(f<AE><DE><CD><AA><A5><C1>Z?6<8C><82>^X]<E8><A6>,<F0><CF><BA><B5>D<9D>k06<CE>XPD<F6><A9><C9><8F><C6>^"-<97><96><99>^LHm
<91>^B/<9B><C3><E7><94><D1>z<8B><P^G<A1><85><F9><E3><9F><EF>M<9A>}^B|^LQ<92>|
<BA><DB><85>`<C2>&^O<C8>HV<DE>0<B8>,<F7><EE>V<D5>p^_^C<99><8B><99><FB>3<A<B4>
<8A><82>V<E3>;<FC><D5>(^L<F2>^^<F9><AF>l(^\<D2><C2><82><9B>Cc^DI<89>^C<CE><90>
<F2><99><E4><A6>6^]<FA><AF><B4>P^\<93><D3><B1><D7><D4><F7>v<AD><9D><AC>
<D1><95>G<AE><F6>=y<F8>;<E3>d<EF><C2>2i<88>G<EC>%^@k?<F2><A0>5y^N^R^RT'<F6>U^_a
<A4><B1><FE>     ^C<FD>0Z<EB><9B><DB><A1>)^A^A<80><90><E5><F0><B1>E<D4>i<D5><93><9F><E0>.<F1>.fn^S<DF><DB>[.Rz42F<B9>^?L8<E4><BF><DC><B2>^V<A8><BF><A2><DD>v<87><85><C3><FC>W<A0>{<9C>N<86><E1>j<E3><AA>WCg|oi*dI=^Fx<87><CA>O<E0><E0>n<D5>-b
<C2><C8>^C<D1>3<B3><C9>K}xQ^?f<B9><F2><AB><9D><E2>^\<FC>^W)<8D><=<A2><D0><D2>
<96>ESC<E1>Fe<C1>^O<8F><AA><C4>^O5D^AJ<9F>-}0<95><8F>c<B2><E9><B4><8A><E1>AM<F6><DA><EE>^ZS6^E<E8>Va<D7><FD><C9>^H<BF>$<9B>q<88><J<9F>+r<EB>:$=<9F><A3><CA><95>
<BC><BE>{7<E3>`^P<F7><8C><C7>
<D0>j^U<C0>2<D5>^\<A8><C6><A1>,^]<CB>YNr^S^U<B7>(^<BA><91>@`<89><C7><84>\<93>^]
<98>\<DC>><B0>
<F5><CF>h,<8C>hESCY^Ad^?<B5>z<DD>2<AD><C8><88><D6><C7>8j<BD><9E>-<9B><AF><BC>
<EC><A9>K<F7>e<C0>b^K<B7>` >_@<B7>}^\<D2><CB><EC><88><F1>1<AE><AB><FF>^Z<AE><C5><F0><CA><83>(@<DD>%^S<B8>Q!^Xi<9F><AD>><B7><D5><C6>'^Nz<F3><B8>^}q<C9><AD><83>
<97><83>#f<C1>^E4WD^O<AA><B0><D3>Z<]<AD>d^BN<87>^CX^Qi<FF><D3>^Qwx2f#<DA><F2>^VU^]a:E>^Q<E0>dAN<DD><D7><E9>;T<9E>    <ED>C<E4>3<C9>&<B2><A9><A7><CF><F7>.<C3>>
<F7><C9>K<B9><93><BD><C6>^Z<9D><A9><C9>I<86><D0>v<86><D2>2<DD><F4><B0><CF>^K^Fb
<C6>D^Y<C2>^F<DF><F1><83><BC>   <F3><D8>^B?`a*<CF><EA>`<8D><C9>^]C^C<C5><C9><B6>;^E<9B><E9><BA>6^U<CA><B3><E1><A0><8B><85><A9><E4><C3>@^T<92>+0B<F9><D7>MHL^L
<90><A3>'^L)^]]7<D4><FF>M'JJ<E4>^C^XV:2<AD><FB><AB><F8><AC>9<A3><E9>m<A5><C5>D
<CC><B0>~^Y#<C5><C2><E2>w#<FB>[(<F6><C7>m<C1><BE>A<BB>0<8F>2^T<E8>Nm<E0><95><9E>f7<CA>^D<86>]<C6>5<F7><99><91>T|<E6>j<A0><E5>h
tO<CB><F1>m/^@R<F2><87>=<94><8F><9B><BF><B7><F1><9F><F3>J<C6>W<85>-6<99>/.W(<C2>;<F8><81><81><C9><DF><DD><8C>D)<90>F^Zd<9C>
/<9A>o<F1>w<E9>+'|5^L<8C>[<BA><DB>.7<DD>D<F1><D4><D8>`$<E6><D7><F2>^D^H<BA>*<F2>*<E8>s<C8>(<B4>^Lc!<F6>Xps      <F5>)<9E>S<EA>{<9D>iL<D9>?<AD>p^D^G^@O<D2>      ;<D6><C8>O<9C><E5><D7><F9>^\^X2<A3>0<C3><B6><8C>2'u}^E<F2>d<82>^S<A9><9F>B<E4>_
>[~/tmp] aria2c -T 6E0F6FFB0908FD215EF2A8BCDD1DFBA019CCA2B8.torrent -S
Exception caught
Exception: [bittorrent_helper.cc:416] errorCode=26 torrent file does not contain a root dictionary.

>[~/tmp]

**Comment by tatsuhiro-t** [comment]
It turns out that the torrent file contains invalid integer: ``i-2.6960757756466E+18e``
As far as I know, torrent file's integer encoding does not allow this scientific format.

**Comment by mohsenhe** [comment]
I am not too familiar with the standard but the same file works perfectly fine on utorrent and other bit torrent clients.

Can you please fix it so that it works.
Thanks

**Comment by tatsuhiro-t** [comment]
This has fixed in the latest release.
