### ISSUE TITLE
Does Aria2 support ed2k download links?

### ISSUE THREAD

**Issue by pingshunhuangalex** [aria2/aria2#603]
Hi Tatsuhiro-t

First please let me thank you for the amazing work you've done so far. Aria2 is definitely one of the amazing things that comes to my life, and it's now an essential part of my browsing experience.

Since I'm still quite new to the utility, just wonder if Aria2 supports ed2k download links (i.e. eDonkey Network)?

If the answer is positive, could you please give me some guidance on how to set things up as it's now the only thing that's not working at the moment.

If the answer is negative, it would be nice to know if this function will be supported in the soon future. Thanks.

**Comment by tatsuhiro-t** [comment]
aria2 does not support ed2k, and we have no plan to support it at the moment.

**Comment by joeshae** [comment]
ed2k is very useful when downloading some resources from some forums. 
Aria2 is my favorite downloader. I'm using it to download almost everything I need, except the ed2k resources, which I have to switch to amule to deal with. 
So I hope ed2k could be supported in aria2. 
Thank you @tatsuhiro-t !

**Comment by underlaw** [comment]
+1

**Comment by Windows10010** [comment]
+1

**Comment by sjehuda** [comment]
I have open a ticket for Gnutella at #2276
