### ISSUE TITLE
BT Torrent downloaded can't be open

### ISSUE THREAD

**Issue by pingshunhuangalex** [aria2/aria2#604]
Hi Tatsuhiro-t

Something is not right with the torrent downloaded by Aria2.

First, I found that the BT task won't start automatically after downloading torrent even though I've already enabled the follow-torrent=true in the configuration. I thought it must be some setting issue.

However, when I try to manually load the torrent downloaded, it gives "Bencode decoding failed" error (I'm using an Aria2UI). Weirdly, when I download the same torrent using chrome, the same torrent can then be loaded in Aria2. That's how I draw the conclusion. I've tested on a few different sites, and it gave me the same result. Could you please fix this issue as well as the "follow-torrent" function? Thanks.

**Comment by tatsuhiro-t** [comment]
Regarding "Bencode decoding failed", we have fixed the similar issue, see #598.

The possible reason why download was not automatically started is that its filename does not end with ".torrent", or its content-type is not "application/x-bittorrent".

**Comment by pingshunhuangalex** [comment]
Thanks for the reply. The version 1.21 I used is directly downloaded from project page. The folder I have looks much simpler than the master folder, i.e. there is no src folder nor BencodeParser.cc for me to tweak.

I also try to update everything using the files in master branch, but it seems simply adding those file doesn't do anything to the utilities. Some more guidance would be much appreciated. Thanks.

**Comment by pingshunhuangalex** [comment]
I kind of understand my problem now. I think the link I captured is not really the real path for my torrent. When chrome open the link it download something else directed by the link, which brings me to another problem...

Is there a way to associate .torrent file somehow with aria2 (or aria2UI)? i.e. when I open (double click) the torrent file, aria2 starts the BT tasks accordingly? Thanks.
