### ISSUE TITLE
torrent can't be downloaded due to gzip content-encoding

### ISSUE THREAD

**Issue by pingshunhuangalex** [aria2/aria2#605]
Hi Tatsuhiro-t

Here I am again, continuing from my last post on failing to download some torrents due to re-directed download link.

I had no idea on what's going on, but one of my friends identified that the problem may be caused by aria2 failed to recognise ```content-encoding: gzip``` (Aria2 can recognise ```Content-Encoding: gzip```, but not ```content-encoding: gzip```). This bug keeps aria2 downloading gzip file instead of a genuine torrent which break follow-torrent function.

Could you please look into it and fix it? Thanks.

**Comment by tatsuhiro-t** [comment]
As far as I know, we search content-encodng in case insensitive manner.  Did you observe that aria2 can download torrent if the incoming header is "content-encoding: gzip" instead of "Content-Encoding: gzip"?
Note that aria2 does not inflate gzipped file by default.  --http-accept-gzip will do.

**Comment by pingshunhuangalex** [comment]
I did have --http-accept-gzip set to true already, but the problem remains. I think it's just Chrome API then. I don't know if there's a way to describe or to fix it. Thanks anyway.

I'm just curious that nobody else in the feedback section seems to be bothered with this issue. How do you guys deal with torrent file? Just download it and load it into aria2 via ui or cmd? Thanks.

**Comment by tatsuhiro-t** [comment]
I confirmed torrent with content-encoding: gzip works if --http-accept-gzip is used.
If it does not work, it is probably due to 1) without .torrent extension, or 2) content-type does not indicate it is torrent file.

**Comment by pingshunhuangalex** [comment]
Thanks. That narrows the issue to chrome API then. Like what I reported in the previous thread, some urls will redirect users to torrents' true path before downloading it. So simply sending the url to aria2 will only download a webpage file or files that are irrelevant. Good examples would be:
http://seventorrents.one/Download/Star-Wars-Episode-VII-The-Force-Awakens-2015-720p-BRRip-x264-AAC-ETRG.1100136.aspx

https://torcache.net/torrent/6897D03D612BC329AC2B504C61CF2A106AEA1253.torrent?title=[kattorr.com]sofcj.raws.pocket.monsters.xy.z.19.tva.1280x720.x264.aac.mp4

There are a lot of cases like this, but I'm not sure if there's anything you can do if it's a chrome api issue. If you are still interested, you can have a go with the urls above. Thanks.

**Comment by tatsuhiro-t** [comment]
Please don't paste the URI which is potentially illegal (guessing from the URI).

**Comment by pingshunhuangalex** [comment]
Sorry, just some random url I searched using google. Well, you get the idea now, and I don't know how else I can pass the message.
