### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [aria2/aria2#624]
Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html "Change a signal action.") ⇒ [setGlobalSignalHandler](https://github.com/tatsuhiro-t/aria2/blob/f0f1b8ef47c391550ff99982f1cad3dd4e1d410d/src/util.cc#L1309)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [putOptions](https://github.com/tatsuhiro-t/aria2/blob/f0f1b8ef47c391550ff99982f1cad3dd4e1d410d/src/OptionParser.cc#L85)

**Comment by tatsuhiro-t** [comment]
Fix committed via 1ce6ac0b238b653d9b49a1c9f913d08db2b74c69

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/aria2/aria2/commit/1ce6ac0b238b653d9b49a1c9f913d08db2b74c69 "More error handling").
