### ISSUE TITLE
about --max-mmap-limit=<SIZE>

### ISSUE THREAD

**Issue by XhstormR** [aria2/aria2#633]
>--max-mmap-limit=\<SIZE>
>Set the maximum file size to enable mmap (see --enable-mmap option). The file size is determined by the sum of all files contained in one download. For example, if a download contains 5 files, then file size is the total size of those files. If file size is strictly greater than the size specified in this option, mmap will be disabled. Default: 9223372036854775807

Can i use  `max-mmap-limit=2048M` ?

**Comment by tatsuhiro-t** [comment]
Yes.  Didn't it work for you?

**Comment by XhstormR** [comment]
I have not tried.I'm just not sure.Thanks.
