### ISSUE TITLE
make :no rule to make target. stop

### ISSUE THREAD

**Issue by magantiakhilchandra** [aria2/aria2#634]
I tried going through various websites but still couldn't find a solution to this.

akhil@akhil-virtual-machine:~/etherlab/sources$ ls
aclocal.m4  autoconf        bootstrap  CodingStyle.txt  config.log  configure.ac  COPYING.LESSER  documentation  ethercat.spec.in  FEATURES   include  Kbuild.in  m4           Makefile.in  NEWS    README.EoE  script  tool
AUTHORS     autom4te.cache  ChangeLog  config.h.in      configure   COPYING       devices         Doxyfile.in    examples          globals.h  INSTALL  lib        Makefile.am  master       README  rtdm        TODO    tty
akhil@akhil-virtual-machine:~/etherlab/sources$ make all modules
make: **\* No rule to make target 'all'.  Stop.

**Comment by tatsuhiro-t** [comment]
Probably, you pulled master branch from github.  If so, you have to generate configure and other scripts using `autoreconf -i`.
I think it would be easier to download release source archive from release page, which includes all generated scripts.

**Comment by lexbrugman** [comment]
I'm getting a similar error after running configure with --disable-websocket:

> make  all-recursive
> make[1]: Entering directory `/tmp/aria2-1.29.0'
> Making all in po
> make[2]: Entering directory `/tmp/aria2-1.29.0/po'
> make[2]: Leaving directory `/tmp/aria2-1.29.0/po'
> Making all in lib
> make[2]: Entering directory `/tmp/aria2-1.29.0/lib'
> make[2]: Nothing to be done for `all'.
> make[2]: Leaving directory `/tmp/aria2-1.29.0/lib'
> Making all in deps
> make[2]: Entering directory `/tmp/aria2-1.29.0/deps'
> Making all in wslay
> make[3]: Entering directory `/tmp/aria2-1.29.0/deps/wslay'
> make[3]: *** No rule to make target `all'.  Stop.
> make[3]: Leaving directory `/tmp/aria2-1.29.0/deps/wslay'
> make[2]: *** [all-recursive] Error 1
> make[2]: Leaving directory `/tmp/aria2-1.29.0/deps'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/tmp/aria2-1.29.0'
> make: *** [all] Error 2

All is good without --disable-websocket

**Comment by tatsuhiro-t** [comment]
@lexbrugman This bug was fixed in b76435fe779ca67d2b1cc794ebb7fafc4d0955ff.  Thank you.

**Comment by magantiakhilchandra** [comment]
I know I am late, but Thanks for info @tatsuhiro-t
