### ISSUE TITLE
place errors on stderr, instead of stdout

### ISSUE THREAD

**Issue by AladW** [aria2/aria2#638]
Right now, aria2c prints diagnostics on stdout, which makes it more difficult to use in scripts (in particular, shell pipes). curl and wget print to stderr instead.

**Comment by tatsuhiro-t** [comment]
I'd like to make this WONTFIX.  This is because if we change the device, the existing script might not work anymore.

**Comment by AladW** [comment]
As with #639, you could keep the existing behaviour by making the new one optional, e.g via `-stderr`.

**Comment by tatsuhiro-t** [comment]
Yes, we can send all stuff currently written to stdout to stderr with new --stderr option.
But it only happens after --stderr is parsed correctly.  Before options are parsed, still stdout is used for backward compatibility.

**Comment by tatsuhiro-t** [comment]
Fix committed via db239c2853cb2982260be39a521fb5672c7e8245

**Comment by AladW** [comment]
Works for me. Though it seems the option is not included in `aria2c --help`.
