### ISSUE TITLE
File name too long (exactly 247) in torrent download

### ISSUE THREAD

**Issue by g0dless** [aria2/aria2#651]
Hello! Great program, at first =)
I tried to download some torrent by magnet uri. Download started, but stopped with

> 2016-05-12 11:43:25.183083 [ERROR] [RequestGroupMan.cc:492] Обнаружено исключение
Exception: [AbstractDiskWriter.cc:221] errNum=36 errorCode=15 Ошибка открытия файл /data/media/download/aria2/blablablalbalba .... .blabla: Слишком длинное имя файла

ENG:
> 2016-05-12 11:43:25.183083 [ERROR] [RequestGroupMan.cc:492] Exception detected
Exception: [AbstractDiskWriter.cc:221] errNum=36 errorCode=15 File open error /data/media/download/aria2/blablablalbalba .... .blabla: File name too long

Totally file name length (I mean full path) is 247 (sic!) chars. Not 255...
FS is ext4. Ubuntu 14.04. 

> aria2c -v
aria2 версия 1.18.1
Copyright (C) 2006, 2013 Tatsuhiro Tsujikawa

I suppose, that new feature have to be: something like "--truncate-filename-if-path-is-too-long" =)

**Comment by tatsuhiro-t** [comment]
I heard that Windows API suffers from short PATH_MAX problem (around 260 characters), but usually Linux platform has much longer limit, usually PATH_MAX is defined as 4096.

**Comment by g0dless** [comment]
yes linux by default have 4k for paths
> ~$ getconf NAME_MAX /data/media
255
~$ getconf PATH_MAX /data/media
4096

**Comment by g0dless** [comment]
I found the answer! This is not an issue of aria2c!

From here: https://forum.transmissionbt.com/viewtopic.php?p=55918#p55918

> Length of filename is 377 bytes (this is length of raw C string). It is encoded in UTF-8. If we transcode it to UTF-16, we will get length of 206 wide characters. It easily fit onto Windows NTFS, as it use UCS-2 encoding and allows 255 wide characters, effectively 510 bytes.
But utf-8 presentation requires 377 bytes, so cannot be used as filename in unixes, as they limit name by 255 bytes, and, I repeat, modern OS'es doesn't use national codepages and do write utf-8 filenames to disk structures as-is.

**Comment by smasterfree** [comment]
I find a way to solve this problem.

1. download the torrent
2. download torrent file editor https://torrent-file-editor.github.io/
3. edit the torrent raw data( the file name is metadata), and save new torrent
4. now download from new saved torrent
