### ISSUE TITLE
BitTorrent http webseed with spaces

### ISSUE THREAD

**Issue by mfredrick** [aria2/aria2#654]
aria2-1.22.0-win-64bit-build1

downloading a torrent file with spaces in the file name from a http server does not work.

aria2c --torrent-file="test file.torrent" "http://host1/test file"
aria2c --torrent-file="test file.torrent" "http://host1/test%20file"

both return errors.
ftp works fine though..

aria2c --torrent-file="test file.torrent" "ftp://host1/test file"

looks similar to a previous issue?
https://sourceforge.net/p/aria2/bugs/60/

thank you tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
It works for me on Linux.
What kind of error did you get?
HTTP request in aria2 log may help debugging.

**Comment by mfredrick** [comment]
I was testing using a batch script and forgot to escape %20 to %%20.

aria2 is great!
thank you tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
Thank you for heads up.  Closing.
