### ISSUE TITLE
cookies file doesn't get processed correctly

### ISSUE THREAD

**Issue by stangri** [aria2/aria2#655]
I've exported cookies from Chrome using cookies.txt extension and it had some dots:

> host.com    TRUE    /       FALSE   1486337059.xxxxx      login  
> host.com   TRUE    /       FALSE   1549409059.xxxxx      auth 

wget works with this cookie file as is, for aria2c I've had to remove the ".xxxxx" part to make it send login/auth from this cookie file.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  Looks like chrome puts subsecond time in expires date, and aria2 does not understand it.

**Comment by tatsuhiro-t** [comment]
Fix committed via bafbbe7
