### ISSUE TITLE
Add $HOME/.config/aria2/aria2.conf to config path

### ISSUE THREAD

**Issue by nils-werner** [aria2/aria2#656]
Most modern Linux utils try to save their config files in `$HOME/.config/<toolname>` instead of `$HOME/.<toolname>`. Aria2 should follow suit and also look for a file there.

**Comment by tatsuhiro-t** [comment]
We are doing it already: http://aria2.github.io/manual/en/html/aria2c.html#aria2-conf

**Comment by nils-werner** [comment]
Oh right, I must have found an older version of the manual then.
