### ISSUE TITLE
SetFileValidData (falloc in Windows) seems to fail in 1.23.0 build 1

### ISSUE THREAD

**Issue by jrmoore** [aria2/aria2#657]
Hi, I'm using --file-allocation=falloc with the current build of 1.23.0 for Windows (the 64-bit one) and aside from the usual warning about that file allocation method under Windows there's one that didn't appear before:

File allocation (SetFileValidData) failed (cause: A required privilege is not held by the client.).

Resulting in aria2 allocating space by filling with zeroes. I tried with different downloads both torrent and http based ones at least lead to this even though I launched aria2 from an administrative prompt.

Such warning didn't appear in the previous build (1.22.0 build 1, 64-bit), and doesn't appear now either if the download is small: a 2.3MB file doesn't trigger it for example, a 300MB one does.

**Comment by tatsuhiro-t** [comment]
Confirmed.  It looks like we have to gain privilege before opening file.
949a580a14cd3afcdf9904acd1d32397c344dd28 will fix this issue.

Because of --no-file-allocation-limit option, by default, file of less than 5 MiB does not trigger file allocation, so there is no warning.

**Comment by tatsuhiro-t** [comment]
Please reopen this bug if you still have this issue.
