### ISSUE TITLE
aria2 torrent individual file download

### ISSUE THREAD

**Issue by jabardast** [aria2/aria2#658]
Hi,

I am using Aria2 Version 1.15.1  on my raspberry pi (3.12.25+ #700 PREEMPT).
I have 3 questions about downloading torrents via aria2

1.  If a torrent has multiple files, can I prioritize their download. Let's say a torrent has 24 files - file1.pdf,file2,pdf...file 24.pdf. Can I mark them sequentially so file 1 is downloaded first, then 2 etc. I googled it and it looks like its not possible

2. If question 1 is not possible. Is there a way to check the download status of individual files with in a torrent ? Aria2 doesn't marks incomplete files as .part or something, so it becomes tricky to identify which file has downloaded and which are still going on.

3. If question 1 and 2 are not possible. Can aria2 email once an individual file download finishes ?
Right now it emails me when the whole torrent is finished (all 24 files). 

Thanks in Advance.
Great software
Jab.

**Comment by tatsuhiro-t** [comment]
Sadly, answer is all NO.

**Comment by jabardast** [comment]
Thanks tatsuhiro-t  for taking time to answer them.
Too bad none of them can be done.

Last question, if I have 10 different files in download queue (bittorrent, url etc).
Can I prioritize them in the queue ?

My concurrent download limit is 1.
If I add file 1 at 10 AM, it starts downloading it.
Add another file at 10:05 , its in waitlist queue.
Add another file at 10:15, added to waitlist queue.

So can I change the download priority of the files which are in queue. 

Apologies in advance, If it's not allowed to add another question.
I will open a new thread if required.

Keep up the good work

**Comment by tatsuhiro-t** [comment]
The closest thing I can think of is that you can manually change the order of downloads waiting in the queue using aria2.changePosition RPC method.  http://aria2.github.io/manual/en/html/aria2c.html#aria2.changePosition

**Comment by jabardast** [comment]
again thanks for your prompt reply. I guess it has to be done via a python script.
Can this be done via webui or yaaw ? These are the frontend I am using right now.
I am open to use any other gui , if it has this feature.

**Comment by tatsuhiro-t** [comment]
Please ask Web UI developers about this.

**Comment by jabardast** [comment]
will do sir. thanks for your time
