### ISSUE TITLE
Incorrect handling of peer-id-prefix option

### ISSUE THREAD

**Issue by edtechd** [aria2/aria2#659]
If I launch aria2 with --peer-id-prefix="-BC0140-", it urlencodes this value and uses such request to the tracker:

GET /announce.php?passkey=.../&info_hash=...&peer_id=%2DBC0140%2D%3E%B7b%E4h%B....

But original client doesn't urlencode "-" symbol:

GET /announce.php?passkey=.../&info_hash=...&peer_id=-BC0140-K%D9%1EpK%BA%1B%DC....

Would it be possible to avoid urlencoding of "-" symbol because it doesn't have a reserved purpose and can be passed without encoding?

**Comment by tatsuhiro-t** [comment]
According to the commit log, this is intentional:

> 2006-08-12  Tatsuhiro Tsujikawa 
> To handle the case where some BitTorrent tracker requires all letters  except for [A-Za-z0-9] is URL encoded.

Perhaps, torrent tracker is now more matured, and we don't have to do this trick.  Have you seen any problem with this eagerly percent-encoded form?

**Comment by edtechd** [comment]
There is a private tracker siambit.tv which doesn't allow aria2 but accepts BitComet. But it seems that it checks the exact Peer ID header match. Urlencoded value doesn't work.

As a workaround, I can alter function torrentPercentEncode() in my fork for my specific case, I didn't know that some trackers require Peer ID fully urlencoded.

**Comment by tatsuhiro-t** [comment]
As far as I know, in olden days, bittorrent tracker's HTTP implementation is broken at best.
We'd like to correct our implementation based on HTTP, so we'll do this in standard way, and see how it breaks.

**Comment by tatsuhiro-t** [comment]
Fix committed via c57259f

**Comment by edtechd** [comment]
Thank you.
