### ISSUE TITLE
configure: error: ./configure failed for deps/wslay

### ISSUE THREAD

**Issue by Aaron20127** [aria2/aria2#661]
hi!
   My aria2 version is aria2-1.23.0, and there is a errow when I execute './configure'.

Copying file m4/codeset.m4
Copying file m4/fcntl-o.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/printf-posix.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makevars.template
libtoolize: `./ltmain.sh' is newer: use `--force' to overwrite
libtoolize: `m4/libtool.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltoptions.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltversion.m4' is newer: use `--force' to overwrite
libtoolize: `m4/lt~obsolete.m4' is newer: use `--force' to overwrite
libtoolize: `./ltmain.sh' is newer: use `--force' to overwrite
libtoolize: `m4/libtool.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltoptions.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltversion.m4' is newer: use `--force' to overwrite
libtoolize: `m4/lt~obsolete.m4' is newer: use `--force' to overwrite
configure.ac:812: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:812: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:812: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.

[root@localhost src]# ./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for cppunit-config... no
checking for Cppunit - version >= 1.10.2... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for bison... no
checking for byacc... no
checking dependency style of gcc... gcc3
checking for ar... (cached) ar
checking for sphinx-build... no
checking for rst2html.py... no
checking for rst2html... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.20... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11 ... yes
checking whether the c++ compiler supports nullptr... checking whether the C++ compiler supports `override` keyword... yes
checking for ZLIB... yes
checking whether gzbuffer is declared... no
checking for gzsetparams... yes
checking for xml2-config... /usr/local/bin/xml2-config
checking for libxml - version >= 2.6.24... yes (version 2.7.8)
checking for SQLITE3... yes
checking for sqlite3_open_v2... yes
checking whether to enable Mac OS X native SSL/TLS... no
checking for main in -lcrypt32... no
checking for main in -lsecur32... no
checking for main in -ladvapi32... no
checking for wincrypt.h... no
checking for security.h... no
checking for LIBGNUTLS... no
configure: WARNING: No package 'gnutls' found
checking for OPENSSL... yes
checking for EVP_DigestInit_ex... yes
checking for EVP_sha224... yes
checking for EVP_sha256... yes
checking for EVP_sha384... yes
checking for EVP_sha512... yes
checking for LIBSSH2... no
configure: WARNING: No package 'libssh2' found
checking for LIBCARES... no
configure: WARNING: No package 'libcares' found
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for ANSI C header files... (cached) yes
checking argz.h usability... yes
checking argz.h presence... yes
checking for argz.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking port.h usability... no
checking port.h presence... no
checking for port.h... no
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking stdio_ext.h usability... yes
checking stdio_ext.h presence... yes
checking for stdio_ext.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/signal.h usability... yes
checking sys/signal.h presence... yes
checking for sys/signal.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/types.h... (cached) yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking ifaddrs.h usability... yes
checking ifaddrs.h presence... yes
checking for ifaddrs.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for mode_t... yes
checking for off_t... yes
checking for size_t... (cached) yes
checking for ssize_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for pid_t... yes
checking for working volatile... yes
checking for ptrdiff_t... yes
checking for struct timespec... yes
checking whether byte ordering is bigendian... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether NLS is requested... yes
checking for msgfmt... /usr/local/bin/msgfmt
checking for gmsgfmt... /usr/local/bin/msgfmt
checking for xgettext... /usr/local/bin/xgettext
checking for msgmerge... /usr/local/bin/msgmerge
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for error_at_line... yes
checking whether gcc needs -traditional... no
checking for working memcmp... yes
checking for sys/time.h... (cached) yes
checking for unistd.h... (cached) yes
checking for alarm... yes
checking for working mktime... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking for sys/socket.h... (cached) yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking whether lstat correctly handles trailing slash... yes
checking whether stat accepts an empty string... no
checking for strftime... yes
checking for vprintf... yes
checking for _doprnt... no
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for working strtod... yes
checking for __argz_count... yes
checking for __argz_next... yes
checking for __argz_stringify... yes
checking for atexit... yes
checking for ftruncate... yes
checking for getcwd... yes
checking for gethostbyaddr... yes
checking for gethostbyname... yes
checking for getifaddrs... yes
checking for getpagesize... yes
checking for getrandom... no
checking for memchr... yes
checking for memmove... yes
checking for mempcpy... yes
checking for memset... yes
checking for mkdir... yes
checking for mmap... yes
checking for munmap... yes
checking for nl_langinfo... yes
checking for posix_fadvise... yes
checking for posix_memalign... yes
checking for pow... yes
checking for putenv... yes
checking for rmdir... yes
checking for select... yes
checking for setlocale... yes
checking for sigaction... yes
checking for sleep... yes
checking for socket... yes
checking for stpcpy... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strcspn... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for strtoull... yes
checking for tzset... yes
checking for unsetenv... yes
checking for usleep... yes
checking for utime... yes
checking for utimes... yes
checking for getrandom linux syscall interface... no
checking for epoll_create... yes
checking for posix_fallocate... yes
checking for fallocate... yes
checking for asctime_r... yes
checking for localtime_r... yes
checking for basename... yes
checking for gai_strerror... yes
checking for getaddrinfo... yes
checking for gettimeofday... yes
checking for strptime... yes
checking for timegm... yes
checking for daemon... yes
checking for poll... yes
checking for port_associate... no
checking for kqueue... no
checking for struct sockaddr_in.sin_len... no
checking for struct sockaddr_in6.sin6_len... no
checking whether struct option.name is assignable from const char*... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/libaria2.pc
config.status: creating src/includes/Makefile
config.status: creating test/Makefile
config.status: creating po/Makefile.in
config.status: creating lib/Makefile
config.status: creating doc/Makefile
config.status: creating doc/manual-src/Makefile
config.status: creating doc/manual-src/en/Makefile
config.status: creating doc/manual-src/en/conf.py
config.status: creating doc/manual-src/ru/Makefile
config.status: creating doc/manual-src/ru/conf.py
config.status: creating doc/manual-src/pt/Makefile
config.status: creating doc/manual-src/pt/conf.py
config.status: creating deps/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
=== configuring in deps/wslay (/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/package/td_aria2/src/deps/wslay)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
./configure: line 16641: syntax error near unexpected token `0.20'
./configure: line 16641: `PKG_PROG_PKG_CONFIG(0.20)'
configure: error: ./configure failed for deps/wslay

**Comment by tatsuhiro-t** [comment]
Have you installed pkg-config package?  If not, first install it, and then run `autoreconf -i` again.

**Comment by Aaron20127** [comment]
I am sure pkg-config has installed

**Comment by Aaron20127** [comment]
This time, I did not execute the command `autoreconf -i`, just executed `./configure`, This operation was successful. but when I executed the command ‘make’, Another problem occurred.I was a novice, please help me：
        
Making all in src
make[5]: Entering directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0/src'
Making all in includes
make[6]: Entering directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0/src/includes'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0/src/includes'
make[6]: Entering directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0/src'
depbase=`echo A2STR.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/sh ../libtool  --tag=CXX   --mode=compile ccache_cxx -DHAVE_CONFIG_H -I. -I..  -I../lib -I../intl -I./includes -I./includes -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include/libxml2 -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I../deps/wslay/lib/includes -I../deps/wslay/lib/includes  -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/include  -std=c++0x   -pipe -Os -pipe -march=armv7-a -mtune=cortex-a9 -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -MT A2STR.lo -MD -MP -MF $depbase.Tpo -c -o A2STR.lo A2STR.cc &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  ccache_cxx -DHAVE_CONFIG_H -I. -I.. -I../lib -I../intl -I./includes -I./includes -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include/libxml2 -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I../deps/wslay/lib/includes -I../deps/wslay/lib/includes -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/include -std=c++0x -pipe -Os -pipe -march=armv7-a -mtune=cortex-a9 -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -MT A2STR.lo -MD -MP -MF .deps/A2STR.Tpo -c A2STR.cc  -fPIC -DPIC -o .libs/A2STR.o
depbase=`echo AbstractAuthResolver.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/sh ../libtool  --tag=CXX   --mode=compile ccache_cxx -DHAVE_CONFIG_H -I. -I..  -I../lib -I../intl -I./includes -I./includes -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include/libxml2 -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I../deps/wslay/lib/includes -I../deps/wslay/lib/includes  -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/include  -std=c++0x   -pipe -Os -pipe -march=armv7-a -mtune=cortex-a9 -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -MT AbstractAuthResolver.lo -MD -MP -MF $depbase.Tpo -c -o AbstractAuthResolver.lo AbstractAuthResolver.cc &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  ccache_cxx -DHAVE_CONFIG_H -I. -I.. -I../lib -I../intl -I./includes -I./includes -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include/libxml2 -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I../deps/wslay/lib/includes -I../deps/wslay/lib/includes -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/usr/include -I/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/include -std=c++0x -pipe -Os -pipe -march=armv7-a -mtune=cortex-a9 -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -MT AbstractAuthResolver.lo -MD -MP -MF .deps/AbstractAuthResolver.Tpo -c AbstractAuthResolver.cc  -fPIC -DPIC -o .libs/AbstractAuthResolver.o
In file included from AbstractAuthResolver.cc:37:0:
a2functional.h:173:38: error: expected type-specifier before string constant
a2functional.h:178:38: error: expected type-specifier before string constant
a2functional.h:183:38: error: expected type-specifier before string constant
a2functional.h:188:38: error: expected type-specifier before string constant
a2functional.h:193:40: error: expected type-specifier before string constant
a2functional.h:198:40: error: expected type-specifier before string constant
a2functional.h:203:45: error: expected type-specifier before string constant
make[6]: *** [AbstractAuthResolver.lo] Error 1
make[6]: Leaving directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0/src'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0'
make[2]: *** [/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/td_aria2-1.0.0/.built] Error 2
make[2]: Leaving directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master/package/td_aria2'
make[1]: *** [package/td_aria2/compile] Error 2
make[1]: Leaving directory `/home/LACZF/Workplace/tenda_wifiv1.0/develop/master'
make: *** [package/td_aria2/compile] Error 2

**Comment by monotykamary** [comment]
I've only compiled this with Cygwin, but I've tried to make sure that I installed these dependencies:

- Cppunit
- bison
- byacc
- lcrypt
- libgnutls
- libssh2

Cygwin doesn't have the c-ares library (libcares) so I wasn't able to install that, but it still worked fine. Try to start from scratch and install those dependencies before `./configure` and `make`.

**Comment by tatsuhiro-t** [comment]
It looks like gcc is too old to compile aria2.  It requires at least gcc >= 4.8.3 or clang >= 3.5.

**Comment by Aaron20127** [comment]
Thank you，the gcc is too old. I installed the gcc 4.9, and compiled successfully.
