### ISSUE TITLE
question/ howto: aria2c for bittorrent seeding on a private LAN ?

### ISSUE THREAD

**Issue by SSSSeb** [aria2/aria2#663]
Hello, 

I am still trying to understand what is a full working workflow to share one large file with thousands of systems on a LAN. More specifically, it seems possible to not need a tracker and use DHT

I understand I will need to 

- point to the dht-entry-point using:  --dht-entry-point for the clients
- provide the same port number to the seeder process for the main server

I did not undesrtand:

- what tool I should use to generate the .torrent file and if it is really needed. (why do I need one at all?)
- I was not able to understand why the -V option should be used on the seeder process.

I would like to get this to work first with two servers... 

note: I managed to get the concept to work with many servers running aria2c when using (on the master server) the bittorrent tracker and the bittorrent client as the initial download (seed). I hope I can simplify this setup and only use aria2c everywhere.

Thx in advance.

**Comment by tatsuhiro-t** [comment]
>  what tool I should use to generate the .torrent file and if it is really needed. (why do I need one at all?)

aria2 could not create .torrent file.  You need other program, say, btmakemetafile, to create .torrent file.  In DHT, we don't use tracker.  You can just pass fake tracker URI.  aria2 may complain about it, but it can be safely ignored.

In DHT, only seeder requires .torrent file.  Clients can use magnet URI to pull the data.  You can see the magnet URI by running `aria2c  -S /path/to/torrent.file`.

>  I was not able to understand why the -V option should be used on the seeder process.

To seed files, aria2 first make sure that it is not broken.  -V option checks piece hashes of a file against the hashes described in .torrent file.
If you are sure that file is OK, then you can use --bt-seed-unverified instead of -V to speed up the start up time.

**Comment by tatsuhiro-t** [comment]
I made an important fix to make DHT work in private network: 3e00be26e8f8fe44c7344a3e8026031a99b22400

**Comment by SSSSeb** [comment]
Thank you very much !

**Comment by SSSSeb** [comment]
I confirm I managed to download a file between two servers on a local LAN with the 3e00be2

**Comment by drcxd** [comment]
> I confirm I managed to download a file between two servers on a local LAN with a rebuild of [3e00be2](https://github.com/aria2/aria2/commit/3e00be26e8f8fe44c7344a3e8026031a99b22400)

Hello, can you tell me how you did that? I am trying to do the same thing. I have one aria2c seeding on one host and another aria2c trying to download on another host. However, it seems that both hosts don't know each other and there is no data transmission.

This is my configure file.

```

bt-exclude-tracker="*"
bt-external-ip=127.0.0.1

dht-listen-port=3074
enable-dht=true
enable-peer-exchange=true
listen-port=3074

seed-ratio=0.0

peer-id-prefix=""
user-agent=""

summary-interval=0
```

The output of `ifconfig`:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.3.16  netmask 255.240.0.0  broadcast 172.31.255.255
        inet6 fe80::9e:6bff:feec:fe57  prefixlen 64  scopeid 0x20<link>
        ether 02:9e:6b:ec:fe:57  txqueuelen 1000  (Ethernet)
        RX packets 32254  bytes 19977538 (19.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 29924  bytes 4629751 (4.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.1.1  netmask 255.255.255.0  broadcast 10.10.1.255
        inet6 fe80::c7:d6ff:fe56:5bb7  prefixlen 64  scopeid 0x20<link>
        ether 02:c7:d6:56:5b:b7  txqueuelen 1000  (Ethernet)
        RX packets 15365  bytes 160105257 (160.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15063  bytes 1387862 (1.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 6785  bytes 977827 (977.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6785  bytes 977827 (977.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

The two hosts are connected by a single link directly.

**Comment by ArtemGr** [comment]
Example transferring a file with aria2 and https://github.com/casey/intermodal

On a server:

    cargo install -f imdl
    imdl torrent create --input foobar
    imdl torrent show --input foobar.torrent
    imdl torrent verify --input foobar.torrent --content foobar
    imdl torrent link --input foobar.torrent
    # copy the magnet link printed!

    aria2c --seed-ratio=0.0 --check-integrity foobar.torrent

On a client:

    aria2c --check-integrity '-paste-magnet-link-here-'

**Comment by SSSSeb** [comment]
thank you very much for this. I will evaluate switching all my bttracker logic and torrent file creation following the precise steps you proposed above. I am so glad switching some code from python2 to rust :-)
