### ISSUE TITLE
Question/problem: Conf file not loaded ?

### ISSUE THREAD

**Issue by Cyberoliv** [aria2/aria2#664]
Hi,

I own a raspberry pi 3 and installed aria2
When I download, all the options are the default options (for exemple ports for RCP and destination dir)
My conf file is located in /home/pi/.aria2/aria2.conf
(My user is pi) and I ran a sudo aria2c --conf-path=/home/pi/.aria2/aria2.conf
Nothing on screen, no error, no ok...
But when I download, my options seem not to be loaded

Any ideas ?

Regards,

Oliver

**Comment by tatsuhiro-t** [comment]
It works for me.  Check the patch is correct, and options are correctly written in the file.  Make sure that options are not really loaded.  Some options are very subtle, and you may not notice the change they produce.

**Comment by Cyberoliv** [comment]
Oh... I had one mistake in one option....
Correct conf file, loaded, it works !

thanks :+1:
