### ISSUE TITLE
Stop using paths.d for MacOS X build

### ISSUE THREAD

**Issue by tcely** [aria2/aria2#671]
I found #159 where the decision to use /etc/paths.d/aria2c was mentioned.

I'd prefer to avoid this since aria2c is only a single binary, where things like git have many. I don't need yet another addition to my $PATH when a symbolic link will do just as well.

For now, I've done this manually on my system.

$ sudo rm /etc/paths.d/arai2c
$ sudo ln -vs ../aria2/bin/aria2c /usr/local/bin

$ ls -l /usr/local/bin/aria2c
lrwxr-xr-x  1 root  wheel  19 Jun  5 16:23 /usr/local/bin/aria2c -> ../aria2/bin/aria2c

**Comment by nmaier** [comment]
You might not like it, but other users like having aria2 in their path after installation. As you did yourself, you can remove the paths.d entry and symlink if you want for yourself, or build aria2 yourself in the first place.

There is also a reason for not installing directly in /usr/local/bin, and that is to avoid interference with brew, which is quite popular (at least among the crowd that is likely to use the terminal at all)

**Comment by tcely** [comment]
The brew Formula doesn't appear to specify anything in /usr/local/bin.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/aria2.rb

We are still dealing with a single symbolic link either way. Adding an entire directory for a single binary is still wasteful.
