### ISSUE TITLE
Post hook script and socks5 proxy

### ISSUE THREAD

**Issue by rexdf** [aria2/aria2#672]
Is there a way to support argument like `--after-script="/home/usr/upload.sh"` which will execute `/home/usr/upload.sh` when download is complete?   Maybe `int system( const char *command )` in `<stdlib.h>` is a simple choice.  Maybe we need `--enable-after-script=false` for default.

[Shadowsocks](https://github.com/shadowsocks/shadowsocks) which uses socks5 is widely used in China except for VPN. It runs on almost all kind of devices.  A great deal of programming sites are blocked in China by GFW. Such as golang.org chromium.org android.com. I know that we can convert socks5 to http proxy, but we need different software on different platform. How about supporting socks5 in aria2?

**Comment by tatsuhiro-t** [comment]
Check out http://aria2.github.io/manual/en/html/aria2c.html#cmdoption--on-download-complete

aria2 does not support socks5 at the moment.  There are some software to replace regular socket functions with socks5 aware ones to transparently enable socks on the fly.  I don't use them these days, so I'm not sure it still works.

**Comment by rexdf** [comment]
Thanks so much.

**Comment by mengyyy** [comment]
you can try this   [pproxy](https://pypi.python.org/pypi/pproxy/1.2.1) need python3
example:

http proxy listen at 127.0.0.1:8800
remote socks5 proxy is 123.123.123.123:8899 auth is (username password)

pproxy  -i http://127.0.0.1:8800 -r socks://123.123.123.123:8899#username:password
