### ISSUE TITLE
The option --download-result doesn't work.

### ISSUE THREAD

**Issue by samtron1412** [aria2/aria2#673]
I tried to change the download result by the option `--download-result`, but it doesn't work.

Three commands below give me the same download result.

```
aria2c --download-result=hide http://mirror.is.co.za/mirrors/linuxmint.com/iso//stable/17.3/linuxmint-17.3-cinnamon-64bit.iso

aria2c --download-result=full http://mirror.is.co.za/mirrors/linuxmint.com/iso//stable/17.3/linuxmint-17.3-cinnamon-64bit.iso

aria2c --download-result=default http://mirror.is.co.za/mirrors/linuxmint.com/iso//stable/17.3/linuxmint-17.3-cinnamon-64bit.iso
```

**aria2 version 1.23.0**

My configuration `aria2.conf`

```
continue
dir=.
file-allocation=none
max-connection-per-server=8
min-split-size=5M
enable-http-pipelining=true
```

**Comment by tatsuhiro-t** [comment]
It works for me.  Did you mean --summary-interval?

**Comment by samtron1412** [comment]
I saw this in the manual:
![2016-06-09-12 03 58](https://cloud.githubusercontent.com/assets/2152084/15942717/6d43e38e-2e3a-11e6-8805-4284583a3131.png)

But when I ran three commands with different values of `<OPT>`, it showed me the same download result like this:
![2016-06-09-12 07 13](https://cloud.githubusercontent.com/assets/2152084/15942863/2fc7d94c-2e3b-11e6-815b-9b56ed9e97a3.png)

**Comment by tatsuhiro-t** [comment]
It is not download result.  The download result is shown when aria2 exits.

**Comment by samtron1412** [comment]
I got it, my bad! Thanks for your replies.

**Comment by smac89** [comment]
Thanks for the clarification
