### ISSUE TITLE
(Compatibility) chocolatey package

### ISSUE THREAD

**Issue by dtgm** [aria2/aria2#677]
Just a request not to change your method for constructing filenames for Windows when issuing builds, or if you do, I would appreciate a shoutout.

Details: I maintain a chocolatey package for aria2 at https://chocolatey.org/packages/aria2/ If you are not familiar, chocolatey is a fork of nuget for installed programs, with improvements to be a package manager like `apt-get`.

It does this by installing from a defined URL within the pkg, which is immutable. So if the URL changes, the pkg no longer works. (see https://chocolatey.org/packages/aria2/#files and click "show" to see script used)

I automatically build the packages by scraping https://github.com/aria2/aria2/releases and getting the version from the filename of the zip, e.g. `/aria2-1.23.0-win-64bit-build1.zip`

I previously was only using "aria2-__1.23.0__-win-64bit-build1.zip" since it appeared buildX was consistently `build1` ... however you replaced it with build2 which broke the pkg since build1 was no longer present. I understand why you want to just update the single file than issue a new version release and I resolved that by now including the build number in my version so `1.23.0.2`

So if the filename changes from that format, it may break my regex to obtain the proper version and install URL.

ref: https://github.com/dtgm/chocolatey-packages/issues/215

**Comment by tatsuhiro-t** [comment]
We changed URI since they are different.
Perhaps, you can parameterize the build<N> as well as version number?

**Comment by dtgm** [comment]
I agree changing the URI was the right move. I use checksum to verify the binary hasn't changed during install of all programs I maintain so programs that silently update bins will fail.

Thanks for the suggestion, I parameterized the build number to try to anticipate if you decide to leave out "build#".

`aria2-1.24.0-win-64bit-build1.zip`
will use version string `1.24.0.1`
`aria2-1.24.0-win-64bit.zip`
will use version string `1.24.0`

Actually, it's a bit dumber than that; it matches 'd\d', so letter "d" followed by "digit".... I guess I should improve the regex in case you change to using a hyphen or require double digits in your build, but I expect that to be unlikely.

FYI, there have been 3,319 installs of this package since it was first created in 2013 so if you're interested, you may want to update your Readme with a section on how to install binary on various platforms. On windows with chocolatey it would be
`choco install aria2`

I think that's also the debian package name (we require packages to be same name as those on other package managers like Debian/Arch/etc).

Also, I was wrong above. I check subpath __latest__ daily (https://github.com/aria2/aria2/releases/latest) so if you mark a release a prerelease in github, a corresponding chocolatey package won't be built.
