### ISSUE TITLE
Error on Win32

### ISSUE THREAD

**Issue by Nullfati** [aria2/aria2#678]
I have that error on Windows 10 x64 with aria2c.exe x32:
[WARN] [SelectEventPoll.cc:235] The number of file descriptor exceeded FD_SETSIZE. Download may slow down or fail.
How fix this error?

**Comment by tatsuhiro-t** [comment]
Do you have lots of concurrent downloads?  It looks like the aria2 process ran out of file descriptor (sockets + opened file), which is capped by 1024.  Try to reduce the number of downloads.

**Comment by Nullfati** [comment]
Yes, I have lots of concurrent downloads because I test aria2 with a lots of downloads. Can you fix this problem in next vesion?

**Comment by tatsuhiro-t** [comment]
The next version, v1.24.0 is released today, and we'd like to avoid last minutes change.

If you can build aria2, try increase value of FD_SETSIZE macro:
https://github.com/aria2/aria2/blob/09e7cfc4c088b239050ca8ec1a8da18e208ae669/src/common.h#L61

**Comment by Nullfati** [comment]
Can you do auto select of value?

**Comment by tatsuhiro-t** [comment]
Based on what?

FD_SETSIZE is compile time constant.  You cannot change it in runtime.

**Comment by Nullfati** [comment]
I read that for Windows fd_setsize can be changed and more then 1024 but for Linux hardcore 1024.
How compile aria2 for windows?

**Comment by tatsuhiro-t** [comment]
We use epoll for Linux, which is not limited by 1024 file descriptor.

We have Dockerfile.mingw to compile windows binary.  It clones master branch, so you have to change it to your copy to include the change.

**Comment by Nullfati** [comment]
Okey. Thanks.
Have any idea how to behave aria2 if I shall increase FD_SETSIZE?

**Comment by tatsuhiro-t** [comment]
I made a commit to increase FD_SETSIZE to 32768.
Now you can build aria2c windows binary using our stock Dockerfile.mingw.
Please test the build and see that it does not show the error message you encountered before.

**Comment by Nullfati** [comment]
Okay.
In the near future results.

**Comment by Nullfati** [comment]
I tested aria 2 with FD_SETSIZE 32768, and after 2 days work with 20 torrents all okay. No have any error.

**Comment by tatsuhiro-t** [comment]
Thank you.  I think this issue has been fixed.
