### ISSUE TITLE
torrent metadata not transferring

### ISSUE THREAD

**Issue by rbos** [aria2/aria2#681]
If I generate a smaller torrent (using py3createtorrent), I'm able to distribute metadata and download the file, but when I create a much larger one, metadata won't transfer.

seeding/downloading notepad++ like so, I can download it, very small download. Here are the commands I'm using. It downloads the metadata and saves a .torrent file.

seed: aria2c NotepadPlusPlus#6.9.2.torrent --file-allocation=none --seed-ratio=0 --bt-enable-lpd=true --bt-seed-unverified=true --bt-exclude-tracker=* --bt-tracker=[redact]/announce --log-level=notice

peer: aria2c "magnet:?xt=urn:btih:3404428114D15A2F8F539302961B86831D2B1FD4&dn" -V --bt-save-metadata=true --bt-stop-timeout=60 --bt-enable-lpd=true --allow-overwrite=true --seed-time=0 --file-allocation=none --bt-tracker=[redact]/announce

However, if I do a much larger software package, 7 gigabytes and 14,000 files about, using the same syntax, it will not download the metadata for the torrent. It shows eg, CN:1 and SD:1 on console, so I'm quite sure I've got the hash correct for the magnet link. 

If instead of using a magnet link, I copy the torrent file to the peer and call aria2c substituting that in for the magnet link, it's able to download.

I don't think I'm doing anything wrong. Could this be an aria2c bug?

**Comment by rbos** [comment]
I did another test with a 1.8 gigabyte download (225*8192kb chunks), and it's transferring metadata fine to my peer test and completing the full download.

**Comment by tatsuhiro-t** [comment]
Can you provide aria2 log file for both seed and peer?
It seems they can find each other, but metadata is not transferred for some reason.

**Comment by rbos** [comment]
Okay, I did three tests; sas with magnet and torrent file, notepad++ with magnet and torrent file. Logs attached. I hope it's clear.

Weird, I can't attach a zip. Well, easy fix.

http://www.sfu.ca/~rbos/aria2clogs.zip

**Comment by tatsuhiro-t** [comment]
Thank you.  The log helps us a lot.
It turns out that aria2 only allowed 1MiB metadata.  Your metadata for large case exceeded that limit.
With f6f672f, we've increased the maximum metadata size.  It should work now.

**Comment by rbos** [comment]
Cool. I'll test it when 1.25.0 comes out. :)

**Comment by rbos** [comment]
Are there dev builds anywhere for Windows that I can use to test? I've given a crack at cross-compiling, but I'd have to build a bunch of other libraries for win64 and that's a little more effort than I'd like to go to.

**Comment by rbos** [comment]
Hi,

I finally got around to cross-compiling the dependency libraries for aria2c and compiling a static Windows executable.

Metadata transferred without issue with my SAS test torrent. Thanks!
