### ISSUE TITLE
Sparse corrupted files

### ISSUE THREAD

**Issue by benfelin** [aria2/aria2#682]
I proceeded massive downloads (70,731 gzipped files - 819GB in total) from a private FTP server with the following command:
	aria2c -i reporfiles.all -c -j25 -x5 -s5 -k64M --save-session=reportfiles.all

reportfiles.all file contains the path to the files. Eg:
	ftp://XXXXXXX:XXXXXXX@private-ftpserver.com/dir1/dir2/dir3/dir4/file987.gz

aria2 (version 1.13.0) downloaded all the files without throwing a single error and reportfiles.all ended up empty, however, I got 69 corrupted gzipped file ('unexpected end of file') and also noticed that the temporary aria2-suffixed file are not deleted. I believe that the download of these files is complete but not 'finalized'.
At this point I can't figure the reason of this 0.1% failure: The private FTP server (flacky network?) or my settings (it works fine for 99% of the downloads though?).

**Comment by tatsuhiro-t** [comment]
This is related to --max-download-result option.
http://aria2.github.io/manual/en/html/aria2c.html#cmdoption--max-download-result

aria2 keeps all completed/failed downloads in the memory, and saves it as session file.  By default, aria2 remembers 1000 latest downloads.  If the limit reached, the oldest entry is removed.  This means that failed download is kicked from memory if the number of downloads is larger than the limit.  In your case, you have more than 70,000 downloads, and if these FTP downloads are not in the last 1000 downloads, they are just gone, and not saved in the session file.  The purpose of --max-download-result is reduce memory usage.  I suggest to increase the limit using that option.

It might be better to add new functionality to keep failed downloads in memory regardless of --max-download-result to save them in session file.

**Comment by tatsuhiro-t** [comment]
55f311a adds --keep-unfinished-download-result to keep unfinished download in memory, and they are saved in --save-session.

**Comment by nmaier** [comment]
@tatsuhiro-t I actually think it would be a good idea to default=true this new option. Most users will be interested in keeping unfinished downloads (in their session files), rather than keeping finished ones for starters, so I think default=true would be the sane, "obvious" default.

Actually, it might be a good idea to change max-download-result to only ever consider finished downloads when purging (not errored, not seeding), and remove the --keep-unfinished-download-result option again... my two cents.

**Comment by tatsuhiro-t** [comment]
From the point of user, yeah, you are right.  Error downloads should be kept by default.
Still I'm concerned unbounded memory, so I'd like to leave --keep-unfinished-download-result option.
Perhaps, we should mention this in --max-download-result option.

**Comment by nmaier** [comment]
It's not exactly unbound... You cannot amplify a single download into infinite download results. So it is effectively bound by the number of downloads in the session. If you add 70000 downloads, you should expect to get quite a few download results ;)

Option or not, the default should be to keep unfinished downloads (at least when a session file is confirgured)

**Comment by tatsuhiro-t** [comment]
I say unbounded because we have RPC mode.  User can throw any number of downloads to it.

**Comment by tatsuhiro-t** [comment]
ae78d7f enables --keep-unfinished-download result by default.
