### ISSUE TITLE
aria2 http/ftp download stuck at 0KB/s even with lowest-speed-limit set

### ISSUE THREAD

**Issue by fawkes** [aria2/aria2#686]
I use aria2 to download multiple files using ftp or http. This bug has appeared after version **1.15**. I tested this issue with version **1.18**, **1.23** and **1.24** . A while after starting aria2, it decides to stop downloading and gets stuck at 0 KB/s although i have set **lowest-speed-limit=1K**. Sometimes this issue happens within minutes of starting the download and sometimes it takes hours for it to happen. But when i set it to download files at night, every morning i find it stuck at 0 KB/s. This issue happens with and without setting **max-overall-download-limit** parameter.

Here are some more info that might help:

- parameters i use: **-j2 -x8 -s4 -c -m0 --retry-wait=600 -i ~/shared/urls.txt -d ~/mb1/downloads/ --deferred-input=true --download-result=full --lowest-speed-limit=1K --log-level=error -laria.log**
- urls.txt contains urls for multiple files to be downloaded.
- The computer executing aria2 has one IPv4 address and is behind NAT.
- I haven't tested this with torrents
- When connection speed drops below the value set for **lowest-speed-limit**, aria2 correctly stops downloading and continues with the next file but sometimes it doesn't happen and it gets stuck.
- Running aria2 with or without sudo permissions doesn't change the issue
- This happens both on **Ubuntu Server 14.04 x64** and **Raspbian Jessie** (haven't tested another OS)

**Comment by tatsuhiro-t** [comment]
I make 2 commits to try to fix this issue.
It is still strange since timeout should be triggered where there is no network activity.

**Comment by fawkes** [comment]
thank you so much for your fast response. I'll get the latest code, build and test it for couple of days and will report the results

**Comment by fawkes** [comment]
I've tested it during the past 2 days and it doesn't seem to be happening anymore. Thanks for the fix.

**Comment by tatsuhiro-t** [comment]
Thank you for confirmation.  Let's close the issue.
