### ISSUE TITLE
Aria2 RPC freezes on adding URI when there is no internet

### ISSUE THREAD

**Issue by sky93** [aria2/aria2#691]
Hello,

I ran Aria2c as RPC mode. In no-internet environment (for example when server accidentally has no internet) when I add a URI, Aria2 adds it fast and I get `gid` instantly (also for torrents) but for the next 1-2 minutes RPC will become inaccessible at all And I can't send/receive any requests to port 6800.

I changed `--timeout=` and `--connect-timeout=` tto but no luck.

This is the log Aria2 gives to me:

```
06/26 16:38:09 [ERROR] CUID#10 - Download aborted. URI=http://ipv4.download.thinkbroadband.com/1GB.zip
Exception: [AbstractCommand.cc:345] errorCode=19 URI=http://ipv4.download.thinkbroadband.com/1GB.zip
  -> [NameResolver.cc:60] errorCode=19 Failed to resolve the hostname ipv4.download.thinkbroadband.com, cause: Name or service not known

06/26 16:38:09 [NOTICE] Download GID#a3699f95c6dccfd8 not complete:
```

How can I fix this issue? Thanks.

**Comment by tatsuhiro-t** [comment]
Are you using asynchronous DNS (--async-dns=true) ?  If not, aria2 uses blocking version of DNS, which may take long time before it failed.  In this case, no timeout is configured for DNS.

**Comment by tatsuhiro-t** [comment]
It means that it lacks asynchronous DNS support.
Try to build aria2 with c-ares library.

**Comment by sky93** [comment]
Nice. I built aria2 with c-ares library and changed `async-dns` to `false`. It's now working without any problem. Thanks

**Comment by tatsuhiro-t** [comment]
You should use async-dns=true to avoid blocking.
2016/06/28 7:17 "Sepehr Mohaghegh" <notifications@github.com>:

**Comment by sky93** [comment]
Yes you said this. But I set it to true and I didn't see any difference. When I changed it ti false, everything went okay :/ I don't know why. I tried it several times.
