### ISSUE TITLE
aria2mon if us rpc-secret hava bug

### ISSUE THREAD

**Issue by hepha** [aria2/aria2#700]
Hello : If you turn rpc-secret set the aria mon will be turned off no error

`aria2c --enable-rpc=true --input-file=/home/hepha/.aria2/download.session --save-session=/home/hepha/.aria2/download.session --disable-ipv6=true --rpc-secret=xxx`
`/usr/share/doc/aria2/xmlrpc/aria2mon`

> /usr/lib/ruby/2.3.0/xmlrpc/client.rb:272:in `call': Unauthorized (XMLRPC::FaultException)
> 	from /home/hepha/bin/rpc:92:in `<main>'

 `aria2c --enable-rpc=true --input-file=/home/hepha/.aria2/download.session --save-session=/home/hepha/.aria2/download.session --disable-ipv6=true `
> -- Download Progress --
> GID#9f382a1df32edbbf SIZE:22.1MiB/749.0MiB(2%) CN:5 SPD:11.1MiB/s ETA:1m5s
> 
>  File:/mnt/download/archlinux-2016.07.01-dual.iso
> --------------------------------------------------------------------------------

`aria2c -v`

> aria2 version 1.24.0
> Copyright (C) 2006, 2015 Tatsuhiro Tsujikawa
> 
> 
> ** Configuration **
> Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
> Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
> Libraries: zlib/1.2.8 libxml2/2.9.4 sqlite3/3.13.0 GnuTLS/3.4.13 nettle GMP/6.1.0 c-ares/1.11.0 libssh2/1.7.0
> Compiler: gcc 6.1.1 20160602
>   built by   x86_64-pc-linux-gnu
>   on         Jun 15 2016 13:18:23
> System: Linux 4.6.3-1-ck #1 SMP PREEMPT Sat Jun 25 10:55:41 EDT 2016 x86_64
OS : ARCH

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.
Fix committed via a9fe783

**Comment by hepha** [comment]
Thank you fix
