### ISSUE TITLE
Issue compiling on Fedora (gnutls /libssh2) ?

### ISSUE THREAD

**Issue by aljazzair** [aria2/aria2#705]
Hello,
I am trying to install aria2c 1.25 from sources on Fedora 24. Followed the instructions and installed required packages and some.

./configure shows the following warnings :

>
checking for LIBGNUTLS... 
no configure: WARNING: No package 'gnutls' found
(...)
>
checking for LIBSSH2... 
no configure: WARNING: No package 'libssh2' found

Yet it seems both are installed:

>dnf list installed  | grep gnutls
gnutls.x86_64                          3.4.14-1.fc24            @updates
gnutls-dane.x86_64                     3.4.14-1.fc24            @updates
gnutls-utils.x86_64                    3.4.14-1.fc24            @updates 

> dnf list installed  | grep libssh2
libssh2.x86_64                         1.7.0-5.fc24             @koji-override-0`

And installation completes:
> aria2c -v
aria2 version 1.25.0
Copyright (C) 2006, 2015 Tatsuhiro Tsujikawa
(...)
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 libxml2/2.9.3 sqlite3/3.13.0 OpenSSL/1.0.2h c-ares/1.11.0
Compiler: gcc 6.1.1 20160621 (Red Hat 6.1.1-3)
  built by   x86_64-pc-linux-gnu
  on         Jul 15 2016 21:21:35
System: Linux 4.6.3-300.fc24.x86_64 #1 SMP Fri Jun 24 20:52:41 UTC 2016 x86_64
(...)

So are gnutls libssh2 optional, or are some aria2 features disabled since they're not detected when compiling?

PS : Thank you for this wonderful program :+1: 

Full log attached
[aria2.bugreport.txt](https://github.com/aria2/aria2/files/366836/aria2.bugreport.txt)

**Comment by q3aql** [comment]
@aljazzair For compiling, you need install "gnutls-devel" and "libssh2-devel" too.

**Comment by aljazzair** [comment]
Thank you for your feedback. After installing these packages and re-compiling, there were no more warnings and the installation result is:

>aria2c -v
aria2 version 1.25.0
Copyright (C) 2006, 2015 Tatsuhiro Tsujikawa
(...)
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 libxml2/2.9.3 sqlite3/3.13.0 GnuTLS/3.4.14 nettle GMP/6.1.0 c-ares/1.11.0 libssh2/1.7.0
Compiler: gcc 6.1.1 20160621 (Red Hat 6.1.1-3)
  built by   x86_64-pc-linux-gnu
  on         Jul 15 2016 23:08:26
System: Linux 4.6.3-300.fc24.x86_64 #1 SMP Fri Jun 24 20:52:41 UTC 2016 x86_64


So SFTP is now enabled .
Thanks again for your kind feedback.

**Comment by tatsuhiro-t** [comment]
Thank you all.  Let's close the issue.
