### ISSUE TITLE
Link failure with ld.gold, -Wl,--as-needed and --enable-libaria2

### ISSUE THREAD

**Issue by mgorny** [aria2/aria2#707]
When aria2 is built with `--enable-libaria2` most of the relevant code is built into the shared library. However, `src/Makefile.am` puts almost all linked dependency libraries into `LDADD` which applies to executables only. Therefore, most of the NEEDED entries land in the executable rather than the library.

This has two consequences:
1. The library lacks proper dependencies and therefore can't be used by a program unless it links to all its dependency libraries directly.
2. If aria2c is linked using ld.gold (the new binutils linker) with `-Wl,--as-needed`, the linker detects that aria2c executable does not use most of the passed `-l` libraries and removes them. As a result, aria2c is broken since neither the program nor the library links to necessary dependency libraries.

I think the correct solution here is to move all the dependency libraries from `LDADD` to `libaria2_la_LIBADD`.

**Comment by tatsuhiro-t** [comment]
Thank you.  I made a commit as you suggested.  See 3220989f56818a4aa949a026453b3b7bd97c9ca9
