### ISSUE TITLE
Option's definitions and information

### ISSUE THREAD

**Issue by devgianlu** [aria2/aria2#713]
Basically, I'd like to have a way to known if a certain option (say --log-level) is a boolean value, integer value or multiple-choice value. All that to be able to set those options through some code. For example, if I should let the user select the log level, I can display him a list (debug, info, notice, warn, error) and let him pick one. All that without doing it manually for each option in the documentation, but with a method that returns all I need. Also a source file on the documentation would be enough. (As now, I wrote a parser for the source file of the documentation but it isn't bug-proof).
Hope someone understands what I'm trying to say. Thanks

**Comment by tatsuhiro-t** [comment]
If I understand correctly, you want new RPC method to send back a client that option definitions which describes which value or type option takes, say, boolean, or multi-value, right?
And now you are doing this by parsing documentation, but you think it is not good enough?

**Comment by Gianlu01** [comment]
Yes! It's exactly want I meant.

**Comment by tatsuhiro-t** [comment]
By the way, we have https://github.com/aria2/aria2/blob/master/doc/bash_completion/make_bash_completion.py to generate bash completion from `aria2c --help#all`, and there we handles options which takes multiple-choices, and boolean values.

**Comment by Gianlu01** [comment]
Seems interesting, but I can't use this from RPC. Right?

**Comment by tatsuhiro-t** [comment]
Yes.
Still you can do similar things to automatically generate your source code.
