### ISSUE TITLE
Is there any notification when a task add to waiting list?

### ISSUE THREAD

**Issue by xjbeta** [aria2/aria2#714]
And when i use "tellStatus", how to use "key" to block the urls in files. If i set "max-connection-per-server"=16, the urls cause the json data too big.

Sorry for my bad english.  :]

**Comment by tatsuhiro-t** [comment]
There is no notification when item is added to waiting list.

keys is array of top level name contained in aria2.tellStatus reply.  You can add all names that you want in a response.  So if you don't want urls, and add all names you want in keys other than `files`.

**Comment by xjbeta** [comment]
Thanks, i hope i can receive a notification when a task add to waiting list or paused list. 
Use tellactive for every second is too much trouble.

**Comment by xjbeta** [comment]
####   I think you can change the notification json 
**brfore**
`{
  "jsonrpc" : "2.0",
  "method" : "aria2.onDownloadStart",
  "params" : [
    {
      "gid" : "xxxxxx"
    }
  ]
}`


**after**
`{
  "jsonrpc" : "2.0",
  "method" : "aria2.onDownloadStatusChange",
  "params" : [
    {
      "gid" : "xxxxxx"
      "status": {"before": "active", "after": "pause" 
}
    }
  ]
}`

#### Can you prvide the date when a task status last changed, or other key you sort the tasklist.
