### ISSUE TITLE
xmlrpc.client problem

### ISSUE THREAD

**Issue by alireza-amirsamimi** [aria2/aria2#718]
Hello
When I download a link from dropbox by terminal (in ubuntu 16.04 and archlinux) with
--referer
and
--load-cookies
every thing is ok!
but when I download with xmlrpc.client (python3 script) with  referer and load-cookies aria2 won't download the file and after a minute aria is returning "error 403"

P S : I started to write a GUI with PyQt5 for aria2
https://github.com/alireza-amirsamimi/persepolis

Thanks for aria2c! it's great

**Comment by tatsuhiro-t** [comment]
load-cookies cannot be used in RPC call.  The workaround is directly passing cookie header field using --header option.

**Comment by alireza-amirsamimi** [comment]
I searched and tested someting but I coudn't handle the problem
How can I directly pass cookie header field (using header option)
Can you say an example please
thanks

**Comment by tatsuhiro-t** [comment]
Assuming you know how to set option in RPC method, I'll show how to use --header option for cookies.
--header option takes a form "<NAME>: <VALUE>", where <NAME> is a HTTP header field name, and <VALUE> is its value.  For cookies, <NAME> is "cookie", and value is value of cookie, which depends on your real cookie value.  For example, to send cookie, named as "foo", and its value "bar", do this:

```
--header "foo: bar"
```

**Comment by alireza-amirsamimi** [comment]
thanks
according to this page :
https://aria2.github.io/manual/en/html/aria2c.html#id6
and your guides I wrote codes to make headers
for example this (GMail):
`'header' : ['S:gmail:n-zOX-RIUN7UCoXQIkADdg', 'COMPASS:gmail:CiUACWuJV5D7Jt8e5fm28LTKRPGAm9NC0N7nKMscPXQymLT5l58BEOu3gb0FGi4ACWuJV79JSEiKGAV-2SEWsCo6K7ueMc8N9o05ypgFhv98dLTFItmtUwANrA7P', 'AUTH_cns4indq8j8aat35shoqhf75dp1looe5:15816067378455350374|1469786400000|99sv1k9dfo7fbfimo5l5cbno0ppkd8id']`

or this (dropbox)
`'header' : ['uc_session:2nZ5ZL6jvRUWgLFXA54VFCmgopUdCd9QbYjKvOV6ti7X5y7DsQJXvfNB2vWqPFuS']`

but still not working same as before

**Comment by alireza-amirsamimi** [comment]
sorry!
I was made a mistake
It worked for gmail
but not worked for dropbox
I tried to download one of this files
https://www.dropbox.com/sh/vj4k3czj60jg7hf/AAAxGQJ8ZXRwlvFfeGUiQHG7a?dl=0&preview=1.file_and_folder_structure.mkv

**Comment by tatsuhiro-t** [comment]
Sanitized cookie value just in case.

Probably it has missing cookie values or expired, but I'm not sure since it is application specific.

**Comment by alireza-amirsamimi** [comment]
Thank you very much :)
I'll work on it.
