### ISSUE TITLE
Error: dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by sonic84** [aria2/aria2#739]
aria2c fails to launch on Mac OS X 10.11.6 and macOS 10.12.0 with error:

mac:~ admin$ /Users/admin/Downloads/aria2-1.26.1/bin/aria2c
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/admin/Downloads/aria2-1.26.1/bin/aria2c
  Reason: image not found
Trace/BPT trap: 5

aria2c version 1.19.0 works fine on both OS versions.

**Comment by nmaier** [comment]
That's using the released binary, right?

**Comment by nmaier** [comment]
hmmm... somehow libssh2 managed to pick up an openssl dependency that shouldn't be there

**Comment by nmaier** [comment]
yip, libssh now links openssl if you do not specify `--without-openssl`

**Comment by nmaier** [comment]
@sonic84 I updated the release dmg and tar as well

**Comment by sonic84** [comment]
Thank you very much!

-Sonic84
