### ISSUE TITLE
issue with peer-id-prefix

### ISSUE THREAD

**Issue by qwerty369** [aria2/aria2#740]
Just upgrade aria2 to 1.25.0 from 1.19.2
Can't download from [bakabt](https://bakabt.me) they have some kind of whitelist for torrent client so <code>--peer-id-prefix=-TR2820-</code> need to bypass but it not work as expected.

**Comment by tatsuhiro-t** [comment]
What is the expect result, and what did you got instead?

**Comment by qwerty369** [comment]
On 1.19 i can download from that site with <code>--peer-id-prefix=-TR2820-</code> with new version it just stuck after file allocation.

**Comment by tatsuhiro-t** [comment]
As far as I've tested, aria2 correctly sends peer ID based on --peer-id-prefix.

**Comment by qwerty369** [comment]
You're right compile new version on os x it run fine with same config file turn out firejail sandboxing is the culprit when async-dns=true, i'm sorry for bothering you.
