### ISSUE TITLE
feature request: clobber and/or filename when exists

### ISSUE THREAD

**Issue by shawnkhall** [aria2/aria2#742]
#709 resolves one naming problem for downloaded files, but leaves another: there's no clobber support. Skype, for example, always uses the same download filename (SkypeSetup.msi) so even in 1.26.1 I'll get SkypeSetup.1.msi when I download it using aria2 when a another file exists. I'd like to be able to use the same local filename, overwriting the existing SkypeSetup.msi if the new file has the same name.

Alternatively, it would be great if when running a script that calls aria2, it were possible to know what the downloaded filename is if the file is skipped as current. Again, with Skype, if SkypeSetup.msi already exists and is unchanged from my last run of aria2, it will not be downloaded again. But there are no log indications what the filename is for the file that was skipped, only the URL, which does me no good locally.

**Comment by tatsuhiro-t** [comment]
--allow-overwrite, perhaps?

**Comment by shawnkhall** [comment]
Thank you. allow-overwrite with conditional-get does allow clobber when the file at the URL is newer:
aria2c http://www.skype.com/go/getskype-msi --allow-overwrite=true --conditional-get=true

But it still doesn't output the local filename that was used. Is there a way to get the log or output table to display this somehow?
![no-filename](https://cloud.githubusercontent.com/assets/6037167/18566439/c6897bd8-7b48-11e6-872f-6e4011b49e46.png)

**Comment by tatsuhiro-t** [comment]
I'm ok to add NOTICE level logging for file name.
The above image looks a bit strange, since file name is missing after "Downlaod has already completed:" and "Download complete:".

**Comment by tatsuhiro-t** [comment]
It looks like a bug that file name is missing in these logs.

**Comment by tatsuhiro-t** [comment]
Fix committed via a31e73d

**Comment by tatsuhiro-t** [comment]
I was a bit confused, but I think the above commit fixes this issue.
