### ISSUE TITLE
Notification when download is finished

### ISSUE THREAD

**Issue by pingshunhuangalex** [aria2/aria2#746]
Is it possible to add a notification feature when a task finished downloading?

I found parameters like ```--on-bt-download-complete, --on-download-complete, --on-download-error, --on-download-pause, --on-download-start, --on-download-stop``` which should allow aria2 to trigger some scripts as notification, but I'm not sure how to achieve it... Am I in the right direction?

Could anyone throw me a tutorial on this, or maybe share some scripts with me if that's the way to go (I'm on Windows BTW)? Thanks

**Comment by xjbeta** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#json-rpc-over-websocket

try to use websocket

**Comment by pingshunhuangalex** [comment]
Thanks @xjbeta for the hints.

I'm sure ```aria2.onDownloadComplete(event), aria2.onDownloadError(event), aria2.onBtDownloadComplete(event)``` are the ones I'm after, but could you please give me an example on how to use these 3 command? I'm currently just using a config file and webui for aria2, not sure where and how these command can be fit into the process. Thanks.

**Comment by xjbeta** [comment]
You can try it in [WebSocket Terminal(Chrome app)](https://chrome.google.com/webstore/detail/dark-websocket-terminal/dmogdjmcpfaibncngoolgljgocdabhke?utm_source=chrome-ntp-icon) 

connect websocket of aria2
`/connect ws://localhost:12345/jsonrpc`

When the task finish you can receive the notification.

**Comment by pingshunhuangalex** [comment]
Cool. Thanks @xjbeta
