### ISSUE TITLE
rpc download problem from github

### ISSUE THREAD

**Issue by alireza-amirsamimi** [aria2/aria2#748]
Hello
I'm programmer of  persepolis download manager(https://github.com/alireza-amirsamimi/persepolis)  . and this download manager is a GUI for aria .

I have a problem when i download zip file from github with rpc .
for example :
assume that i want to download this link from github(aria2's source)
`https://github.com/aria2/aria2/archive/master.zip`
I can download it from terminal with this command
`aria2c https://github.com/aria2/aria2/archive/master.zip`
but when i want to download it with rpc then i get this error:

Resource not found

I have this problem only with few websites.

**Comment by tatsuhiro-t** [comment]
Did you check HTTP request path and header fields?  Are they correctly formatted?

**Comment by alireza-amirsamimi** [comment]
I think yes! because it works for the other sites(gmail , mediafire , and many sites)
I have this problem only with few websites (for example github)

**Comment by nmaier** [comment]
just tried via XMLRPC (via python3 `xmlrpc.client.ServerProxy`), with and without a token... Both worked.

Could you provide more details?

```text
In [5]: a.aria2.addUri(['https://github.com/aria2/aria2/archive/master.zip'])
Out[5]: '015d7c7eed598092'

09/24 11:57:17 [NOTICE] Download complete: /Users/.../dev/aria2/aria2-master.zip
```

```text
In [8]: a.aria2.addUri("token:test", ['https://github.com/aria2/aria2/archive/master.zip'])
Out[8]: 'bce1e93e501c81e0'

09/24 11:59:12 [NOTICE] Download complete: /Users/.../dev/aria2/aria2-master.1.zip
```

**Comment by alireza-amirsamimi** [comment]
Sorry!
It was my mistake!I was sended http-user whith https link!
problem solved
thanks for replays
