### ISSUE TITLE
Continue a download with a different URI

### ISSUE THREAD

**Issue by louy2** [aria2/aria2#752]
I am downloading from a server that expires the downloading URI every 8 hours, after which aria2 will raise error code 22.

I've inspected the control file and found that information of the download are still there, just unavailable through RPC interface. I wonder if I can continue the download with a different URI from the point recorded in aria2.

**Comment by tatsuhiro-t** [comment]
The control file does not contain URI, and aria2 just matches file name, so you can use different URI without problem.

**Comment by louy2** [comment]
Is there a way to do that via RPC or do I launch another process?

**Comment by louy2** [comment]
Okay, I see. I can just add URI. Strange that I've met "download successful" error in the past. I'll report if I meet them again.
