### ISSUE TITLE
Aria2c can't resolve hosts on WSL

### ISSUE THREAD

**Issue by Efreak** [aria2/aria2#755]
background: I'm trying to get apt-fast running under the windows subsystem for linux

I thought this was an issue with c-ares at first, since some other c-ares software does not work properly on WSL, but when compiling c-ares myself, the adig/ahost tools work fine, and aria2 still does not resolve hosts.

I've self-compiled libc-ares2 and libc-ares-dev from the official ubuntu sources on both trusty and xenial with the following commands:

```
apt-get build-dep c-ares aria2
apt-get source c-ares aria2
pushd c-ares*
debuild -r fakeroot --preserve-env
popd
dpkg -i *ares*.deb
pushd aria2*
debuild -r fakeroot --preserve-env
popd
dpkg -i *.deb
```

And this is the results I get:

```
root@Win10-vm-2:/home/Efreak/sources# c-ares-1.10.0/ahost google.com
google.com                              216.58.217.206
root@Win10-vm-2:/home/Efreak/sources# aria2-1.18.1/src/aria2c http://google.com

10/10 18:20:03 [ERROR] CUID#6 - Download aborted. URI=http://google.com
Exception: [AbstractCommand.cc:312] errorCode=19 URI=http://google.com
  -> [AbstractCommand.cc:739] errorCode=19 CUID#6 - Name resolution for google.com failed:No address returned
```

I've tried this in a WSL/trusty (default) environment under WSL, and I've also tried it in a VM that has had WSL updated to Xenial. Both have the same results, though xenial is using an newer version of aria2 (1.19.0)

I'll be checking the latest version of aria2c (1.27.1) shortly, but I don't expect that to change anything.

**Comment by Efreak** [comment]
Just finished compiling aria2c on trusty.
```
root@Win10-vm-2:/home/Efreak/sources/aria2-1.27.1# src/aria2c -v|head -n 1
aria2 version 1.27.1
root@Win10-vm-2:/home/Efreak/sources/aria2-1.27.1# src/aria2c http://google.com

10/10 18:58:10 [NOTICE] Downloading 1 item(s)

10/10 18:58:10 [ERROR] CUID#7 - Download aborted. URI=http://google.com
Exception: [AbstractCommand.cc:350] errorCode=19 URI=http://google.com
  -> [AbstractCommand.cc:800] errorCode=19 CUID#7 - Name resolution for google.com failed:No address returned
```

Xenial is still compiling, I'll update this post when it finishes.

**Comment by TruboXL** [comment]
Seems like the author's Android recommendation can be applied as a workaround for WSL too...

From [README.android](https://github.com/aria2/aria2/blob/master/README.android):
> Since Android does not have ``/etc/resolv.conf``, c-ares (asynchronous DNS resolver) is disabled by default. But name resolution is sometimes a little bit slow, so I recommend to enable c-ares. You can enable it using ``--async-dns`` and specify DNS servers using ``--async-dns-server`` option, like this:
>``--async-dns --async-dns-server=`getprop net.dns1`,`getprop net.dns2` ``

In WSL case, instead of missing `resolve.conf` which is present anyway, just that NETLINK sockets aren't there yet as mentioned in https://github.com/Microsoft/BashOnWindows/issues/69#issuecomment-208574945, so no support for async DNS.

I guess we have to use the slower ``--async-dns=false`` for now...

**Comment by TruboXL** [comment]
This has been fixed in Creators Update, you can close this bug now...

**Comment by tatsuhiro-t** [comment]
Thank you. Closing the issue.
