### ISSUE TITLE
Aria2 responding to pings

### ISSUE THREAD

**Issue by devgianlu** [aria2/aria2#762]
When I send a ping frame through WebSocket to aria2, it responds with an Invalid request error. By itercepting the packet going to aria2 it's clearly visible that no payload is sent. I wonder if it would be possible to have aria2 not to respond.

![screenshot](https://cloud.githubusercontent.com/assets/14827249/19922826/b41d767c-a0e4-11e6-80c7-3e131eae2da8.png)

**Comment by tatsuhiro-t** [comment]
How do you send PING frame?  As far as I know, no browser allows user to send WebSocket PING frame.  I'm talking about PING frame described in RFC 6455 https://tools.ietf.org/html/rfc6455#section-5.5.2

**Comment by Gianlu01** [comment]
Well, I'm using this library on Android: https://github.com/TakahikoKawasaki/nv-websocket-client

**Comment by tatsuhiro-t** [comment]
I haven't used that library, but did you send PING using like so:

```java
// Send a ping frame.
ws.sendPing("Are you there?");
```

**Comment by Gianlu01** [comment]
No, I'm using 
`ws.sendPing();`

**Comment by Gianlu01** [comment]
@tatsuhiro-t I've updated the original question clarifying some things.

**Comment by tatsuhiro-t** [comment]
Thank you.  I send suggested 6 bytes to aria2, but it responds Pong frame as expected.  In other words, aria2 correctly identified Ping frame, and responded Pong frame.  It didn't treat it as RPC request.  Could you confirm that WebSocket handshake is correctly made?

**Comment by Gianlu01** [comment]
Those are the handshake headers:
```
GET /jsonrpc HTTP/1.1
Host: 192.168.1.50:2789
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: cjBVPYYinUCbqaz5sAM2CA==
```
I should also note that I'm receiving correctly the PONG frame, but the error message is sent too.

**Comment by tatsuhiro-t** [comment]
I sent Ping frame to aria2, but I haven't got any error message.
Make sure that you only sent Ping frame.

**Comment by Gianlu01** [comment]
Can you tell me how you sent those bytes so I can test on my own and investigate further

**Comment by tatsuhiro-t** [comment]
I sent Ping frame using wslay library https://tatsuhiro-t.github.io/wslay/index.html
