### ISSUE TITLE
suffering from HTTPS not support error

### ISSUE THREAD

**Issue by adaaaaaa** [aria2/aria2#779]
[aria2.txt](https://github.com/aria2/aria2/files/605515/aria2.txt)

I find quite rare error like this kind in google. try to download two files from https,but failed .
anybody have some idea about this error?Please help...
-----------------------------------------------------------
already install openssl libssl-dev but also suffer the same error...

**Comment by tatsuhiro-t** [comment]
Could you give us the output of `aria2c -v`?

**Comment by adaaaaaa** [comment]
[aria2version.txt](https://github.com/aria2/aria2/files/618033/aria2version.txt)
like this? @tatsuhiro-t

**Comment by adaaaaaa** [comment]
using this command
aria2c -v | egrep 'Enabled Features|Libraries|Compiler|System'
[aria2ver.txt](https://github.com/aria2/aria2/files/618068/aria2ver.txt)

**Comment by Suncatcher** [comment]
And here is my output:

    aria2 version 1.29.0
    Copyright (C) 2006, 2016 Tatsuhiro Tsujikawa
    ...
    bla-bla-bla
    ...
    ** Configuration **
    Enabled Features: BitTorrent, GZip, Message Digest
    Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
    Libraries: zlib/1.2.8 libgcrypt/1.6.5
    Compiler: gcc 5.4.0 20160609
     built by   x86_64-pc-linux-gnu
     on         Nov 20 2016 15:07:06
    System: Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64

And I want to repeat my question from issue [361](https://github.com/aria2/aria2/issues/361):
**if Aria was built without HTTPS, then how can it be rebuilt to add this support?**

**Comment by tatsuhiro-t** [comment]
Both of you have missing HTTPS support.

Assuming you are using Linux, you need to install gnutls or openssl to enable HTTPS support.
We documented required libraries at https://aria2.github.io/manual/en/html/README.html#how-to-build

**Comment by Suncatcher** [comment]
>> Assuming you are using Linux, you need to install gnutls or openssl to enable HTTPS support.
We documented required libraries at https://aria2.github.io/manual/en/html/README.html#how-to-build

So I need to uninstall the current aria2 then build again (my previous build files are deleted already) and install again? There is no easy way?
How can I uninstall it? I didn't found anything in the documentation, and simple `apt-get purge` doesn't work.
Excuse me for dummy questions, I am still newbie in installing soft from sources.

**Comment by tatsuhiro-t** [comment]
Easiest way to install aria2 is package offered by Linux distribution.
Have you built aria2 by yourself?  Or did you install aria2 from package?
For Ubuntu or Debian, `apt-get install aria2` will install HTTPS enabled aria2.
I don't know much about other Linux distribution.

**Comment by adaaaaaa** [comment]
after 
1\fix missing libraries 
2\make uninstall aria2
3\./configure
4\make && make install
i successfully solve the problem!!haha!

**Comment by hzpc-joostk** [comment]
Have a look at this: https://github.com/timonier/aria2/

It installs the latest aria2 version as a Docker image and runs it in a temporary container. It just works, no need to think of dependencies and build on top of a minimal Alpine. 

The startup overhead (tested with `--version` is about 0.2 seconds on my system. The size overhead is about 11 MB as compared to a local build.
