### ISSUE TITLE
why can't I download file

### ISSUE THREAD

**Issue by leandroong** [aria2/aria2#781]
Normally, inside linux, i downloaded this file using syntax, wget https://codeload.github.com/lancethepants/tomatoware/zip/master
Q#: why Aria2 is having issue downloading it ?

**Comment by tatsuhiro-t** [comment]
It works for me.  What kind of error did you get?

**Comment by leandroong** [comment]
well, no error in gui, File that should be download is master,zip file with filesize of 575,836KB.

**Comment by leandroong** [comment]
Go to site: https://github.com/lancethepants/tomatoware and click "clone or download"

**Comment by leandroong** [comment]
I think file downloaded was not even written.

**Comment by leandroong** [comment]
I use this aria2 server, https://github.com/ziahamza/webui-aria2

**Comment by leandroong** [comment]
anyway, i do it manually, wget https://codeload.github.com/lancethepants/tomatoware/zip/master

**Comment by leandroong** [comment]
Error I got from terminal:
/media/myssd/aria2_downloads/test # aria2c https://codeload.github.com/lancethep
ants/tomatoware/zip/master

11/23 22:58:49 [NOTICE] Downloading 1 item(s)
[#07403f 0B/0B CN:1 DL:0B]
11/23 22:58:51 [ERROR] CUID#7 - Download aborted. URI=https://codeload.github.com/lancethepants/tomatoware/zip/master
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://codeload.github.com/lancethepants/tomatoware/zip/master
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

11/23 22:58:51 [NOTICE] Download GID#07403f4c95468029 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
07403f|ERR |       0B/s|https://codeload.github.com/lancethepants/tomatoware/zip/master

Status Legend:
(ERR):error occurred.

**Comment by tatsuhiro-t** [comment]
The error means that aria2 could not verify server's certificate.
Are you using aria2 on Linux?  If so, try --ca-certificate /etc/ssl/certs/ca-certificates.crt

**Comment by leandroong** [comment]
im running it from router using static binary compiled, source taken from https://github.com/lancethepants/aria2-mipsel-static
with aria2 server taken from https://github.com/ziahamza/webui-aria2

test run:
/media/myssd/aria2_downloads/test # aria2c https://codeload.github.com/lancethep
ants/tomatoware/zip/master -ca-certificate /etc/ssl/certs/ca-certificates.crt
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--continue'.
  -> [OptionHandlerImpl.cc:95] errorCode=1 continue must be either 'true' or 'false'.
Usage:
 -c, --continue[=true|false]  Continue downloading a partially downloaded
                              file. Use this option to resume a download
                              started by a web browser or another program
                              which downloads files sequentially from the
                              beginning. Currently this option is only
                              applicable to http(s)/ftp downloads.

                              Possible Values: true, false
                              Default: false
                              Tags: #basic, #http, #ftp
/media/myssd/aria2_downloads/test #

**Comment by leandroong** [comment]
my router dont have the certificate folder, only have 1 file /etc/ssl/openssl.cnf

**Comment by leandroong** [comment]
curious, wget works w/out any certification supplied

**Comment by tatsuhiro-t** [comment]
`--ca-certificate`, not `-ca-certificate`

**Comment by leandroong** [comment]
still error, i dont have certificate
/media/myssd/aria2_downloads/test # aria2c https://codeload.github.com/lancethep
ants/tomatoware/zip/master --ca-certificate /etc/ssl/certs/ca-certificates.crt

11/23 23:34:51 [NOTICE] Downloading 1 item(s)

11/23 23:34:51 [ERROR] Failed to load trusted CA certificates from /etc/ssl/cert                                                                                                                     s/ca-certificates.crt. Cause: error:02001002:system library:fopen:No such file o                                                                                                                     r directory
[#fda40c 0B/0B CN:1 DL:0B]
11/23 23:34:52 [ERROR] CUID#7 - Download aborted. URI=https://codeload.github.co                                                                                                                     m/lancethepants/tomatoware/zip/master
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://codeload.github.com/                                                                                                                     lancethepants/tomatoware/zip/master
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: unable to get l                                                                                                                     ocal issuer certificate

11/23 23:34:52 [NOTICE] Download GID#fda40c43ebecac65 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
fda40c|ERR |       0B/s|https://codeload.github.com/lancethepants/tomatoware/zip                                                                                                                     /master

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page                                                                                                                      for details.
/media/myssd/aria2_downloads/test #772

**Comment by leandroong** [comment]
how about adding option similar to wget, "--no-check-certificate" ?

/media/myssd/aria2_downloads/test # aria2c https://codeload.github.com/lancethep
ants/tomatoware/zip/master --no-check-certificate
aria2c: unrecognized option `--no-check-certificate'
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'.

Did you mean:
        --check-certificate
/media/myssd/aria2_downloads/test #

**Comment by tatsuhiro-t** [comment]
Looks like your system does not have the file.

> how about adding option similar to wget, "--no-check-certificate" ?

aria2 already has one: --check-certificate=false

But this is a last resort, since this is insecure.  Perhaps, it would be better to ask router OS (openwrt?) developer or community that where the CA certificate file is.

**Comment by tatsuhiro-t** [comment]
Well, aria2 help system actually suggested the option...

**Comment by leandroong** [comment]
--check-certificate=false working. Thanks.

**Comment by leandroong** [comment]
kindly close issue ....
