### ISSUE TITLE
-i - key doesnt work

### ISSUE THREAD

**Issue by pasha-zzz** [aria2/aria2#785]
aria2 version 1.27.1
Linux 4.4.32-rc1 #1580 Mon Nov 14 11:06:03 CET 2016 armv7l DD-WRT

even:
echo 'http://v4.ident.me'|aria2c -i -

says 'No files to download.' and exits.
Win32 (same version) works fine.
Other stuff work with pipe fine (wget, sed, grep etc.)

**Comment by pasha-zzz** [comment]
This works fine too:
echo 'http://v4.ident.me'>url.txt
aria2c -i ./url.txt

**Comment by tatsuhiro-t** [comment]
It works for me: echo "http://localhost" | aria2c -i-

**Comment by pasha-zzz** [comment]
Its a router with DD-WRT firmware. Some people checked on PC Linux (Debian) - works too. And I dont know how to debug this case. Even if log-level=debug there are no interesting info.
Maybe compile config...

** Configuration **
Enabled Features: BitTorrent, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 libxml2/2.9.4 OpenSSL/1.0.2j libssh2/1.7.0
Compiler: gcc 5.4.0
  built by   x86_64-pc-linux-gnu
  targetting arm-openwrt-linux-gnu
  on         Nov  2 2016 00:21:25

**Comment by pasha-zzz** [comment]
zyxmon user found solution: we must create /dev/stdin and all works `ln -s /proc/self/fd/0 /dev/stdin`

**Comment by tatsuhiro-t** [comment]
That is interesting.  Some OS does not have /dev/stdin.  Android is one of them.

**Comment by pasha-zzz** [comment]
And I check many utils and all works fine w/o this workaround. Only aria2 affected. Very strange.

**Comment by tatsuhiro-t** [comment]
We use /dev/stdin (and con for windows) explicitly in the source code, which causes this issue.  Using libc stdin could solve this issue.
