### ISSUE TITLE
Torrent downloads sometimes stop progressing

### ISSUE THREAD

**Issue by unsystemizer** [aria2/aria2#797]
v 1.29.0

With 1.29.0 I noticed that sometimes downloads just stop moving. For example today I found one torrent stuck at 66%. For now I simply CTRL+C and restart. 

It happens approximately in 5% of downloads. I didn't have this problem with older versions (maybe not 1.28, but 1.26 or 1.27, I skipped v1.28) on the same system. Except for Windows updates, I don't think anything else changed. 

```
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 expat/2.2.0 sqlite3/3.15.1 GMP/6.1.1 c-ares/1.12.0 libssh2/1.8.0
Compiler: mingw-w64 4.0 (stable) / gcc 6.1.1 20160815
  built by   x86_64-pc-linux-gnu
  targetting i686-w64-mingw32
  on         Nov 15 2016 23:12:47
System: Windows 6.2 (6.2)
```

**Comment by tatsuhiro-t** [comment]
BitTorrent code has not changed much since v1.27.0.  I'm interested in what's happening when download stuck.  Could you capture aria2 log when it occurs?

**Comment by unsystemizer** [comment]
Okay, I'll try. In the console, there's nothing but the usual, it's just that the numbers aren't moving.
I suspect that aria2c may stop when I accidentally press Enter or some other key (because I think that pressing enter sometimes helped), but I couldn't cause it to stop, I could only "unpause" it, and not always. 
Next time I spot this issue I'll try to capture more details.

**Comment by unsystemizer** [comment]
Ran into this again. Here's how it happens:
* Click with mouse anywhere in Windows console where aria2c is downloading a torrent
* Now download is stopped and (if you look with TCP viewer or tail the aria log), the download is paused - the log stops moving and aria's TCP connections gradually get closed.
* To unpause, put mouse in the console window and press ENTER. Now the log is being created again and network activity appears

I think this may be because a while ago I changed some console properties. Just in case someone wants to repro or comes across this, here's what they're like now.
![image](https://cloud.githubusercontent.com/assets/13134193/21055939/6f69fc92-be6e-11e6-9e43-c7079832365b.png)

Now I don't think this is an aria2c issue, so you may close this if you agree.

**Comment by tatsuhiro-t** [comment]
Thank you.  Agreed that it can pause aria2c.  Let's close the issue.

**Comment by unsystemizer** [comment]
I played with the Command Prompt properties and found that `Quick Edit Mode` can create this problem. 
If someone needs to have Quick Edit Mode enabled and doesn't want it to interfere with aria2c, they could consider submitting a patch. (I disabled mine as I didn't use it a lot).

How to disable Quick Edit Mode: https://msdn.microsoft.com/en-us/library/windows/desktop/ms686033(v=vs.85).aspx
