### ISSUE TITLE
Error tomatoware cross-compilation of aria2 version 1.30.0

### ISSUE THREAD

**Issue by leandroong** [aria2/aria2#804]
I got this error in my tomatoware cross-compilation of latest aria2 , version 1.30.0
...
mipsel-linux-g++: WARNING: unsafe header/library path used in cross-compilation: '/usr/lib/x86_64-linux-gnu'
/opt/tomatoware/mipsel-soft-mnt/usr/lib/gcc/mipsel-buildroot-linux-uclibc/6.1.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: warning: library search path "/usr/lib/x86_64-linux-gnu" is unsafe for cross-compilation
/opt/tomatoware/mipsel-soft-mnt/usr/lib/gcc/mipsel-buildroot-linux-uclibc/6.1.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libpthread.a when searching for -lpthread
/opt/tomatoware/mipsel-soft-mnt/usr/lib/gcc/mipsel-buildroot-linux-uclibc/6.1.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/librt.a when searching for -lrt
/opt/tomatoware/mipsel-soft-mnt/usr/lib/gcc/mipsel-buildroot-linux-uclibc/6.1.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: cannot find -llzma
/opt/tomatoware/mipsel-soft-mnt/usr/lib/gcc/mipsel-buildroot-linux-uclibc/6.1.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libdl.a when searching for -ldl
/opt/tomatoware/mipsel-soft-mnt/usr/lib/gcc/mipsel-buildroot-linux-uclibc/6.1.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libm.a when searching for -lm
/opt/tomatoware/mipsel-soft-mnt/usr/lib/gcc/mipsel-buildroot-linux-uclibc/6.1.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.a when searching for -lc
collect2: error: ld returned 1 exit status
..

Note: tomatoware cross-compilation for version 1.29.0 was a success.

**Comment by leandroong** [comment]
Here is script portion for compiling aria
...

######### ###################################################################
# ARIA2 # ###################################################################
######### ###################################################################
mkdir -p $SRC/aria2 && cd $SRC/aria2
$WGET https://github.com/aria2/aria2/releases/download/release-1.30.0/aria2-1.30.0.tar.gz
tar zxvf aria2-1.30.0.tar.gz
cd aria2-1.30.0

LDFLAGS="-zmuldefs $LDFLAGS" \
CPPFLAGS=$CPPFLAGS \
CFLAGS=$CFLAGS \
CXXFLAGS=$CXXFLAGS \
$CONFIGURE \
--enable-libaria2 \
--enable-static \
--disable-shared \
--without-libuv \
--without-appletls \
--without-gnutls \
--without-libnettle \
--without-libgmp \
--without-libgcrypt \
--without-libexpat \
--with-xml-prefix=$DEST \
ZLIB_CFLAGS="-I$DEST/include" \
ZLIB_LIBS="-L$DEST/lib" \
OPENSSL_CFLAGS="-I$DEST/include" \
OPENSSL_LIBS="-L$DEST/lib" \
SQLITE3_CFLAGS="-I$DEST/include" \
SQLITE3_LIBS="-L$DEST/lib" \
LIBCARES_CFLAGS="-I$DEST/include" \
LIBCARES_LIBS="-L$DEST/lib" \
LIBSSH2_CFLAGS="-I$DEST/include" \
LIBSSH2_LIBS="-L$DEST/lib" \
ARIA2_STATIC=yes 

$MAKE \
LIBS="-static -lz -lssl -lcrypto -lsqlite3 -lcares -lxml2 -lssh2"

make install DESTDIR=$BASE/aria2_ipkg_install-commit-121616
....

**Comment by tatsuhiro-t** [comment]
We rewrote configure script to use pkg-config to detect some libraries.  They may wrongly find native libraries, and pull those linker paths.
The affected libraries are:

* cppunit
* libxml2
* libexpat
* libnettle

You configuration rules out libexpat and libnettle.
Setting PKG_CONFIG_PATH to the cross compiled library path might solve the issue.

**Comment by leandroong** [comment]
Tatsuhiro-t, Thanks a lot. Cross-compilation went successful after added the ff:
Note2: Fixed, added the ff:
...
export PKG_CONFIG_PATH=$DEST/lib/pkgconfig:$PKG_CONFIG_PATH
...

###
#ARIA2
###
...
LIBXML2_CFLAGS="-I$DEST/include/libxml2" \
LIBXML2_LIBS="-L$DEST/lib" \
...
