### ISSUE TITLE
Build problem in Debian 7

### ISSUE THREAD

**Issue by Jimmy-Z** [aria2/aria2#806]
````
In file included from AbstractAuthResolver.cc:35:0:
AbstractAuthResolver.h:46:11: error: looser throw specifier for ‘virtual aria2::AbstractAuthResolver::~AbstractAuthResolver()’
In file included from AbstractAuthResolver.h:38:0,
                 from AbstractAuthResolver.cc:35:
AuthResolver.h:49:11: error:   overriding ‘virtual aria2::AuthResolver::~AuthResolver() noexcept (true)’
````

bisected recent releases, this was introduced in 1.27, 1.26.1 or older builds fine.

**Comment by tatsuhiro-t** [comment]
I think this is caused by older C++ compiler.
We used to require gcc 4.8.3 or clang-3.5, but recent changes may require more recent ones.
Which version of compiler are you using?

**Comment by Jimmy-Z** [comment]
The one comes with debian 7, 4.7.2
https://packages.debian.org/wheezy/gcc

**Comment by Jimmy-Z** [comment]
I tried to fix this by adding "noexcept(true)" to those declarations, only ended with this:
````
  CXX      download_handlers.lo
In file included from BencodeDiskWriter.h:38:0,
                 from BencodeDiskWriterFactory.h:39,
                 from MemoryBencodePreDownloadHandler.h:39,
                 from download_handlers.cc:45:
ValueBaseDiskWriter.h: In instantiation of ‘class aria2::ValueBaseDiskWriter<aria2::bittorrent::BencodeParser>’:
download_handlers.cc:105:66:   required from here
ValueBaseDiskWriter.h:51:11: error: function ‘aria2::ValueBaseDiskWriter<ValueBaseParser>::~ValueBaseDiskWriter() [with ValueBaseParser = aria2::bittorrent::BencodeParser]’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘aria2::ValueBaseDiskWriter<aria2::bittorrent::BencodeParser>::~ValueBaseDiskWriter()’
````
I'd admit I know almost nothing about C++

**Comment by tatsuhiro-t** [comment]
You have to undoing 366e2e8f795e82e2c8472bcf1cd0a892550789a9
That is basically replace "= default" with "{}".

**Comment by q3aql** [comment]
@Jimmy-Z You can try these builds:

* [aria2-1.30.0-linux-gnu-32bit-build1.tar.bz2](https://github.com/q3aql/aria2-static-builds/releases/download/v1.30.0/aria2-1.30.0-linux-gnu-32bit-build1.tar.bz2)
* [aria2-1.30.0-linux-gnu-64bit-build1.tar.bz2](https://github.com/q3aql/aria2-static-builds/releases/download/v1.30.0/aria2-1.30.0-linux-gnu-64bit-build1.tar.bz2)

**Comment by Jimmy-Z** [comment]
thanks, never knew there was a ARIA2_STATIC=yes
