### ISSUE TITLE
Don't succeed to use addTorrent XML-RPC method with XMLRPC::Lite perl module

### ISSUE THREAD

**Issue by canarem33** [aria2/aria2#809]
Hi,

I work on a project in which I need to send XML-RPC command using XMLRPC::Lite perl module. I succeed to send many other commands but I don't succeed to use addTorrent method.
Hereafter an extract of my code:
`use XMLRPC::Lite;`
`use MIME::Base64 qw(encode_base64);`

`my $clientTorrent = $ARGV[0];`
`my $xmlrpc = XMLRPC::Lite->proxy('http://' . $clientTorrent . ':6800/rpc');`
`my $buf;`
`my $torrent;`
`open(FILE, '/opt/aria/aria2-master/src/testtest/config.log.torrent') or die "$!";`
`read(FILE, $buf, 10000);`
`close FILE;`
`$torrent = encode_base64($buf);`
`$xmlrpc->call('aria2.addTorrent', $torrent);`

Could someone help me?
Thanks in advance,
canarem33

**Comment by canarem33** [comment]
For your information,
I found my mistake, MIME::Base64 module shall not be used to encode torrent file. Just reading the file and sending it with addTorrent method works:
`open(FILE, '/opt/aria/aria2-master/src/testtest/config.log.torrent') or die "$!";
my $torrent = <FILE>;
close FILE;
my $result = $xmlrpc->call('aria2.addTorrent', $torrent)->result;`

canarem33

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
