### ISSUE TITLE
小白用户懵逼中

### ISSUE THREAD

**Issue by kiongweidong** [aria2/aria2#812]
下载到Mac过后安装，安装完成过后找不到在哪儿啊，完全不知道在哪里找，找了半天也找不到，更别说打开使用了！我承认我傻，能不能来一位大神告诉我在哪里a？？

**Comment by Jimmy-Z** [comment]
google aria2 Mac 教程

**Comment by tatsuhiro-t** [comment]
Issue should be written in English, thereby I close those issues not written in English unconditionally.
