### ISSUE TITLE
empty announce

### ISSUE THREAD

**Issue by fatdrag0n** [aria2/aria2#818]
I ran it on magnet and it saved torrent but I get empty announce from tracker trying to upload torrent to. 

$ ./aria2c --bt-metadata-only=true --bt-save-metadata=true 'magnet:?xt=urn:btih:fc030ad391d60080722cbdd6588d7e140f83cc85&dn=Sim%C4%81+Bin%C4%81+-+Iran%3A+Music+of+North+and+South+Khorassan+%282+CD%29+-+19&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969'

**Comment by fatdrag0n** [comment]
tried another magnet  and seems like torrent file created can't be uploaded to trackers! maybe bad metadata processing!

./aria2c --bt-metadata-only=true --bt-save-metadata=true 'magnet:?xt=urn:btih:8eed728523a7034df427ada254fa4487997db55d&dn=Frontline.S2016E15.Exodus.1080p.WEB-DL.AAC2.0.H.264-QUEENS&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969'
Password:

12/30 16:34:36 [NOTICE] Downloading 1 item(s)

12/30 16:34:36 [NOTICE] IPv4 DHT: listening on UDP port 6995

12/30 16:34:36 [NOTICE] IPv4 BitTorrent: listening on TCP port 6997

12/30 16:34:36 [NOTICE] IPv6 BitTorrent: listening on TCP port 6997
[#b8bf8a 84KiB/84KiB(100%) CN:14 SD:2]                                                           
12/30 16:34:40 [NOTICE] Download complete: [MEMORY][METADATA]Frontline.S2016E15.Exodus.1080p.WEB-DL.AAC2.0.H.264-QUEENS

12/30 16:34:40 [NOTICE] Saved metadata as /usr/local/aria2/bin/8eed728523a7034df427ada254fa4487997db55d.torrent.
                                                                                                 
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b8bf8a|OK  |       0B/s|[MEMORY][METADATA]Frontline.S2016E15.Exodus.1080p.WEB-DL.AAC2.0.H.264-QUEENS

Status Legend:
(OK):download completed.

**Comment by fatdrag0n** [comment]
I found another way to convert instead of using aria2

**Comment by tatsuhiro-t** [comment]
It looks like you have found the workaround. Closing this issue.
