### ISSUE TITLE
Web interface (UI) for Aria2

### ISSUE THREAD

**Issue by viharm** [aria2/aria2#819]
Hi, I have developed a non-Ajax modular web interface for download daemons with the first module for *Aria2*.

It can be found here... https://gitlab.com/viharm/Odux

It uses a php library I have forked and further developed (https://github.com/viharm/phpAria2rpc).

I hope that these two can be useful for both developers and users. I would highly appreciate if these were included on the Aria2 page.

Happy to discuss further.

Regards.

**Comment by tatsuhiro-t** [comment]
That is true that I have listed several webui on aria2 web site, but now I lean not to add another, since it will end up any project without proper evaluation.  Please do some other routes to advertise your work.

**Comment by viharm** [comment]
@tatsuhiro-t , thank you for taking the time to consider this.
