### ISSUE TITLE
max-concurrent-downloads clarification

### ISSUE THREAD

**Issue by stepanbujnak** [aria2/aria2#833]
Could anyone please clarify what the `max-concurrent-downloads` options actually does? Let's say I have 10x100mb files I want to download. I have set that `split=5`, `min-split-size=20M` and `max-concurrent-downloads=5`.

Each downloaded file should then be split into 5x20MB chunks.

Will the `max-concurrent-downloads` option make it download 5 chunks in parallel or 5 files in parallel? If it downloads 5 files at a time, how many chunks are downloaded in parallel?

Thank you.

**Comment by tatsuhiro-t** [comment]
max-concurrent-downloads limits the number of concurrent download item.  split and min-split-size functions inside the item.  Imagine that you have input file (see -i option) like this:

```
http://example.com/foo
http://example.com/bar
```

Here is 2 download items.  aria2 can download these items concurrently, and the number of the concurrency is controlled by max-concurrent-downloads.  OTOH, in each download item, you can configure the number of connections using split or min-split-size, etc.

**Comment by tatsuhiro-t** [comment]
That said, I found that current max-concurrent-downloads is a bit ambiguous.  Since we are in documentation freeze period for the next release, we will handle it after next release.

**Comment by manisoftwartist** [comment]
Also, what happens when we use this parameter for a small list of image files which are not huge? That is, to download a list of N_IMGS (just a random) image files with --max-concurrent-downloads 100, how does this option work?
