### ISSUE TITLE
Option rpc-certificate fails with symlink

### ISSUE THREAD

**Issue by asmolero** [aria2/aria2#835]
Config options rpc-certificate and rpc-certificate-key fail with  -> [OptionHandlerImpl.cc:555] errorCode=1 Is '/etc/letsencrypt[...]' a file? when the file is a symlink.

**Comment by asmolero** [comment]
Invalid. There were permission issues, although the error wasn't specific about them.

**Comment by tatsuhiro-t** [comment]
Thank you.  #836 fixes error message issue.
