### ISSUE TITLE
HTTP download Error HTTP response header....

### ISSUE THREAD

**Issue by liliass** [aria2/aria2#840]
Aria2 1.22.0
Device : MiRouter R1D

Download http file. 
showing error :  error HTTP response header was bad or unexpected. 

Pls Help.

**Comment by liliass** [comment]
root@XiaoQiang:/etc/misstar/applications/aria2/bin# /etc/misstar/applications/ar
ia2/bin/aria2c http://verify.iso.mirrors.ustc.edu.cn/ubuntu-releases/16.04.1/ubu
ntu-16.04.1-desktop-amd64.iso

01/25 00:52:37 [ERROR] CUID#7 - Download aborted. URI=http://verify.iso.mirrors.ustc.edu.cn/ubuntu-releases/16.04.1/ubuntu-16.04.1-desktop-amd64.iso
Exception: [AbstractCommand.cc:345] errorCode=22 URI=http://verify.iso.mirrors.ustc.edu.cn/ubuntu-releases/16.04.1/ubuntu-16.04.1-desktop-amd64.iso
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

01/25 00:52:37 [NOTICE] Download GID#0e8b0ec465c1f652 not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0e8b0e|ERR |       0B/s|http://verify.iso.mirrors.ustc.edu.cn/ubuntu-releases/16.04.1/ubuntu-16.04.1-desktop-amd64.iso

Status Legend:
(ERR):error occurred.

**Comment by liliass** [comment]
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 expat/2.1.0 sqlite3/3.9.2 OpenSSL/1.0.2e c-ares/1.10.0 libssh2/1.5.0
Compiler: gcc 5.2.0
  built by   i686-pc-linux-gnu
  targetting arm-none-linux-uclibcgnueabi
  on         Apr 17 2016 00:45:14
System: Linux 2.6.36 #1 SMP PREEMPT Thu Jul 7 19:22:17 CST 2016 armv7l

**Comment by tatsuhiro-t** [comment]
HTTP status code is 403.  It usually means that server refused to access the requested resource.  Can you download the same file using wget, and browser?  Does it require authentication?

**Comment by liliass** [comment]
issue can be closed. solved by restarting the router. 
Thanks

**Comment by tatsuhiro-t** [comment]
OK, close now.
