### ISSUE TITLE
using aria2 to transfer directories to thousands of machines.

### ISSUE THREAD

**Issue by sebalos314** [aria2/aria2#847]
I am intending to use aria2 to transfer big directories of files to thousands of machines on a LAN.
My plan is to tar the directory, create a .torrent file, and to seed the file from aria2 from the source machine, then to start aria2 on all systems.

Is there a better way to do it ? If the directory I am sharing is slightly modified, I will have to restart building the archive unfortunately but I do not see a better way for now to be efficient.

**Comment by tatsuhiro-t** [comment]
Metalink could be an alternative.  https://tools.ietf.org/html/rfc5854

**Comment by sebalos314** [comment]
thank you very much. I'll finish my prototype based on my 'basic' idea first. I'll definitely have a look at Metalink.
