### ISSUE TITLE
SSL initialization failed：The request is invalid.

### ISSUE THREAD

**Issue by BeatingChildren** [aria2/aria2#848]
My aria2 version is 1.31.0,support BitTorrent, GZip, HTTPS, Message Digest, Metalink, XML-RPC.But when i download from https,it throw an error

[root@localhost build]# /etc/aria2-1.31.0/bin/aria2c https://google.com

02/06 15:31:14 [NOTICE] Downloading 1 item(s)

02/06 15:31:14 [ERROR] CUID#7 - Download aborted. URI=https://google.com
Exception: [../../src/AbstractCommand.cc:351] errorCode=1 URI=https://google.com
  -> [../../src/SocketCore.cc:932] errorCode=1 SSL initialization failed：The request is invalid.

How can i fix it?
thk.

**Comment by tatsuhiro-t** [comment]
The error seems to come from gnutls.  Have you built aria2 by yourself?
It may be because gnutls is old.  I'm not sure it is the cause of the issue.
I use gnutls 3.5.8, and have no problem.
If you could, try building aria2 with openssl.

**Comment by BeatingChildren** [comment]
tks 👍 , i try to build aria2 --without-gnutls --with-openssl, it can work. And i try to install gnutls 3.5.8, build aria2 with gnutls, it can also work.
翻译英文真难。。。。  :-D

**Comment by chucklvip** [comment]
add this extra setting when aria2c start (Perhaps it should be written to the configuration file)

`check-certificate=false`
