### ISSUE TITLE
Exit status 1 when failed to preallocate disk space

### ISSUE THREAD

**Issue by stepanbujnak** [aria2/aria2#856]
When there is not enough disk space to download a file, the `ErrorCode` field of the `DownloadHandle` class equals to `1`, which is `unknown error`. What I would expect instead is to get `9` indicating that there wasn't enough disk space to download the file. Is this what's supposed to happen or is it actually an incorrect behavior?

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  The error code should be 9, but the error code is not propagated to the last error field.  #857 fixes it.
