### ISSUE TITLE
How can I download multiple torrents with different options?

### ISSUE THREAD

**Issue by sixpointzero** [aria2/aria2#858]
I'm trying to download multiple torrents with different options but I can't seem to figure out how.

For example, I have two torrent files `1.torrent` and `2.torrent`. `2.torrent` is a multi-file torrent and I'd like to download only the first file from it. However, I'd like to download everything that `1.torrent` can offer. Right now, doing this doesn't work as expected -

```
user@pc ~> aria2c -d /data/videos/ 1.torrent --select-file=1 2.torrent
```

The above command downloads only the first file from `1.torrent` and `2.torrent` which isn't expected.

Can `aria2` download multiple torrents simultaneously with different options if desired?

```
user@pc ~> aria2c -v
aria2 version 1.31.0
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 libxml2/2.9.4 sqlite3/3.16.2 GnuTLS/3.5.8 nettle GMP/6.1.2 c-ares/1.12.0 libssh2/1.8.0
Compiler: gcc 6.3.1 20170109
  built by   x86_64-pc-linux-gnu
  on         Jan 17 2017 10:25:57
System: Linux 4.4.50-1-lts #1 SMP Sat Feb 18 17:14:48 CET 2017 x86_64
```

**Comment by tatsuhiro-t** [comment]
There are several ways to achieve this.

###  Use -i input file option.

Example:

```
/path/to/1.torrent

/path/to/2.torrent
  select-file=1
```

See https://aria2.github.io/manual/en/html/aria2c.html#input-file

If -i input file does not work, try aria2.addTorrent RPC method.

### aria2.addTorrent RPC method

See https://aria2.github.io/manual/en/html/aria2c.html#aria2.addTorrent

**Comment by sixpointzero** [comment]
The input file option seems to work. Thanks!
