### ISSUE TITLE
Option to immediately save control file

### ISSUE THREAD

**Issue by zingaburga** [aria2/aria2#859]
Aria2 seems to only save a control file on a graceful exit or (by default) every 60 seconds.  There doesn't appear to be a way to force a save, and will always wait at least 60 seconds after starting (or whatever is configured) before it saves the initial file.

It may be ideal, in some situations, if a blank control file could be immediately saved when the download is started.  Ideally, this control file should be written before the file to-be-downloaded is preallocated on disk.

This can be useful in some automation cases, for example, automatically resuming after a crash occurs.  With the current behavior, if a download starts but a crash or unexpected shutdown happens within 60 seconds (i.e. before it can write the control file), attempting to resume downloads will fail as the destination file already exists.  This can be worked around via `--allow-overwrite` but this isn't ideal if you actually want the process to fail if the file originally existed.  If a blank control file exists, aria2 can see that it needs to resume this download (although resume from the beginning) rather than fail due to a file existing.

A possible alternative may be to allow incomplete downloads to be named differently (#284), where, if it encounters such a file, it can be "resumed" (again, from the beginning) if no corresponding control file exists.

Thanks for the awesome tool and hope it makes sense :)  
(and apologies if something already exists to do this that I missed (I'm actually running an older version of aria2, and haven't checked whether the latest version acts differently))

**Comment by zingaburga** [comment]
It just came to me, but it may also be beneficial to also have an option to auto save the session file (if `--save-session` has been specified) whenever a download completes, otherwise attempting to resume can result in the process failing if a download has completed, but the updated session has yet been written to disk (`--save-session-interval` option specified).

As there is an RPC call to explicitly force it, I suppose one could make use of the on-complete hook to call a program, connect to RPC and force a session save, but it's a bit cumbersome and probably less reliable than doing it in the same process.

Thanks for reading!

**Comment by tatsuhiro-t** [comment]
I think it would be nice to write .aria2 control file as early as possible.  First such chance is when we determined the file size.  For metalink, and torrents, we know the file size in advance, so we can immediately write .aria2 file.

It sounds nice to save --save-session file when a download finishes.
One thing I'm concerned is that people use to put thousand of lines in input file.  If there are lots of tiny files, writing session file per file could take some time, which pauses actual download processing, and causes download slower.  Perhaps, explicit toggle option for this feature would be nice.

**Comment by zingaburga** [comment]
> I think it would be nice to write .aria2 control file as early as possible. First such chance is when we determined the file size.

Makes sense, since you can only falloc the file after you know the file size (so you can write control file before main file is written).

And yeah, I can see I/O being a problem if there are lots of small files, so an option is ideal.  This is also the same for the control file (lots of small files can cause unnecessary .aria2 files to be written), so an option for that (or maybe combine the two) could be useful.

Thanks for sharing your thoughts!

**Comment by tatsuhiro-t** [comment]
#861 implements early save of control file.  Since the number of save operation of the control file is limited by concurrency, it is expected to within the small number.  I think no toggle option is necessary.

**Comment by zingaburga** [comment]
Finally managed to get a build working, and it looks great!

Thanks for the change :)

**Comment by Deadooshka** [comment]
so using of `aria2.saveSession()` upon adding downloads will make no sense?
