### ISSUE TITLE
get torrent file from magnet.-

### ISSUE THREAD

**Issue by jimsrc** [aria2/aria2#873]
I would like to download get the torrent file associated to a given magnet link.
I found [this](https://github.com/NapoleonWils0n/cerberus/blob/master/aria2c/aria2c-convert-magnet-links-to-torrent.sh) and [this](http://askubuntu.com/questions/387805/download-torrents-with-aria2c), where they suggest something like:
```bash
aria2c --bt-metadata-only=true --bt-save-metadata=true --listen-port=6881 "magnet link url goes here" # I also tried deleting the "listen-port"
```
As those posts are from 3 years ago, I guess the changes in aria2 implementation made them useless now?
Is aria2 implemented such that it **can** do it?

**Comment by tatsuhiro-t** [comment]
It should work.  A torrent file whose name is hex string of info hash should be created in the directory which -d option specifies.  Did you get any errors?

**Comment by jimsrc** [comment]
Ok, now it works if I add a "-d" argument. Specifically:
```bash
aria2c -d ~/torrents --bt-metadata-only=true --bt-save-metadata=true --listen-port=6881 "magnet link url" ## Works nice
```

**Comment by 07416** [comment]
>    aria2c -d ~/torrents --bt-metadata-only=true --bt-save-metadata=true --listen-port=6881 "magnet link url"

`--listen-port=6881` may not be necessary.

**Comment by 0wwafa** [comment]
Here you go:

https://zibri.github.io/aria2magnet/
