### ISSUE TITLE
How to set GID manually for metalinks?

### ISSUE THREAD

**Issue by alireza-amirsamimi** [aria2/aria2#877]
Hello
I can't set GID for metalinks .
I tried --gid option but did not work.
for example (my metalink file is openSUSE-Leap-42.3-DVD-x86_64-Build0149-Media.iso.meta4) : 
```
aria2c --gid='6eedf0' ~/openSUSE-Leap-42.3-DVD-x86_64-Build0149-Media.iso.meta4 

```
after this command download started but my desired GID didn't set .

I also tried python3 xml rpc
```
dict = {'gid' = '6eedf0' }
server.aria2.addMetalink(xmlrpc.client.Binary(open(metalink_file_address, 'rb').read()) , dict  )
```
after this download started but my desired GID didn't set.

Can you guid me, please

--------------------------------
I'm archlinux user
aria2 version 1.31.0

**Comment by tatsuhiro-t** [comment]
aria2 uses newly generated gid(s) to download files described in Metalink file.
You can query these gid by checking "followedBy" (see https://aria2.github.io/manual/en/html/aria2c.html#aria2.tellStatus).

**Comment by alireza-amirsamimi** [comment]
Thank you 👍
