### ISSUE TITLE
Print information about each redirect

### ISSUE THREAD

**Issue by SumatraPeter** [aria2/aria2#884]
aria2 currently follows redirects completely silently. It would be nice if it can at least print an [INFO] or [NOTICE] for each redirect as part of the program's normal output and not just in the log. For example:

[INFO] original_url -> redirected_url
or
[NOTICE] original_url -> redirected_url

**Comment by tatsuhiro-t** [comment]
Currently, we have the following INFO level log:

```
2017-04-09 16:57:21.359724 [INFO] [HttpResponse.cc:169] CUID#7 - Redirecting to http://localhost/foo/
```

**Comment by SumatraPeter** [comment]
IMO a download utility should display important info. like the actual file URL as part of its normal output instead of burying it away in a huge log. So moving that INFO message to aria2's normal output would be my preferred option.

If you don't want to do that for some reason (although I can't think why), then my second suggestion would be this: cURL for example has a verbose option (-v) that prints certain messages to stdout. Would it be possible to have a similar -v option for aria2 that displays only certain important messages from the log (such as actual download URL) as part of the normal output? That would be far better than for example using --log=- and searching the entire huge log for info. such as this.

**Comment by tatsuhiro-t** [comment]
I'm fine to change log level form INFO to NOTICE for this particular log.
