### ISSUE TITLE
g++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by NPCHK** [aria2/aria2#887]
configure: summary of build options:

    version:        1.0.1-DEV shared 0:1:0
    Host type:      x86_64-unknown-linux-gnu
    Install prefix: /usr/local
    C compiler:     gcc
    CFlags:         -g -O2
    Library types:  Shared=yes, Static=yes
    CUnit:          no
    Nettle:         yes
    Build examples: yes

configure: summary of build options:

Build:          x86_64-unknown-linux-gnu
Host:           x86_64-unknown-linux-gnu
Target:         x86_64-unknown-linux-gnu
Install prefix: /usr/local
CC:             gcc
CXX:            g++
CPP:            gcc -E
CXXFLAGS:       -g -O2
CFLAGS:         -g -O2
CPPFLAGS:       
LDFLAGS:        
LIBS:           
DEFS:           -DHAVE_CONFIG_H
CXX1XCXXFLAGS:   -std=c++11 
EXTRACXXFLAGS:   -pipe
EXTRACFLAGS:     -pipe
EXTRACPPFLAGS:  
EXTRALDFLAGS:   
EXTRALIBS:      
WARNCXXFLAGS:   
LibUV:          no (CFLAGS='' LIBS='')
SQLite3:        yes (CFLAGS='' LIBS='-lsqlite3 ')
SSL Support:    yes
AppleTLS:       no (LDFLAGS='')
WinTLS:         no (LIBS='')
GnuTLS:         yes (CFLAGS='-I/usr/include/p11-kit-1 ' LIBS='-lgnutls ')
OpenSSL:        no (CFLAGS='' LIBS='')
CA Bundle:      
LibNettle:      yes (CFLAGS='' LIBS='-lnettle ')
LibGmp:         yes (CFLAGS='' LIBS='-lgmp')
LibGcrypt:      no (CFLAGS='' LIBS='')
LibXML2:        yes (CFLAGS='-I/usr/include/libxml2 ' LIBS='-lxml2 ')
LibExpat:       no (CFLAGS='' LIBS='')
LibCares:       yes (CFLAGS='' LIBS='-lcares ')
Zlib:           yes (CFLAGS='' LIBS='-L/usr/lib/x86_64-linux-gnu -lz ')
Libssh2:        yes (CFLAGS='' LIBS='-lssh2 ')
Tcmalloc:       no (CFLAGS='' LIBS='')
Jemalloc:       no (CFLAGS='' LIBS='')
Epoll:          yes
Bittorrent:     yes
Metalink:       yes
XML-RPC:        yes
Message Digest: libnettle
WebSocket:      yes (CFLAGS='-I$(top_builddir)/deps/wslay/lib/includes -I$(top_srcdir)/deps/wslay/lib/includes' LIBS='$(top_builddir)/deps/wslay/lib/libwslay.la')
Libaria2:       no (shared=yes static=no)
bash_completion dir: ${datarootdir}/doc/${PACKAGE_TARNAME}/bash_completion
Static build:   no

-----------------------------------------------------------------------

  CXX      OptionHandlerException.lo
  CXX      OptionHandlerFactory.lo
{standard input}: Assembler messages:
{standard input}:1907: Warning: end of file in string; '"' inserted
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:2291: recipe for target 'OptionHandlerFactory.lo' failed
make[3]: *** [OptionHandlerFactory.lo] Error 1
make[3]: Leaving directory '/root/aria2/src'
Makefile:2329: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/aria2/src'
Makefile:544: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/aria2'
Makefile:454: recipe for target 'all' failed
make: *** [all] Error 2

-----------------------------------------------------------------------
usr/share/doc/gcc-4.9/README.Bugs:
[README.Bugs.txt](https://github.com/aria2/aria2/files/919527/README.Bugs.txt)

**Comment by tatsuhiro-t** [comment]
This looks like gcc bug, not aria2.

**Comment by AnselmD** [comment]
Maybe you do not have enough memory?

See: c++: internal compiler error: Killed (program cc1plus) · Issue #224 · Valloric/ycmd · GitHub
https://github.com/Valloric/ycmd/issues/224

luascript.cpp.o Warning: end of file in string Ubuntu 14.04x64 - SOLVED · Issue #1408 · otland/forgottenserver · GitHub
https://github.com/otland/forgottenserver/issues/1408
