### ISSUE TITLE
win10下面能不能用？

### ISSUE THREAD

**Issue by guoyan1983** [aria2/aria2#898]
win10下面能不能用？

**Comment by XhstormR** [comment]
能

**Comment by WuErMaO** [comment]
为什么我闪退呢

**Comment by lizongzeshunshun** [comment]
@WuErMaO 使用命令行运行 这是个命令行软件

**Comment by tatsuhiro-t** [comment]
Please use English here.

**Comment by guanjianli** [comment]
@tatsuhiro-t  He say that why i can not work in windows 10.

**Comment by smdhz** [comment]
Windows server 2016 runs it perfectly.

**Comment by 424778940z** [comment]
The OP is asking can win10 run aria2.
Seems he don't know aria2 is a cmdline program, and there is no gui popup so he is confused.

There is no issue here, close please.

For the OP:
Aria2是一个命令行程序, 并不提供图形界面, 你点开看到一个黑色窗口一闪而过是正常的. 详细使用方法请搜索一些中文资料学习.

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.

**Comment by scientificCommunity** [comment]
哈撒给
