### ISSUE TITLE
Reuse .torrent file instead of redownloading metadata for magnet URI after restarting aria2c

### ISSUE THREAD

**Issue by rabbitsmith** [aria2/aria2#909]
When a magnet URI is added to aria2 using JSON-RPC started using 
bt-save-metadata=true
rpc-save-upload-metadata=true
and other stuff using a configuration file
the metadata is downloaded and saved as a .torrent file, but after saving session and control files after partially downloading, and restarting without forcing, the torrent file is not used. The metadata file is downloaded again. Imagine this situation for a seeder using aria2 having 1000 torrents has to download metadata for all 1000 torrents again in case of a restart even if he/she has all metadata stored as a .torrent file in the same directory as the control files and the downloaded files are.

This can be accomplished by replacing the magnet uri to be saved into the input file using save-session by the path to the .torrent file.

Used aria2c 1.13.0 on Windows 10.

**Comment by BrutalSimplicity** [comment]
It sounds like you've solved your problem. Is this a question?

I would say do exactly that, if you restart during the middle of a download, just check for torrents with a .aria2 file (incomplete download), and then re-add the saved torrent metadata.

**Comment by rabbitsmith** [comment]
You're right, I found an answer. But my question is, could you name another BitTorrent client which accepts magnets 
, downloads metadata, but on restart, redownloads it again?
Why not implement this simple replacement while saving the session data?

**Comment by BrutalSimplicity** [comment]
I'm guessing because the metadata for the torrent is not included in the .aria2 file. **DISREGARD** It actually is included in the .aria2 file based on this https://aria2.github.io/manual/en/html/technical-notes.html#control-file-aria2-format. The `infohash` property should allow a torrent download to be resumed *methinks*.

@tatsuhiro-t This could be a useful feature. Unless, we're missing something and it's actually already implemented somewhere.

**Comment by tatsuhiro-t** [comment]
There is no way to use downloaded torrent file when magnet URI is saved in session file at the moment.
Since the downloaded torrent file has the particular name (hex string of infohash + .torrent), it can be used to by pass initial bootstrap with new toggle option.

**Comment by YorikSar** [comment]
This problem bugs me for some time now: I can download stuff using magnet links, but every time I restart aria2c after that it takes a lot of time to fetch all metadata from DHT again. Is it possible for aria2c to store some database of known torrent files and check it when magnet link is being added (and serve them via DHT as well)?

**Comment by tatsuhiro-t** [comment]
#916 fixes this issue by reading saved .torrent file (by --bt-save-metadata), and skip the metadata fetch from DHT if it is successful.

**Comment by YorikSar** [comment]
@tatsuhiro-t Great, thanks!

And what do you think about also serving known infohashes?

**Comment by tatsuhiro-t** [comment]
What do you mean by "serving known infohashes"?  Is it directly related to this issue?

**Comment by YorikSar** [comment]
@tatsuhiro-t No, it is not directly related to this issue. I'm talking about serving known torrent files over DHT to other magnet link users.
