### ISSUE TITLE
How to add download task to aria2 daemon which enabled RPC & token?

### ISSUE THREAD

**Issue by mpco** [aria2/aria2#914]
The command I tried:
`curl -s http://127.0.0.1:6800/jsonrpc -H "Content-Type: application/json" -H "Accept: application/json" --data '{"jsonrpc": "2.0","id":1, "method": "aria2.addUri", "params":["token:xxxx", ["http://xxxx.com/xxx.xxx"], {"out": "filename"}]}'`

Is there another way? aria2c?
When download task url and title are saved in variables of shell, how to add task to aria2 daemon?
Thank you!

**Comment by mozbugbox** [comment]
https://gitlab.com/mozbugbox/aria2daemon

**Comment by mpco** [comment]
Thank you.
