### ISSUE TITLE
regression: auto-save-interval=0 no longer works

### ISSUE THREAD

**Issue by metasieben** [aria2/aria2#917]
Since issue #859 has been fixed >auto-save-interval< set to zero, aka only create control-files when stopping a download, no longer works.

My use-case looks like this, my download-script uses the existence of a control-file to determine, if a download-process needs to be resumed or not.

Please add an option to generate control-files only when a download is canceled/stopped.

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.  #918 fixes this issue.
