### ISSUE TITLE
total length mismatch

### ISSUE THREAD

**Issue by a545774001** [aria2/aria2#919]
When I was trying to start download from a link,this error occured.
Could I skip this by edit some config?
`root@XiaoQiang:/userdisk/data/Aria2# aria2c http://tinyurl.com/lxgtcnq
[#b6dcb9 0B/0B CN:1 DL:0B]
05/22 01:26:17 [ERROR] CUID#6 - Download aborted. URI=http://tinyurl.com/lxgtcnq
Exception: [AbstractCommand.cc:366] errorCode=1 URI=https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B1112689522308342%2C490350098855141%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:1f3fI7M3KZuAQsfV8Vci%2FZ7krkU%3D&uid=4272329219&time=1495473733&dp-logid=3271512512792687044&dp-callid=0&vuk=4272329219&zipname=%E3%80%90%E6%89%B9%E9%87%8F%E4%B8%8B%E8%BD%BD%E3%80%91%E5%8D%83%E6%81%8B%E4%B8%87%E8%8A%B1%E5%80%92%E8%AE%A1%E6%97%B6%E7%AD%89.zip  -> [RequestGroup.cc:724] errorCode=1 Download aborted.
  -> [DefaultBtProgressInfoFile.cc:277] errorCode=1 total length mismatch. expected: 455784891, actual: 3909582076

05/22 01:26:17 [NOTICE] Download GID#b6dcb92b7c7ac233 not complete: /userdisk/data/Aria2/file

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b6dcb9|ERR |       0B/s|/userdisk/data/Aria2/file

Status Legend:
(ERR):error occurred.
`
Sorry about my poor English

**Comment by mostafa88** [comment]
I have the save issue, but the message is 

> [DefaultBtProgressInfoFile.cc:300] errorCode=1 total length mismatch. expected: 1223079221, actual: 0

@LessCat, Did your problem fixed?
Please specify how do you fix the issue?
