### ISSUE TITLE
osx darwin version is always missing

### ISSUE THREAD

**Issue by devildant** [aria2/aria2#920]
Hello,

i develop an personal projet (for download) from windows and mac os, and the 2 last releases no content the darwin version.

It is difficult for me to compile on mac, because it is a friend that lends me his, and I can't use it only a very few time.

it's possible to have osx version for 1.32.0  ? or for next release ?

ps good job aria2 is perfect

best regards

**Comment by nmaier** [comment]
https://github.com/aria2/aria2/issues/936#issuecomment-308696829

**Comment by devildant** [comment]
thx for your reply, and sorry for your problem (family, mac) ,  i hope everything will work out
