### ISSUE TITLE
What is the max value of max-concurrent-downloads (-j)?

### ISSUE THREAD

**Issue by Dingo64** [aria2/aria2#924]
What is the max value of max-concurrent-downloads?
I tried using 100 but it doesn't seem like it's downloading 100 links in parallel.

**Comment by myfreeer** [comment]
[OptionHandlerFactory.cc#L435](https://github.com/aria2/aria2/blob/9deb4210b2c94446126e66c7994d745643cd39c9/src/OptionHandlerFactory.cc#L435)
-1, infinite, or probably INT_MAX, but also limited by your cpu's single core performance, relating to #869

**Comment by Dingo64** [comment]
Thanks. I'll try to run more instances of aria2.
