### ISSUE TITLE
Where is macOS binary ?

### ISSUE THREAD

**Issue by testcaoy7** [aria2/aria2#936]
Official site states "There you can download source distribution and binaries for OS X, Windows and Android." 

However I only saw Windows and Android binary in the github download section.

**Comment by nmaier** [comment]
The last binaries I produced are here:
https://github.com/aria2/aria2/releases/tag/release-1.30.0

After that I had to deal with some family stuff in my real life etc, and then some technical issues like my mac breaking which did not allow me to do builds. I'll try to resume that shortly tho

**Comment by tatsuhiro-t** [comment]
@nmaier thank you!

**Comment by nmaier** [comment]
ok, 1.32.0 darwin binaries are now available

**Comment by testcaoy7** [comment]
@nmaier Thank you !!!

**Comment by shinecurve** [comment]
where is 1.34.0 darwin binaries?
