### ISSUE TITLE
Normal user cannot start aria2c

### ISSUE THREAD

**Issue by Windywind** [aria2/aria2#938]
It's strange to me, I have used aria2 on my CentOS server for a long whille, but recently, I installed a Ubuntu 17.04 GNOME on my laptop. And the aria2 doesn't work on it.

![screenshot from 2017-06-11 06-11-20](https://user-images.githubusercontent.com/9924858/27008556-ce4b9142-4e6c-11e7-86c4-ba5f4f258fd7.png)

I cannot run aria2 as a normal user, which is "wind" here. 

It is a sudoer, but I cannot run _aria2c_ even using "sudo aria2c".

The problem is the _logger_ has no access to the log file, as shown in the picture.

But on my CentOS server, everything works well.

Any idea? New kernel features? Ubuntu features?

**Comment by Windywind** [comment]
And I checked on my CentOS server, It IS run by normal user "wind", in deed, not user "root".

![screenshot from 2017-06-11 06-23-54](https://user-images.githubusercontent.com/9924858/27008634-92c9f864-4e6e-11e7-823f-280d36df0e69.png)

**Comment by rabbitsmith** [comment]
Try creating an empty log file manually and then starting aria2

**Comment by Windywind** [comment]
Hi @rabbitsmith ,

I don't think that could be a solution, I knew that a empty session file is needed, but not a log file. Moreover, I found a log file already exist in the path prompted. see below

![screenshot from 2017-06-12 03-43-57](https://user-images.githubusercontent.com/9924858/27017633-c0d16086-4f21-11e7-9285-a3133efe2541.png)

**Comment by Windywind** [comment]
@rabbitsmith 
And I recreated the log file, as I have expected, this did not work.
![screenshot from 2017-06-12 03-49-18](https://user-images.githubusercontent.com/9924858/27017684-4404a292-4f22-11e7-8950-5bfc6a19feb7.png)

**Comment by smdhz** [comment]
chmod +w /etc/aria2/aria2.log

**Comment by Windywind** [comment]
The way to work around is, to make the log file and session file both writable for "others".
So now, these two files are look like this:
`-rw-rw-rw- 1 root root 21980 Jun 12 03:51 aria2.log`
`-rw-rw-rw- 1 root root     0 Jun  7 18:56 aria2.session`

**Comment by Windywind** [comment]
Alright, I have found the cause.

I have no _log_ configuration on my CentOS server, but I do have log configure on my Ubuntu GNOME. And for a normal user, of course it has no access to a owned by root.

solved.
