### ISSUE TITLE
Is there a way to make all threads to download the first blocks first?

### ISSUE THREAD

**Issue by markx** [aria2/aria2#946]
I'm trying to use multiple connections to download a video file from a HTTP host, and the file is big(say 1 GB).

IIRC, currently the file will be splited equally, and then each connection starts at each one split. For example, if I use 2 connections to download a 1000MB file, one connection will download from 0B, and the second connection will start from 500MB position.

Is it possible to make all connections to download the first blocks? (using the previous example, both threads download the first 500 MB together, then the last 500 MB).

Also, could you point to the code that is related to this logic? I wanted dig into the code myself but am entirely new to the codebase and don't know where to start.

**Comment by Jimmy-Z** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--stream-piece-selector

**Comment by markx** [comment]
Exactly what I needed. Thanks!

**Comment by Jimmy-Z** [comment]
Glad to help :)
