### ISSUE TITLE
Adding Headers

### ISSUE THREAD

**Issue by SakeenaQureshee** [aria2/aria2#962]
I want to send header along with the uri which I want to download via JSON-RPC
header is- **Authorization: Bearer [key]**

how the JSON-RPC request will look like if I want to send headers along with them?

In Aria2 Documentation, I was only able to find how to specify headers! I couldn't find where to add them in JSON request.

**JSON for specifying Headers:**
{'header':['Accept-Language: ja', 'Accept-Charset: utf-8']}

**JSON request for downloading:**
{'jsonrpc':'2.0', 'id':'qwer', 'method':'aria2.addUri', 'params':[['http://example.org/file']]}

**Comment by Jimmy-Z** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#aria2.addUri
`options is a struct and its members are pairs of option name and value. See Options below for more details.`
