### ISSUE TITLE
Manifest and VersionInfo (Windows)

### ISSUE THREAD

**Issue by eladkarako** [aria2/aria2#963]
Hi!
May I suggest adding a <em>Manifest</em> and a <em>VersionInfo</em> (as resources) for Windows-versions (x86/x64) of aria2c.exe, for a better compatibility in Windows.

Also the version-info is useful for making the application more trustworthy, since Windows will read those values when interacting with the user, also some online scanners (virustotal) read those and adds them to the overall clean signature.

<hr/>

anyway, I've actually wrote it,
but I suggest that you'll review it anyway before using it.

manifest (will work for either x86/x64 since it is not architecture specific...)
<pre>
&lt;?xml version="1.0" encoding="UTF-8" standalone="yes"?&gt;
&lt;asmv1:assembly xmlns="urn:schemas-microsoft-com:asm.v2" manifestVersion="1.0"
                xmlns:asmv1="urn:schemas-microsoft-com:asm.v1"
                xmlns:asmv2="urn:schemas-microsoft-com:asm.v2"
                xmlns:asmv3="urn:schemas-microsoft-com:asm.v3"&gt;

  &lt;asmv1:assemblyIdentity type="win32" language="neutral" processorArchitecture="msil"
                          name="aria2c.exe" version="1.3.2.0" /&gt;

  &lt;compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"&gt;
    &lt;application&gt;
      &lt;supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"&gt;&lt;/supportedOS&gt; &lt;!-- Windows 10 and Windows Server 2016      --&gt;
      &lt;supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"&gt;&lt;/supportedOS&gt; &lt;!-- Windows 8.1 and Windows Server 2012 R2  --&gt;
      &lt;supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"&gt;&lt;/supportedOS&gt; &lt;!-- Windows 8 and Windows Server 2012       --&gt;
      &lt;supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"&gt;&lt;/supportedOS&gt; &lt;!-- Windows 7 and Windows Server 2008 R2    --&gt;
      &lt;supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"&gt;&lt;/supportedOS&gt; &lt;!-- Windows Vista and Windows Server 2008   --&gt;
    &lt;/application&gt;
  &lt;/compatibility&gt;

  &lt;trustInfo&gt;
    &lt;security&gt;
      &lt;requestedPrivileges&gt;
        &lt;requestedExecutionLevel level="asInvoker" uiAccess="false" /&gt;
      &lt;/requestedPrivileges&gt;
    &lt;/security&gt;
  &lt;/trustInfo&gt;
&lt;/asmv1:assembly&gt;
</pre>

<em>minified (prefered):</em>
<code>&lt;?xml version="1.0" encoding="UTF-8" standalone="yes"?&gt;&lt;asmv1:assembly xmlns="urn:schemas-microsoft-com:asm.v2" manifestVersion="1.0" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3"&gt;&lt;asmv1:assemblyIdentity type="win32" language="neutral" processorArchitecture="msil" name="aria2c.exe" version="1.3.2.0"/&gt;&lt;compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"&gt;&lt;application&gt;&lt;supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"&gt;&lt;/supportedOS&gt;&lt;supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"&gt;&lt;/supportedOS&gt;&lt;supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"&gt;&lt;/supportedOS&gt;&lt;supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"&gt;&lt;/supportedOS&gt;&lt;supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"&gt;&lt;/supportedOS&gt;&lt;/application&gt;&lt;/compatibility&gt;&lt;trustInfo&gt;&lt;security&gt;&lt;requestedPrivileges&gt;&lt;requestedExecutionLevel level="asInvoker" uiAccess="false"/&gt;&lt;/requestedPrivileges&gt;&lt;/security&gt;&lt;/trustInfo&gt;&lt;/asmv1:assembly&gt;</code>

and here is a <code>VersionInfo</code> block for the application too..
I didn't what to wrote exactly so I guess it will need some editing too..
 (should work for either x86/x64)

<pre>

1 VERSIONINFO
FILEVERSION 1,3,2,0
PRODUCTVERSION 1,3,2,0
FILEOS 0x4
FILETYPE 0x1
{
BLOCK "StringFileInfo"
{
	BLOCK "040904b0"
	{
		VALUE "CompanyName", "The Aria2c Authors"
		VALUE "FileDescription", "aria2 is a utility for downloading files"
		VALUE "FileVersion", "1.3.2.0"
		VALUE "InternalName", "aria2c"
		VALUE "LegalCopyright", "Copyright 2017 The Aria2 Authors. All rights reserved."
		VALUE "ProductName", "Aria2 executable"
		VALUE "OriginalFilename", "aria2c.exe"
		VALUE "ProductVersion", "1.3.2.0"
		VALUE "CompanyShortName", "The Aria2 Authors"
		VALUE "ProductShortName", "Aria2 Installer"
		VALUE "LastChange", "823bcc4ab0d2ca3b9f3da282f0e6bd7b342b7d94-refs/heads/master@{#823bcc4}"
		VALUE "Official Build", "0"
	}
}

BLOCK "VarFileInfo"
{
	VALUE "Translation", 0x0409 0x04B0
}
}

</pre>

You can get the compiled <code>res</code> file
from here: <a href="https://gist.github.com/eladkarako/b2eba8ea8e8e6a2a54cc14a9a5f5a198#file-versioninfo_and_manifest_compiled_and_ready_to_be_import_using__resourcehacker_for_example-res">https://gist.github.com/eladkarako/b2eba8ea8e8e6a2a54cc14a9a5f5a198#file-versioninfo_and_manifest_compiled_and_ready_to_be_import_using__resourcehacker_for_example-res</a>

<img src="https://i.imgur.com/SgWJEIp.png" />

<sub>Ps. <em>I've tried editing it first, but it seems that the Windows builds have a non standard head/data section which makes on-the-fly resource not possible, so this is probably something you'll want to add to the make file..</em></sub>

**Comment by eladkarako** [comment]
I've could not add a manifest as an embedded resource to <code>aria2c.exe</code>,
using my <a href="https://github.com/eladkarako/manifest/">manifest tool</a>,
since the data sections are not standard, so <code>mt.exe</code> from Windows-SDK can't identify <code>aria2c.exe</code> as a valid binary, something wrong with its pe-headers...

I would probably fix the makefile(s) but for now I've used a <a href="https://gist.github.com/eladkarako/d24d5ed3c917ef230b0fc990104f9fe6">workaround</a> to have an external manifest file.

then I've used <a href="https://github.com/eladkarako/manifest/blob/master/generic.manifest">a generic manifest</a>, renamed it to aria2c.exe.manifest and placed it in the same folder as <code>aria2c.exe</code>, windows 10 allows it to run out side of the file/registry-virtualization, and it runs a lot faster too.

I don't have a workaround for the VersionInfo part, it should be an embedded resource (compilation time, before any packet-protectors etc...)

what compiler do you use for the releases?
since the result is not identifiable and any change to the binary file result in corruption of the binary file...

<img src="https://i.imgur.com/qUdAqkT.gif"/>

<img src="https://i.imgur.com/1fwD0PN.gif"/>

**Comment by tatsuhiro-t** [comment]
I use mingw-w64 cross compiler.  https://github.com/aria2/aria2/blob/master/README.mingw

**Comment by eladkarako** [comment]
I'll try to see if <a href="https://github.com/eladkarako/gcc-res">this gcc command</a> will work with the make file.

**Comment by eladkarako** [comment]
I'm using a <a href="https://github.com/eladkarako/mods/tree/master/Aria2">slightly modified version</a> of the statically link version from <a href="https://github.com/q3aql/aria2-static-builds/">github.com/q3aql/aria2-static-builds/</a>. It allows rewriting the manifest and VERSIONINFO binary blocks without corrupting the binary execute. You might as well run a quick diff or close <a href="https://github.com/aria2/aria2/issues/963/">this one</a> all together (and maybe https://github.com/aria2/aria2/issues/1075 too?)
