### ISSUE TITLE
I installed aria2-1.32.0-osx-darwin-build2.dmg on my mac,but I can't find it anywhere?

### ISSUE THREAD

**Issue by SuAdrenine** [aria2/aria2#965]
I installed aria2-1.32.0-osx-darwin-build2.dmg on my mac,but I can't find it anywhere?It's not in the application folder and anywhere else.

**Comment by nmaier** [comment]
It will install into '/usr/local/aria2/bin/aria2c' but will be in the PATH of new terminals so just `aria2c <param>` should work.
