### ISSUE TITLE
Daemonized aria2 1.32.0 crashes/quits on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by stangri** [aria2/aria2#972]
I've been using aria2 for more than 2 years and it seems that ever since I've upgraded to the self-compiled 1.32.0, aria2 sometimes quits/crashes from time to time.
There's nothing exceptional in /var/log/aria2/aria2.log about it.
Just creating this issue to see if anyone else is experiencing same problem. Also, if there're ways to monitor/troubleshoot this problem, please let me know.

**Comment by nmaier** [comment]
Honestly, daemon() is kinda deprecated, and not properly implemented a lot of times. We should remove that feature and advice users to run aria2 with some kind of init script or even in a screen/tmux

**Comment by stangri** [comment]
I am using an init script below. If there's a better one I should use, please advise.
```sh
# cat /etc/init.d/aria2
#!/bin/sh
### BEGIN INIT INFO
# Provides: aria2cRPC
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: aria2c RPC init script.
# Description: Starts and stops aria2 RPC services.
### END INIT INFO
#USER="root"
USER="stangri"
DAEMON=/usr/bin/aria2c
CONF=/etc/aria2/aria2.conf
ARGS="--daemon --conf-path=$CONF"
start() {
if [ -f $CONF ]; then
logger -st ARIA2C "Starting aria2c daemon..."
start-stop-daemon -S -c $USER -x $DAEMON -- $ARGS
else
logger -st ARIA2C "Couldn't start aria2 daemon (no $CONF found)"
fi
}

stop() {
logger -st ARIA2C "Stoping aria2c daemon..."
start-stop-daemon -o -c $USER -K -u $USER -x $DAEMON
}

status() {
dbpid=`pgrep -fu $USER $DAEMON`
if [ -z "$dbpid" ]; then
logger -st ARIA2C "aria2c daemon not running."
else
logger -st ARIA2C "aria2c daemon running..."
fi
}

case "$1" in
start)
start
sleep 1
;;
stop)
stop
sleep 1
;;
restart)
stop
sleep 2
start
;;
status)
status
;;
*)
echo "Usage: {start|stop|restart|status}"
exit 1
esac

exit 0
```

**Comment by nmaier** [comment]
@stangri I don't even think you need --daemon in that init script. It should work fine without it
