### ISSUE TITLE
errorCode=22 status=403

### ISSUE THREAD

**Issue by nhunting** [aria2/aria2#973]
Hello - When I attempt to download large files from https://www2.census.gov I get this error:
[ERROR] CUID#7 - Download aborted. URI=https://www2.census.gov/programs-surveys/acs/summary_file/2010/data/5_year_entire_sf/Tracts_Block_Groups_Only.zip
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://www2.census.gov/programs-surveys/acs/summary_file/2010/data/5_year_entire_sf/Tracts_Block_Groups_Only.zip
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

The command I am using is as simple as possible, just:

aria2c.exe <URL>

The command works for smaller files. I can download the large files using a browser. 
Is there anything I am doing wrong? Thanks.

**Comment by tatsuhiro-t** [comment]
curl also gets 403.  Perhaps, it is server issue?

**Comment by nhunting** [comment]
Thanks. It seems very library-specific:
These do not work:
  * aria
  * curl
  * Chrome 

These do:
  * WinINet funtions built into Windows 
  * uGet for Windows 

Interesting. I'd rather use aria because the interface is so great and scriptable. aria is a great program.

**Comment by Jimmy-Z** [comment]
In my test Chrome works and wget/curl/aria2 doesn't, but it seems just like a UA test, --user-agent=Chrome works.

**Comment by nhunting** [comment]
Cool, thank you! I should have thought of that. I appreciate your help!

**Comment by Jimmy-Z** [comment]
Glad to help :)

**Comment by Andyk1n** [comment]
I met the same ’errorCode=22 status=403.But it is hard for me to figure out with your communication.I would appreciate some advise about fixing with “service issue”.

**Comment by Jimmy-Z** [comment]
HTTP 403 could be caused by a lot of things, you should probably start a new issue, AND describe your issue.
