### ISSUE TITLE
windows versions don't work

### ISSUE THREAD

**Issue by sy19890515** [aria2/aria2#974]
I downloaded both 32bit and 64bit versions for windows. but when I run the exe files, nothing happens.

**Comment by Jimmy-Z** [comment]
by "run the exe files" do you mean double click on them?
by "nothing happens" do you mean a black window flashes but disappears immediately?

**Comment by sy19890515** [comment]
@Jimmy-Z Yes, and I also try run it as admin, but still...

**Comment by Jimmy-Z** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#synopsis
And maybe you should google about what is a command line program first.

**Comment by sy19890515** [comment]
@Jimmy-Z Oh I see! Thank you so much! I didn't realize it was for command lines only

**Comment by Jimmy-Z** [comment]
I suppose you should click on that "close issue" button below.

**Comment by sy19890515** [comment]
@Jimmy-Z Oh sorry. I am new to here and not familiar with the features. Thanks for reminding me!
