### ISSUE TITLE
questions regarding static build

### ISSUE THREAD

**Issue by Jimmy-Z** [aria2/aria2#977]
````
  CXXLD    aria2c
/home/jimmyz/aria2/dep/lib/libsqlite3.a(sqlite3.o): In function `unixDlOpen':
/home/jimmyz/aria2/sqlite-autoconf-3200000/sqlite3.c:36536: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
./.libs/libaria2.a(util.o): In function `aria2::util::getHomeDir[abi:cxx11]()':
/home/jimmyz/aria2/aria2-1.32.0/src/util.cc:1406: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
./.libs/libaria2.a(SocketCore.o): In function `aria2::callGetaddrinfo(addrinfo**, char const*, char const*, int, int, int, int)':
/home/jimmyz/aria2/aria2-1.32.0/src/SocketCore.cc:1446: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/jimmyz/aria2/dep/lib/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':
b_sock.c:(.text+0x71): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
````
I googled a bit and found [this](https://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo) and [this](https://stackoverflow.com/questions/15165306/compile-a-static-binary-which-code-there-a-function-gethostbyname)
If I understood correctly, does that effectively rendered static linking useless?

For the record I'm building on arch, which doesn't provide static libraries, so I have to build all dependencies.

**Comment by kkartaltepe** [comment]
You can probably resolve the  gethostbyname by compiling glibc with static nss. See https://www.gnu.org/software/libc/manual/html_node/Configuring-and-compiling.html

Not sure if there is any similar method of resolving getpwuid which has pretty much the same issues for the same reasons as gethostbyname (maybe you can call out to `getent` if you want to trade dynamic linking for IPC).

 I'm not sure why you would want to statically link glibc, but as stated in the stackoverflow answers these calls are highly dependent on runtime configuration and libraries and static linking will almost guarantee they return wrong results in any system that isnt completely default.

**Comment by kkartaltepe** [comment]
It's also worth noting that the OpenSSL license used by aria2c is incompatible with the GPL so be sure to take care to follow licensing restrictions of the LGPL used by glibc when static linking if you intend on redistributing your build.

**Comment by Jimmy-Z** [comment]
Thank you for the extensive answer!

But how do I static link only some libraries? the configure script only comes with a ARIA2_STATIC option.

As for why I'd need a static build, my main problem is one of my target system is still debian 7, too old(or me been too lazy) to build aria2.

Plus building aria2 is a relatively time consuming task, with static build I can build it in one place and just copy around.

Anyway despite the warnings, the binary built on arch runs fine on debian 7 as far as I can tell.

**Comment by tatsuhiro-t** [comment]
One way is build only a static library, and just link it as usual.

**Comment by Jimmy-Z** [comment]
Thanks, I'll try that.

**Comment by samiam95124** [comment]
Just FYW, building glibc static does not solve the issue.
