### ISSUE TITLE
How to support HTTPS on Android?

### ISSUE THREAD

**Issue by anguni** [aria2/aria2#981]
I can't download file on HTTPS sites. What should I do?

**Comment by Jimmy-Z** [comment]
I can download HTTPS on Android fine, more information? how do you compile/get/run it?

**Comment by anguni** [comment]
I use aria2 by commond line on Juicessh

**Comment by Jimmy-Z** [comment]
You used JuiceSSH to connect to an Android device?

**Comment by anguni** [comment]
Thank you very much!

**Comment by Jimmy-Z** [comment]
Glad to help, I suppose you can press the "close" button below.
