### ISSUE TITLE
[ERROR] [util.cc:1953] CreateProcess() failed. Cannot execute user command.

### ISSUE THREAD

**Issue by zmni** [aria2/aria2#992]
```
Windows 8.1 x64
aria2c v1.32.0 x64
```
<pre lang="bash">E:\Bin\Py36
> aria.bat https://bootstrap.pypa.io/get-pip.py

08/25 10:52:22 [NOTICE] Downloading 1 item(s)
[#587907 1.4MiB/1.5MiB(95%) CN:1 DL:222KiB]
08/25 10:52:29 [NOTICE] Download complete: E:/Bin/Py36/get-pip.py
<b>2017-08-25 10:52:29.460211 [ERROR] [util.cc:1953] CreateProcess() failed. Cannot execute user command.</b>

<b>08/25 10:52:29 [ERROR] CreateProcess() failed. Cannot execute user command.</b>

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
587907|OK  |   224KiB/s|E:/Bin/Py36/get-pip.py

Status Legend:
(OK):download completed.</pre>

Inside `aria.bat`:  `@"%~dpn02c.exe" --conf-path="%~dpn02c.conf" %*`

Here is `aria2c.conf`:
<pre lang="properties"># Basic
continue=true
log=-

# HTTP/S-FTP
remote-time=true
retry-wait=60
user-agent="Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"

# Advanced
allow-overwrite=true
always-resume=true
auto-file-renaming=false
conditional-get=true
disable-ipv6=true
file-allocation=none
log-level=warn
on-download-complete=exit</pre>

Is there something wrong with my `aria.bat` or `aria2c.conf`? I'm sure I followed the manual correctly.

**Comment by tatsuhiro-t** [comment]
Try specifying absolute path in on-download-complete

**Comment by zmni** [comment]
My bad, completely skipped [Event Hook](https://aria2.github.io/manual/en/html/aria2c.html#event-hook) example doc.

Thanks a lot.. aria & external command run without problem now.
