### ISSUE TITLE
Please add support for iOS 

### ISSUE THREAD

**Issue by Wh0ba** [aria2/aria2#997]
The OS X version says " bad CPU type"

**Comment by hugetiny** [comment]
+1

**Comment by Wh0ba** [comment]
iOS builds are available here https://mcapollo.github.io/Public/

**Comment by nicknull** [comment]
> iOS builds are available here https://mcapollo.github.io/Public/
 i can't find it by the link https://mcapollo.github.io/Public/

**Comment by skytoup** [comment]
https://github.com/MCApollo/aria2/commit/8ad0fe8a721c61f1eefa9cd9a100fff61e227813

**Comment by codenamedpkt** [comment]
Recommend LibTerm for free one or Prompt if you like to pay some bucks. They support aria2c with by installing packages. Heads over Apple App Store and hit install. And there you go.
